function defaultRabbitPsoasFibril = createRabbitPsoasFibrilModel(...
                                      normPevkToActinAttachmentPoint,...
                                      normFiberLengthAtOneNormPassiveForce,...                                      
                                      outputMatFileLocation,...
                                      smallNumericallyNonZeroNumber,...
                                      flag_enableNumericallyNonZeroGradients,...
                                      flag_plotAllCurves,...
                                      flag_useOctave)

%%
% Add the directories needed to run this script
%%
%parametersDirectoryTreeMTParams     = genpath('parameters');
%parametersDirectoryTreeExperiments  = genpath('experiments');
%parametersDirectoryTreeModels       = genpath('models');
%parametersDirectoryTreeCurves       = genpath('curves');
%parametersDirectoryTreeSimulation   = genpath('simulation');
%addpath(parametersDirectoryTreeMTParams);
%addpath(parametersDirectoryTreeExperiments);
%addpath(parametersDirectoryTreeModels);
%addpath(parametersDirectoryTreeCurves);
%addpath(parametersDirectoryTreeSimulation);

if( smallNumericallyNonZeroNumber <= 0 &&...
    flag_enableNumericallyNonZeroGradients  )
  disp('Warning: flag_enableNumericallyNonZeroGradients is set to 1 and');
  disp('         smallNumericallyNonZeroNumber <= 0');
  disp('Setting smallNumericallyNonZeroNumber to be sqrt(sqrt(eps))');
  smallNumericallyNonZeroNumber = sqrt(sqrt(eps));
end

if(isempty(normPevkToActinAttachmentPoint))
  normPevkToActinAttachmentPoint        = 0.5;

  disp('normPevkToActinAttachmentPoint empty using default:');  
  fprintf('\t%f\n',normPevkToActinAttachmentPoint);
end

if(isempty(normFiberLengthAtOneNormPassiveForce))
  normFiberLengthAtOneNormPassiveForce        = 1.367732948060934e+00;

  disp('normFiberLengthAtOneNormPassiveForce empty using default');
  fprintf('\t%f\n',normFiberLengthAtOneNormPassiveForce);
end



postprocessingDirectoryTree     = genpath('postprocessing');
addpath(postprocessingDirectoryTree   );

%flag_useOctave = 0;
%flag_enableNumericallyNonZeroGradients    = 1;
%flag_plotEveryDefaultCurve = 0;

%smallNumericallyNonZeroNumber           = sqrt(sqrt(eps));



scaleOptimalFiberLength      = 1.0; 
scaleMaximumIsometricTension = 1;



[rabbitPsoasFibrilMusculotendonProperties, ...
 rabbitPsoasFibrilSarcomereProperties] = ...
    createRabbitPsoasFibril(  scaleOptimalFiberLength,...
                        scaleMaximumIsometricTension,...
                        normFiberLengthAtOneNormPassiveForce,...
                        normPevkToActinAttachmentPoint,...
                        flag_useOctave);

createMusculoTendonFcn = ...
  @(argScaleFiberLength,argScaleFiso)createRabbitPsoasFibril(...
                                        argScaleFiberLength,...
                                        argScaleFiso,...
                                        normFiberLengthAtOneNormPassiveForce,...
                                        normPevkToActinAttachmentPoint,...
                                        flag_useOctave); 
                                        
rabbitPsoasFibrilActiveForceLengthData  = [];
rabbitPsoasFibrilPassiveForceLengthData = [];

%We have no data to fit to, and so these options are not used
flag_solveForOptimalFiberLengthOfBestFit         = 0; 
shiftLengthActiveForceLengthCurveDescendingCurve = 0.;

[rabbitPsoasFibrilNormMuscleCurvesDefault,...
 rabbitPsoasFibrilMusculotendonPropertiesDefault,...
 rabbitPsoasFibrilSarcomerePropertiesDefault,... 
 activeForceLengthCurveAnnotationPoints,...
 rabbitPsoasFibrilActiveForceLengthDataDefault,...
 rabbitPsoasFibrilPassiveForceLengthDataDefault,...
 rabbitPsoasFibrilPassiveForceLengthCurveSettings]= ...
    createFittedMuscleCurves( ...
      rabbitPsoasFibrilMusculotendonProperties,...
      rabbitPsoasFibrilSarcomereProperties,...
      rabbitPsoasFibrilActiveForceLengthData,...
      rabbitPsoasFibrilPassiveForceLengthData,...
      shiftLengthActiveForceLengthCurveDescendingCurve,...
      flag_enableNumericallyNonZeroGradients,...
      smallNumericallyNonZeroNumber,...
      flag_solveForOptimalFiberLengthOfBestFit,...
      createMusculoTendonFcn,...
      flag_useOctave);



defaultRabbitPsoasFibril = struct('musculotendon',...
                            rabbitPsoasFibrilMusculotendonPropertiesDefault,...
                            'sarcomere',...
                            rabbitPsoasFibrilSarcomerePropertiesDefault,...
                            'falData',...
                            rabbitPsoasFibrilActiveForceLengthDataDefault,...
                            'fpeData',...
                            rabbitPsoasFibrilPassiveForceLengthDataDefault,...
                            'curves',...
                            rabbitPsoasFibrilNormMuscleCurvesDefault);
              
%'output/structs/defaultRabbitPsoasFibril.mat'                      
save(outputMatFileLocation,...
     'defaultRabbitPsoasFibril');  


if(flag_plotAllCurves==1)
  figH=figure;
  figH = plotStructOfBezierSplines( rabbitPsoasFibrilNormMuscleCurvesUpd_ET,...
                                  {'Inverse','use'});                          
end

   
