function defaultRabbitPsoasFibril = createRabbitPsoasFibrilModel(...
                                      normPevkToActinAttachmentPoint,...
                                      normFiberLengthAtOneNormPassiveForce,...                                      
                                      outputMatFileLocation,...
                                      smallNumericallyNonZeroNumber,...
                                      flag_enableNumericallyNonZeroGradients,...
                                      flag_plotAllCurves,...
                                      flag_useOctave)


%Potential variables to expose
rabbitPsoasFibrilActiveForceLengthData  = [];
rabbitPsoasFibrilPassiveForceLengthData = [];
scaleOptimalFiberLength      = 1.0; 
scaleMaximumIsometricTension = 1;


% Check the arguments
if( smallNumericallyNonZeroNumber <= 0 &&...
    flag_enableNumericallyNonZeroGradients  )
  disp('Warning: flag_enableNumericallyNonZeroGradients is set to 1 and');
  disp('         smallNumericallyNonZeroNumber <= 0');
  disp('Setting smallNumericallyNonZeroNumber to be sqrt(sqrt(eps))');
  smallNumericallyNonZeroNumber = sqrt(sqrt(eps));
end

if(isempty(normPevkToActinAttachmentPoint))
  normPevkToActinAttachmentPoint        = 0.5;

  disp('normPevkToActinAttachmentPoint empty using default:');  
  fprintf('\t%f\n',normPevkToActinAttachmentPoint);
end

if(isempty(normFiberLengthAtOneNormPassiveForce))
  normFiberLengthAtOneNormPassiveForce        = 1.367732948060934e+00;

  disp('normFiberLengthAtOneNormPassiveForce empty using default');
  fprintf('\t%f\n',normFiberLengthAtOneNormPassiveForce);
end



[rabbitPsoasFibrilMusculotendonProperties, ...
 rabbitPsoasFibrilSarcomereProperties] = ...
    createRabbitPsoasFibrilParameters(  scaleOptimalFiberLength,...
                        scaleMaximumIsometricTension,...
                        normFiberLengthAtOneNormPassiveForce,...
                        normPevkToActinAttachmentPoint,...
                        flag_useOctave);

createMusculoTendonFcn = ...
  @(argScaleFiberLength,argScaleFiso)createRabbitPsoasFibrilParameters(...
                                        argScaleFiberLength,...
                                        argScaleFiso,...
                                        normFiberLengthAtOneNormPassiveForce,...
                                        normPevkToActinAttachmentPoint,...
                                        flag_useOctave); 
                                        


%We have no data to fit to, and so these options cannot be used
flag_solveForOptimalFiberLengthOfBestFit         = 0; 
shiftLengthActiveForceLengthCurveDescendingCurve = 0.;

[rabbitPsoasFibrilNormMuscleCurvesDefault,...
 rabbitPsoasFibrilMusculotendonPropertiesDefault,...
 rabbitPsoasFibrilSarcomerePropertiesDefault,... 
 activeForceLengthCurveAnnotationPoints,...
 rabbitPsoasFibrilActiveForceLengthDataDefault,...
 rabbitPsoasFibrilPassiveForceLengthDataDefault,...
 rabbitPsoasFibrilPassiveForceLengthCurveSettings]= ...
    createFittedMuscleCurves( ...
      rabbitPsoasFibrilMusculotendonProperties,...
      rabbitPsoasFibrilSarcomereProperties,...
      rabbitPsoasFibrilActiveForceLengthData,...
      rabbitPsoasFibrilPassiveForceLengthData,...
      shiftLengthActiveForceLengthCurveDescendingCurve,...
      flag_enableNumericallyNonZeroGradients,...
      smallNumericallyNonZeroNumber,...
      flag_solveForOptimalFiberLengthOfBestFit,...
      createMusculoTendonFcn,...
      flag_useOctave);



defaultRabbitPsoasFibril = struct('musculotendon',...
                            rabbitPsoasFibrilMusculotendonPropertiesDefault,...
                            'sarcomere',...
                            rabbitPsoasFibrilSarcomerePropertiesDefault,...
                            'falData',...
                            rabbitPsoasFibrilActiveForceLengthDataDefault,...
                            'fpeData',...
                            rabbitPsoasFibrilPassiveForceLengthDataDefault,...
                            'curves',...
                            rabbitPsoasFibrilNormMuscleCurvesDefault);
              
%'output/structs/defaultRabbitPsoasFibril.mat'                      
save(outputMatFileLocation,...
     'defaultRabbitPsoasFibril');  

if(flag_plotAllCurves==1)
  figH=figure;
  figH = plotStructOfBezierSplines( rabbitPsoasFibrilNormMuscleCurvesUpd_ET,...
                                  {'Inverse','use'});                          
end

   
