%%
% SPDX-FileCopyrightText: 2023 Matthew Millard <millard.matthew@gmail.com>
%
% SPDX-License-Identifier: MIT
%
% If you use this code in your work please cite the pre-print of this paper
% or the most recent peer-reviewed version of this paper:
%
%    Matthew Millard, David W. Franklin, Walter Herzog. 
%    A three filament mechanistic model of musculotendon force and impedance. 
%    bioRxiv 2023.03.27.534347; doi: https://doi.org/10.1101/2023.03.27.534347 
%
%%

function [normMuscleCurves,...
          musculotendonPropertiesUpd,...
          sarcomerePropertiesUpd,...
          activeForceLengthCurveAnnotationPoints,...
          dataActiveForceLengthNormalized,...
          dataPassiveForceLengthNormalized,...
          forceLengthCurveSettings] = ...
          createFittedMuscleCurvesTRSS2017(...
                      musculotendonProperties,...
                      sarcomereProperties,...   
                      useWLCTitinModel,...                      
                      useCalibratedCurves,...      
                      useTwoSidedTitinCurves,...
                      useTitinModel2025,...
                      dataActiveForceLengthNormalized,...
                      dataPassiveForceLengthNormalized,...
                      shiftLengthActiveForceLengthCurveDescendingCurve,... 
                      useSharpForceVelocityCurve,...
                      fitTitinCurvesToTRSS2017,...                      
                      flag_enableNumericallyNonZeroGradients,...
                      smallNumericallyNonZeroNumber,...
                      flag_solveForOptimalFiberLengthOfBestFit,...
                      createMusculoTendonFcn,...
                      useElasticTendon,...
                      elasticTendonReferenceModel,...
                      projectFolders,...
                      flag_useOctave)
%%
% Will create all of the Bezier curves that are needed to simulate both
% Vexat and 2012 equilibrium muscle model
% 
% @param musculotendonProperties:
%   A struct that contains architectural properties of the muscle along with 
%   some additional mechanical properties. See the current example
%   in parameters/felineSoleus/getFelineSoleusMusculotendonProperties.m
%
% @param sarcomereProperties           
%   A struct that returns the normalized lengths of the various filaments
%   in the sarcomeres of the type of muscle being simulated in addition to
%   some additional properites related to cross bridge stiffness and damping
%   required in Vexat. See the current example in
%   in parameters/felineSoleus/getMammalianSkeletalMuscleNormalizedSarcomereProperties.m
%
% @param dataActiveForceLength
%   An n by two matrix where the first column is normalized fiber length 
%   and the second column is normalized active muscle force. For an example
%   please see
%   parameters/felineSoleus/getFelineSoleusMusculotendonData.m
%
% @param dataPassiveForceLength
%   An n by two matrix where the first column is normalized fiber length 
%   and the second column is normalized passive muscle force. For an example
%   please see
%   parameters/felineSoleus/getFelineSoleusMusculotendonData.m
%
% @param flag_enableNumericallyNonZeroGradients
%   Setting this to 1 will ensure that large curve sections that would otherwise 
%   have a slope of zero (e.g. the part of the active force length curve that is 
%   between 0 and close to 0.5, and is greater than 1.6) will have non-zero a
%   non zero slope with a magnitude equal to smallNumericallyNonZeroNumber.
%   This is particularly useful when using this muscle model in an optimization 
%   routine that does not tolerate gradients of zero.
%
% @param smallNumericallyNonZeroNumber
%   If flag_enableNumericallyNonZeroGradients is set to 1 then all of the
%   sections of the curves that would other wise have a slope of zero will
%   have a slope that is set to the value here. I recommend a value that
%   is for practical terms zero, but is greater than the tolerance used on 
%   the optimization problem.forceVelocity
%
%
% @param flag_solveForOptimalFiberLengthOfBestFit
%         When set to 1 an optimization run will be made in which the
%         optimal fiber length is scaled so that the distance between
%         the active force length curve and the normalized active 
%         force length data is minimized.
%
% @param createMusculoTendonFcn
%         A function that takes the arguments scaleFiberLength and
%         scaleMaximumIsometricTension and returns 4 structures:
%         musculotendonProperties, sarcomereProperties,
%         activeForceLengthData, and passiveForceLengthData.
%      
% @param flag_useOctave
%   Setting this to 1 will ensure that no parts of the code that are 
%   incompatible with octave are called.
%
% @return structs 
%   normMuscleCurves with these fields
%     activeForceLengthCurve,
%     fiberForceVelocityCurve
%     fiberForceLengthCurve
%     forceLengthECMHalfCurve
%     forceLengthIgPCurve
%     forceLengthPevkIgDCurve
%     tendonForceLengthCurve
%     tendonDampingLengthCurve
%
% sarcomerePropertiesUpd
%   identical to the sarcomere properties struct except in the case
%   when dataPassiveForceLength is not empty: in this case the field
%   extraCellularMatrixPassiveForceFraction has been updated so that
%   the combined passive forces developed by the ECM and titin
%   fit the passive force length curve data as closely as possible.
%%
    
% Note
%  These curves are really in here just for plotting purposes: the model
%  does not use them.
%
%  forceLengthIgpCurveHuman
%  forceLengthPevkIgdCurveHuman
%  forceLengthIgpCurveHumanB
%  forceLengthPevkIgdCurveHumanB

normMuscleCurves = struct('activeForceLengthCurve' ,            [],...
                          'fiberForceVelocityCurve',            [],...
                          'activeForceLengthCalibratedCurve' ,  [],...
                          'fiberForceVelocityCalibratedCurve',  [],...
                          'useWLCTitinModel',useWLCTitinModel,...
                          'useCalibratedCurves',useCalibratedCurves,...                          
                          'fiberForceLengthCurve'  ,        [],...
                          'fiberForceLengthInverseCurve'  , [],...                          
                          'forceLengthECMHalfCurve',        [],...
                          'forceLengthECMHalfInverseCurve', [],...                          
                          'forceLengthProximalTitinCurve',  [],...
                          'forceLengthDistalTitinCurve',    [],...
                          'forceLengthProximalTitinInverseCurve',  [],...
                          'forceLengthDistalTitinInverseCurve',    [],...
                          'forceLengthIgPTitinCurve',            [],...
                          'forceLengthPevkTitinCurve',        [],...
                          'forceLengthIgDTitinCurve',        [],... 
                          'forceLengthIgPTitinInverseCurve',            [],...
                          'forceLengthPevkTitinInverseCurve',        [],...
                          'forceLengthIgDTitinInverseCurve',        [],... 
                          'useTitinCurvesWithRigidIgDSegment', 0,...
                          'useTwoSidedTitinCurves', useTwoSidedTitinCurves,...
                          'useTitinModel2025', useTitinModel2025,...
                          'fiberForceVelocityInverseCurve', [],...
                          'fiberForceVelocityCalibratedInverseCurve',[],...
                          'tendonForceLengthCurve',         [],...
                          'tendonForceLengthInverseCurve',  [],...
                          'compressiveForceLengthCurve', []);

%                          'forceLengthProximalTitinTwoSidedCurve',  [],...
%                          'forceLengthDistalTitinTwoSidedCurve',    [],...
%                          'forceLengthProximalTitinInverseTwoSidedCurve',  [],...
%                          'forceLengthDistalTitinInverseTwoSidedCurve',    [],...
                        
%'forceLengthIgpCurveHuman',       [],...
%'forceLengthPevkIgdCurveHuman',   [],...
%'forceLengthIgpCurveHumanB',      [],...
%'forceLengthPevkIgdCurveHumanB',  [],...
%'forceLengthProximalTitinCurveHuman',  [],...
%'forceLengthDistalTitinCurveHuman',    [],...
%'forceLengthProximalTitinInverseCurveHuman',  [],...
%'forceLengthDistalTitinInverseCurveHuman',    [],...
%'forceLengthProximalTitinCurveTwoSidedHuman',  [],...
%'forceLengthDistalTitinCurveTwoSidedHuman',    [],...
%'forceLengthProximalTitinInverseCurveTwoSidedHuman',  [],...
%'forceLengthDistalTitinInverseCurveTwoSidedHuman',    [],...

curvinessActiveForceLength = 1.;                        
%%
%
% Scale the fiber length and maximum isometric force such that the
% active force length curve fits the data as closely as possible.
%%

if(flag_solveForOptimalFiberLengthOfBestFit==1 ...
      && isempty(createMusculoTendonFcn)==0 ...
      && isempty(dataActiveForceLengthNormalized)==0)
  x0 = [1.];
  errFcn = @(argX)calcScalingError(...
                    argX,...
                    createMusculoTendonFcn,...
                    curvinessActiveForceLength,...
                    shiftLengthActiveForceLengthCurveDescendingCurve,...
                    flag_enableNumericallyNonZeroGradients,...
                    smallNumericallyNonZeroNumber,...                                        
                    flag_useOctave);
  fvalStart = errFcn(1.0);
  A   = [];
  B   = [];
  Aeq = [];
  Beq = [];
  lb  = [0.5];
  ub  = [1.5];  
                                      
  [x,fval,exitflag]=fmincon( errFcn, x0, A,B,Aeq,Beq,lb,ub);

  assert(fval <= fvalStart, 'Error: fitting of lopt produced a worse result');
    
  scaleOptimalFiberLength       = x(1,1);
  scaleMaximumIsometricTension  = 1;
  
  [musculotendonProperties, ...
   sarcomereProperties,...
   dataActiveForceLengthNormalized,...
   dataPassiveForceLengthNormalized] = ...
      createMusculoTendonFcn(scaleOptimalFiberLength,...
                             scaleMaximumIsometricTension);
  
end

     
%musculotendonPropertiesUpd = musculotendonProperties;
%sarcomerePropertiesUpd     = sarcomereProperties;   
%dataActiveForceLengthUpd   = dataActiveForceLength;
%dataPassiveForceLengthUpd  = dataPassiveForceLength;

%%
% 
% Active-force-length curve:
%   :Build using sarcomere geometry. For now do not fit it
%%

fprintf('Building default curves ... \n')

flag_compensateForCrossbridgeStiffness = 0;
[normMuscleCurves.activeForceLengthCurve, ...
  activeForceLengthCurveAnnotationPoints] ...
    = createFiberActiveForceLengthCurve(...
          sarcomereProperties.normMyosinHalfLength*2,...
          sarcomereProperties.normMyosinBareHalfLength*2,...
          sarcomereProperties.normActinLength,...
          sarcomereProperties.normZLineLength,...
          sarcomereProperties.normSarcomereLengthZeroForce,...
          sarcomereProperties.normCrossBridgeStiffness,...          
          curvinessActiveForceLength, ...           
          shiftLengthActiveForceLengthCurveDescendingCurve,...
          flag_compensateForCrossbridgeStiffness,...          
          flag_enableNumericallyNonZeroGradients,...
          smallNumericallyNonZeroNumber,...
          musculotendonProperties.name,...
          flag_useOctave);  

fprintf('  activeForceLengthCurve created\n');

flag_compensateForCrossbridgeStiffness = 1;
[normMuscleCurves.activeForceLengthCalibratedCurve, ...
  activeForceLengthCurveAnnotationPointsCal] ...
    = createFiberActiveForceLengthCurve(...
          sarcomereProperties.normMyosinHalfLength*2,...
          sarcomereProperties.normMyosinBareHalfLength*2,...
          sarcomereProperties.normActinLength,...
          sarcomereProperties.normZLineLength,...
          sarcomereProperties.normSarcomereLengthZeroForce,...
          sarcomereProperties.normCrossBridgeStiffness,...          
          curvinessActiveForceLength, ...           
          shiftLengthActiveForceLengthCurveDescendingCurve,...
          flag_compensateForCrossbridgeStiffness,...          
          flag_enableNumericallyNonZeroGradients,...
          smallNumericallyNonZeroNumber,...
          musculotendonProperties.name,...
          flag_useOctave);  


fprintf('  activeForceLengthCalibratedCurve created\n');
%%
% 
% Force Velocity Curve
%
%%

curvinessEccentricForceVelocity = 0.9;

normMuscleCurves.fiberForceVelocityCurve ...
  = createFiberForceVelocityCurve(...
      musculotendonProperties.forceVelocityMultiplierAtHalfMaximumFiberVelocity,...
      musculotendonProperties.forceVelocityMultiplierAtLowEccentricFiberVelocity,...
      musculotendonProperties.forceVelocityMultiplierAtMaximumEccentricFiberVelocity,...
      curvinessEccentricForceVelocity,...
      flag_enableNumericallyNonZeroGradients,...
      smallNumericallyNonZeroNumber,...
      musculotendonProperties.name,...
      flag_useOctave);

if(useSharpForceVelocityCurve==1)

    dydxEcc_div_dydxConc = 5;
    %dydxEcc_div_dydxConc = 10;
    curvinessEccentricForceVelocitySharp = 0.95;
    
    normMuscleCurves.fiberForceVelocityCurve ...
      = createFiberForceVelocitySharpCurve(...
          musculotendonProperties.forceVelocityMultiplierAtHalfMaximumFiberVelocity,...
          musculotendonProperties.forceVelocityMultiplierAtLowEccentricFiberVelocity,...
          musculotendonProperties.forceVelocityMultiplierAtMaximumEccentricFiberVelocity,...
          curvinessEccentricForceVelocitySharp,...
          flag_enableNumericallyNonZeroGradients,...
          smallNumericallyNonZeroNumber,...
          musculotendonProperties.name,...
          dydxEcc_div_dydxConc,...
          flag_useOctave);

end


fprintf('  fiberForceVelocityCurve created\n'); 

normMuscleCurves.fiberForceVelocityInverseCurve = ...
  createInverseCurve(normMuscleCurves.fiberForceVelocityCurve);
fprintf('  fiberForceVelocityInverseCurve created\n');


normMuscleCurves.fiberForceVelocityCalibratedCurve = ...
normMuscleCurves.fiberForceVelocityCurve;


normMuscleCurves.fiberForceVelocityCalibratedCurve.xpts = ...
  normMuscleCurves.fiberForceVelocityCalibratedCurve.xpts ...
  .*sarcomereProperties.forceVelocityCalibrationFactor;

normMuscleCurves.fiberForceVelocityCalibratedCurve.xEnd = ...
  normMuscleCurves.fiberForceVelocityCalibratedCurve.xEnd ...
  .*sarcomereProperties.forceVelocityCalibrationFactor;

normMuscleCurves.fiberForceVelocityCalibratedCurve.dydxEnd = ...
  normMuscleCurves.fiberForceVelocityCalibratedCurve.dydxEnd ...
  ./sarcomereProperties.forceVelocityCalibrationFactor;

fprintf('  fiberForceVelocityCalibratedCurve created\n'); 

normMuscleCurves.fiberForceVelocityCalibratedInverseCurve = ...
  createInverseCurve(normMuscleCurves.fiberForceVelocityCalibratedCurve);
fprintf('  fiberForceVelocityCalibratedInverseCurve created\n');

%%
%
% Passive force length curve:
%   fit it to data, if its available. Otherwise use plausible defaults
%%
forceLengthCurveSettings = struct('normLengthZero',0,'normLengthToe',0,'fToe',0,...
                                  'kZero',0,'kToe',0,'curviness',0);



flag_passiveCurveFitted=0;    
%Fit the passive curve so that it has the same force-path-length curve
%as the elastic tendon MTU. 
if(useElasticTendon == 0 && ...
      isempty(elasticTendonReferenceModel)==0 && ...
      isempty(dataPassiveForceLengthNormalized) ==0)
  flag_passiveCurveFitted=1;
  normLengthZero           = sarcomereProperties.normFiberLengthAtZeroForce; 
  if(isfield(sarcomere,'normFiberLengthAtZeroPassiveForce'))
    normLengthZero = sarcomereProperties.normFiberLengthAtZeroPassiveForce;
  end   
  normLengthToe            = sarcomereProperties.normFiberLengthAtOneNormPassiveForce;

     
  dataPassiveForceLengthNormalized = [dataPassiveForceLengthNormalized;...
      sarcomereProperties.normFiberLengthAtOneNormPassiveForce,1];

  kLow            = 0.2;
  kZero           = 0;
  if(flag_enableNumericallyNonZeroGradients)
    kZero = smallNumericallyNonZeroNumber;
  end      
  fToe            = 1.0;  
  curviness       = 0.5;

  kNum            = 2;
  kToe            = kNum/(normLengthToe-normLengthZero);
  xshift          = min(dataPassiveForceLengthNormalized(:,1));
  xwidth          = 0.7;


  problemScaling  = 1000;
  params0         = [xshift        , xwidth, kNum].*problemScaling;
  paramsLB        = [0.8*xshift    ;    0.5; 1.05].*problemScaling;
  paramsUB        = [2.0           ;    2.0;    4].*problemScaling;
  
  fixedParams = [kLow,kZero,fToe,curviness];

  errFcn = @(argX)calcRigidToElasticTendonForceLengthCurveError(argX,...
                   problemScaling,fixedParams, ...
                   elasticTendonReferenceModel,flag_useOctave);  

  err0 = errFcn(params0);
  lsqOptions = optimoptions('lsqnonlin','Display','off',...
      'FinDiffType','central','FunctionTolerance',1e-8,'MaxIterations',5000);
  [x,resnorm,residual,exitflag,output,lambda,jacobian]    =...
      lsqnonlin(errFcn,params0,paramsLB,paramsUB,lsqOptions);
  err1 = errFcn(x);

  fprintf('  forceLengthCurve fitted to elastic tendon model, error reduced from %1.2e - %1.2e\n',...
      norm(err0),norm(err1));  

  xshift    = x(1)/problemScaling;
  xwidth    = x(2)/problemScaling;
  kNum      = x(3)/problemScaling;

  normLengthZero = xshift;
  normLengthToe  = xshift + xwidth;
  kToe      = kNum/(normLengthToe-normLengthZero);
  curviness = 0.75;

  assert( kZero < kLow );
  
  flag_computeIntegral = 1;
  normMuscleCurves.fiberForceLengthCurve = ...
    createFiberForceLengthCurve2021(normLengthZero,...
                                normLengthToe,...
                                fToe,...
                                kZero,...
                                kLow,...
                                kToe,...
                                curviness,...
                                flag_computeIntegral,...
                                musculotendonProperties.name,...
                                flag_useOctave);
                              
  forceLengthCurveSettings.normLengthZero = normLengthZero;
  forceLengthCurveSettings.normLengthToe  = normLengthToe;
  forceLengthCurveSettings.fToe           = fToe;
  forceLengthCurveSettings.kZero = kZero;
  forceLengthCurveSettings.kLow  = kLow;
  forceLengthCurveSettings.kToe  = kToe;
  forceLengthCurveSettings.curviness = curviness;

  flag_debug=0;
  if(flag_debug==1)
    figFpeFit =figure;
    lopt    = elasticTendonReferenceModel.musculotendon.optimalFiberLength;
    penOpt  = elasticTendonReferenceModel.musculotendon.pennationAngle;
    ltSlk   = elasticTendonReferenceModel.musculotendon.tendonSlackLength;
    
    
    lceN0 = elasticTendonReferenceModel.curves.fiberForceLengthCurve.xEnd(1,1);
    lceN1 = elasticTendonReferenceModel.curves.fiberForceLengthCurve.xEnd(1,2);
    lpV = zeros(100,1);
    fpeNATV=zeros(100,1);
    fpeNRTATV=zeros(100,1);
    for(i=1:1:100)
       n = (i-1)/99;
       nMin = 0.05;
    
       lceN_ET =lceN0 + (n*(1-nMin) + nMin)*(lceN1-lceN0);
       fpeN_ET = calcBezierYFcnXDerivative(lceN_ET, ...
           elasticTendonReferenceModel.curves.fiberForceLengthCurve,0);
    
       fiberKin = calcFixedWidthPennatedFiberKinematicsAlongTendon(lceN_ET*lopt,0,lopt,penOpt);
       alpha = fiberKin.pennationAngle;
       fpeNATV(i,1)= fpeN_ET*cos(alpha);
    
       ftN_ET = fpeN_ET*cos(alpha);
    
       ltN_ET = calcBezierYFcnXDerivative(ftN_ET, ...
                elasticTendonReferenceModel.curves.tendonForceLengthInverseCurve, 0);
       lp = (lopt * lceN_ET)*cos(alpha) + ltN_ET*ltSlk;
       lpV(i,1)=lp;
    
       lceAT_RT = lp - ltSlk;
       
       fiberKinRT = calcFixedWidthPennatedFiberKinematics(lceAT_RT,0,lopt,penOpt);
       lce_RT = fiberKinRT.fiberLength;
       alpha_RT= fiberKinRT.pennationAngle;
    
       lceN_RT = lce_RT/lopt;
    
       fpeN_RT = calcBezierYFcnXDerivative(lceN_RT, normMuscleCurves.fiberForceLengthCurve,0);
       fpeNRTATV(i,1)=fpeN_RT*cos(alpha_RT);
       
    end        
    subplot(1,2,1);
        plot(lpV,fpeNATV,'b');
        hold on;
        plot(lpV,fpeNRTATV,'r');
        box off;
        xlabel('Path Length (m)');
        ylabel('Norm. Force');
        title('Passive force AT: ET vs RT');
    subplot(1,2,2);
        plot(lpV,fpeNRTATV-fpeNATV,'m');
        box off;
        xlabel('Path Length (m)');
        ylabel('Norm. Force');
        title('Passive force AT error: ET vs RT');
    here=1;
  end
end

if(flag_passiveCurveFitted == 0 && ...
   isempty(dataPassiveForceLengthNormalized) == 0)

      flag_passiveCurveFitted=1;
      normLengthZero  = min(1.0,sarcomereProperties.normFiberLengthAtOneNormPassiveForce-0.6);
      if(isfield(sarcomere,'normFiberLengthAtZeroPassiveForce'))
        normLengthZero = sarcomereProperties.normFiberLengthAtZeroPassiveForce;
      end      
      normLengthToe   = sarcomereProperties.normFiberLengthAtOneNormPassiveForce;

      kZero           = 0;
      
      if(flag_enableNumericallyNonZeroGradients)
        kZero = smallNumericallyNonZeroNumber;
      end         
      
      kLow            = 0.2;
      kNum            = 2;
      kToe            = kNum/(normLengthToe-normLengthZero);
      curviness       = 0.75;
      %xshift          = min(dataPassiveForceLengthNormalized(:,1));
      xshift          = normLengthZero;
      xwidth          = normLengthToe-normLengthZero;
      problemScaling  = 1;
      params0         = [xshift    , xwidth, kNum].*problemScaling;
      paramsLB        = [0.8*xshift;    0.5; 1.25].*problemScaling;
      paramsUB        = [2.0       ;    2.0; 3.0].*problemScaling;
      
      fixedParams = [kLow,kZero,curviness];
    
      errFcn = @(argX)calcFittedFiberForceLengthCurveError(argX,...
                       dataPassiveForceLengthNormalized,problemScaling,...
                       fixedParams,flag_useOctave);
      
                   
      err0 = errFcn(params0);
      lsqOptions = optimoptions('lsqnonlin','Display','off',...
          'FinDiffType','central');
      [x,resnorm,residual,exitflag]  = ...
          lsqnonlin(errFcn,params0,paramsLB,paramsUB,lsqOptions);
      
      err1 = errFcn(x);
    
      fprintf('  forceLengthCurve fitted, error reduced from %1.2e - %1.2e\n',...
              norm(err0),norm(err1));
      
      xshift    = x(1)/problemScaling;
      xwidth    = x(2)/problemScaling;
      kNum      = x(3)/problemScaling;

      normLengthZero = xshift;
      normLengthToe  = xshift + xwidth;
      kToe      = kNum/(normLengthToe-normLengthZero);
      fToe      = 1;
      curviness = 0.75;
    
      assert( kZero < kLow );
      
      flag_computeIntegral = 1;
      normMuscleCurves.fiberForceLengthCurve = ...
        createFiberForceLengthCurve2021(normLengthZero,...
                                    normLengthToe,...
                                    fToe,...
                                    kZero,...
                                    kLow,...
                                    kToe,...
                                    curviness,...
                                    flag_computeIntegral,...
                                    musculotendonProperties.name,...
                                    flag_useOctave);
                                  
      forceLengthCurveSettings.normLengthZero = normLengthZero;
      forceLengthCurveSettings.normLengthToe  = normLengthToe;
      forceLengthCurveSettings.fToe           = fToe;
      forceLengthCurveSettings.kZero = kZero;
      forceLengthCurveSettings.kLow  = kLow;
      forceLengthCurveSettings.kToe  = kToe;
      forceLengthCurveSettings.curviness = curviness;

end
    


if(flag_passiveCurveFitted==0)
  flag_passiveCurveFitted=1;
  %normLengthZero = sarcomereProperties.normFiberLengthAtZeroForce; 
  normLengthZero  = min(0.928,sarcomereProperties.normFiberLengthAtOneNormPassiveForce-0.6);
  if(isfield(sarcomereProperties,'normFiberLengthAtZeroPassiveForce'))
      if(isnan(sarcomereProperties.normFiberLengthAtZeroPassiveForce)==0)
        normLengthZero = sarcomereProperties.normFiberLengthAtZeroPassiveForce;
      end
  end
  normLengthToe  = sarcomereProperties.normFiberLengthAtOneNormPassiveForce;
  fToe  = 1;
  kZero = 0;
  if(flag_enableNumericallyNonZeroGradients)
    kZero = smallNumericallyNonZeroNumber;
  end         
  kLow  = 0.2;
  if(isfield(sarcomereProperties,'normFiberStiffnessAtLowPassiveForce'))
      if(isnan(sarcomereProperties.normFiberStiffnessAtLowPassiveForce)==0)
        kLow = sarcomereProperties.normFiberStiffnessAtLowPassiveForce;
      end
  end

  kToe  = 2.1/(normLengthToe-normLengthZero);
  if(isfield(sarcomereProperties,'normFiberStiffnessAtOneNormPassiveForce'))
      if(isnan(sarcomereProperties.normFiberStiffnessAtOneNormPassiveForce)==0)
        kToe = sarcomereProperties.normFiberStiffnessAtOneNormPassiveForce;
      end
  end

  curviness = 0.7;  
  if(isfield(sarcomereProperties,'fiberForceLengthCurviness'))
      if(isnan(sarcomereProperties.fiberForceLengthCurviness)==0)
        curviness = sarcomereProperties.fiberForceLengthCurviness;
      end
  end

  flag_computeIntegral = 1;
  normMuscleCurves.fiberForceLengthCurve = ...
    createFiberForceLengthCurve2021(normLengthZero,...
                                normLengthToe,...
                                fToe,...
                                kZero,...
                                kLow,...
                                kToe,...
                                curviness,...
                                flag_computeIntegral,...
                                musculotendonProperties.name,...
                                flag_useOctave);                 
                              
  forceLengthCurveSettings.normLengthZero = normLengthZero;
  forceLengthCurveSettings.normLengthToe  = normLengthToe;
  forceLengthCurveSettings.fToe  = fToe;
  forceLengthCurveSettings.kZero = kZero;
  forceLengthCurveSettings.kLow  = kLow;
  forceLengthCurveSettings.kToe  = kToe;
  forceLengthCurveSettings.curviness = curviness;                                             
end     



fprintf('  fiberForceLengthInverseCurve created\n');
normMuscleCurves.fiberForceLengthInverseCurve = ...
      createInverseCurve(normMuscleCurves.fiberForceLengthCurve);



%%
%
%   Titin curves and extracellular matrix curves
%     :If passive force-length data exists, solve for the minimum permissable 
%      value for the ECM fraction that results in a set of passive curves for 
%      the ECM and titin that:
%
%     1. Can reproduce the passive force length curve data
%     2. With curves for the IgP and PEVK regions that are plausible 
%
%%


fprintf('  ecm & titin curves:\n');

flag_computeCurveIntegrals=0;
flag_computeIntegral=0;
  
lambdaECM = sarcomereProperties.extraCellularMatrixPassiveForceFraction; 

if(lambdaECM < sqrt(eps))
    x0=-1;
    x1= 1;
    y0= 0;
    y1= 0;
    k0= 0;
    k1= 0;
    c = 0.5;
    
    pZ0 = calcQuinticBezierCornerControlPoints(x0, y0, k0, 0, ...
                                               x1, y1, k1, 0, c);
    
    %Create the curve structure
    zeroCurve.xpts    = pZ0(:,1);
    zeroCurve.ypts    = pZ0(:,2);
    
    zeroCurve.xEnd         = [x0,x1];
    zeroCurve.yEnd         = [y0,y1];
    zeroCurve.dydxEnd      = [k0, k1];
    zeroCurve.d2ydx2End    = [0, 0];
    
    zeroCurve.integral = [];
    normMuscleCurves.forceLengthECMHalfCurve = zeroCurve;
    normMuscleCurves.forceLengthECMHalfCurve.name = ...
        sprintf('%s.%s',musculotendonProperties.name,'fiberForceLengthCurve');
else

    normMuscleCurves.forceLengthECMHalfCurve  = ...
      createFiberForceLengthCurve2021((forceLengthCurveSettings.normLengthZero)*0.5,...
                                  (forceLengthCurveSettings.normLengthToe)*0.5,...
                                  lambdaECM,...
                                  forceLengthCurveSettings.kZero*(lambdaECM*2),...
                                  forceLengthCurveSettings.kLow*(lambdaECM*2),...
                                  forceLengthCurveSettings.kToe*(lambdaECM*2),...
                                  forceLengthCurveSettings.curviness,...
                                  flag_computeCurveIntegrals,...                              
                                  musculotendonProperties.name,...
                                  flag_useOctave);  

end
normMuscleCurves.forceLengthECMHalfCurve.name = sprintf('%s.%s',...
  musculotendonProperties.name,'forceLengthECMHalfCurve');
fprintf('    forceLengthECMHalfCurve created\n');

normMuscleCurves.forceLengthECMHalfInverseCurve = ...
      createInverseCurve(normMuscleCurves.forceLengthECMHalfCurve); 
fprintf('    forceLengthECMHalfInverseCurve created\n');



%%
%Stiff spring titin curves
%  :Here the PEVK segment is its own separate elastic curve and the distal Ig
%   segment is lumped with the proximal Ig segment.
%%
flag_useElasticIgD        = 1;
flag_createTwoSidedCurves = 0;


if(useTitinModel2025==0)
  [normMuscleCurves.forceLengthProximalTitinCurve, ...
      normMuscleCurves.forceLengthProximalTitinInverseCurve,...
   normMuscleCurves.forceLengthDistalTitinCurve, ...
      normMuscleCurves.forceLengthDistalTitinInverseCurve,...
   normMuscleCurves.forceLengthIgPTitinCurve, ...
      normMuscleCurves.forceLengthIgPTitinInverseCurve,...
   normMuscleCurves.forceLengthPevkTitinCurve, ...
      normMuscleCurves.forceLengthPevkTitinInverseCurve,...
   normMuscleCurves.forceLengthIgDTitinCurve, ...
      normMuscleCurves.forceLengthIgDTitinInverseCurve] ...
            = createTitinCurves2022( normMuscleCurves.fiberForceLengthCurve,...                                   
                                     forceLengthCurveSettings,...
                                     normMuscleCurves.forceLengthECMHalfCurve,...
                                     sarcomereProperties,...
                                     musculotendonProperties.name,...
                                     useWLCTitinModel,...
                                     flag_createTwoSidedCurves,...
                                     flag_computeCurveIntegrals,...
                                     flag_useElasticIgD,...
                                     sarcomereProperties.titinModelType,...                                   
                                     flag_useOctave);

else

  [normMuscleCurves.forceLengthProximalTitinCurve, ...
      normMuscleCurves.forceLengthProximalTitinInverseCurve,...
   normMuscleCurves.forceLengthDistalTitinCurve, ...
      normMuscleCurves.forceLengthDistalTitinInverseCurve,...
   normMuscleCurves.forceLengthIgPTitinCurve, ...
      normMuscleCurves.forceLengthIgPTitinInverseCurve,...
   normMuscleCurves.forceLengthPevkTitinCurve, ...
      normMuscleCurves.forceLengthPevkTitinInverseCurve,...
   normMuscleCurves.forceLengthIgDTitinCurve, ...
      normMuscleCurves.forceLengthIgDTitinInverseCurve] ...
            = createTitinCurves2025( normMuscleCurves.fiberForceLengthCurve,...                                   
                                     forceLengthCurveSettings,...
                                     normMuscleCurves.forceLengthECMHalfCurve,...
                                     sarcomereProperties,...
                                     musculotendonProperties.name,...                            
                                     useWLCTitinModel,...
                                     flag_createTwoSidedCurves,...
                                     flag_computeCurveIntegrals,...
                                     flag_useElasticIgD,...
                                     sarcomereProperties.titinModelType,...  
                                     projectFolders,...                                  
                                     flag_useOctave);

end 

%%
%
% Tendon Force-Length Curve
%
%%
eIso            = musculotendonProperties.tendonStrainAtOneNormForce;
kIso            = 1.375/eIso;
fToe            = 2./3.;
curvinessTendon = 0.5;
computeIntegral = 1;
minimumSlope    = 0;
if(flag_enableNumericallyNonZeroGradients==1)
  minimumSlope = smallNumericallyNonZeroNumber;
end
if(eIso > 0)
    normMuscleCurves.tendonForceLengthCurve = ...
      createTendonForceLengthCurve2021( eIso, kIso, ...
                                        fToe, curvinessTendon, ...
                                        computeIntegral, ...
                                        flag_enableNumericallyNonZeroGradients,...
                                        smallNumericallyNonZeroNumber,...
                                        musculotendonProperties.name,...
                                        flag_useOctave);
    fprintf('  tendonForceLengthCurve created\n');
      
    normMuscleCurves.tendonForceLengthInverseCurve = ...
      createInverseCurve(normMuscleCurves.tendonForceLengthCurve);
    
    fprintf('  tendonForceLengthInverseCurve created\n');      
    computeIntegral = 0;
    normMuscleCurves.tendonStiffnessCurve = ...
              createTendonStiffnessCurve2021( normMuscleCurves.tendonForceLengthCurve,...
                                            curvinessTendon*curvinessTendon,...
                                            flag_enableNumericallyNonZeroGradients,...                                      
                                            flag_useOctave);
    
    
    fprintf('  tendonStiffnessCurve created\n');    
else
    normMuscleCurves.tendonForceLengthCurve=[];
    normMuscleCurves.tendonForceLengthInverseCurve = [];
    normMuscleCurves.tendonStiffnessCurve=[];
end
    




%%
%
% Compressive Force-Length Curve
%   : to prevent the CE from going below its minimum fiber length
%
%%

lceOpt      = musculotendonProperties.optimalFiberLength; 
lceATMin    = musculotendonProperties.minimumFiberLengthAlongTendon;
fiberLengthAlongTendonAtOneNormForce = lceATMin/lceOpt;

alphaOpt    = musculotendonProperties.pennationAngle;
lceOptATN   = (lceOpt*cos(alphaOpt)/lceOpt);

fiberLengthAlongTendonAtZeroNormForce = ...
    fiberLengthAlongTendonAtOneNormForce ...
    +(lceOptATN/10.0);

curviness = 0.5;

normMuscleCurves.compressiveForceLengthCurve = ...
    createCompressiveForceLengthCurve2022(...
                    fiberLengthAlongTendonAtOneNormForce,...
                    fiberLengthAlongTendonAtZeroNormForce,...
                    curviness, ...
                    musculotendonProperties.name,...
                    flag_useOctave);

  
fprintf('  compressiveForceLengthCurve created\n');


musculotendonPropertiesUpd = musculotendonProperties;
sarcomerePropertiesUpd     = sarcomereProperties;   


