function [errV,forceLengthCurveSettingsUpd] = ...
               calcErrorFiberForceLengthCurve2021(...
                    arg,...
                    expData,...
                    optVarNames,...
                    forceLengthCurveSettings)

forceLengthCurveSettingsUpd = forceLengthCurveSettings;

for i=1:1:length(optVarNames)
  forceLengthCurveSettingsUpd.(optVarNames{i}) = ...
    arg(i);
end

flag_computeIntegral  = 0;
flag_useOctave        = 0;

fiberForceLengthCurve = ...
    createFiberForceLengthCurve2021(...
      forceLengthCurveSettingsUpd.normLengthZero,...
      forceLengthCurveSettingsUpd.normLengthToe,...
      forceLengthCurveSettingsUpd.fToe,...
      forceLengthCurveSettingsUpd.kZero,...
      forceLengthCurveSettingsUpd.kLow,...
      forceLengthCurveSettingsUpd.kToe,...
      forceLengthCurveSettingsUpd.curviness,...
      flag_computeIntegral,...
      'fitting-FpeN',...
      flag_useOctave);


errV = zeros(size(expData.lceN));

for i=1:1:length(expData.lceN)
  fpeN = calcBezierYFcnXDerivative(expData.lceN(i),...
                    fiberForceLengthCurve,...
                    0);
  errV(i) = fpeN-expData.fpeN(i);
end





