function [errV,curveSample] = ...
               calcErrorTitinForceLengthCurves(...
                    arg,...
                    expData,...
                    optVarNames,...
                    forceLengthCurveSettingsInput,...
                    defaultModel,...
                    projectFolders,...
                    flag_generateCurveSample)

errV = ones(size(expData.lceN)).*nan;
curveSample = [];

% fprintf('\n%1.3e',arg(1));
% for i=2:1:length(arg)
%   fprintf('\t%1.3e',arg(i));    
% end
% fprintf('\n');

fprintf('%1.3e,');
updModel=defaultModel;
curveSample= [];
forceLengthCurveSettings = forceLengthCurveSettingsInput;

for i=1:1:length(optVarNames)
  forceLengthCurveSettings.(optVarNames{i}) = ...
    arg(i);
end

%
% Create the force-length curve
%

flag_computeIntegral  = 0;
flag_useOctave        = 0;

updModel.curves.fiberForceLengthCurve = ...
    createFiberForceLengthCurve2021(...
      forceLengthCurveSettings.normLengthZero,...
      forceLengthCurveSettings.normLengthToe,...
      forceLengthCurveSettings.fToe,...
      forceLengthCurveSettings.kZero,...
      forceLengthCurveSettings.kLow,...
      forceLengthCurveSettings.kToe,...
      forceLengthCurveSettings.curviness,...
      flag_computeIntegral,...
      'fitting-FpeN',...
      flag_useOctave);

updModel.curves.fiberForceLengthInverseCurve = ...
      createInverseCurve(updModel.curves.fiberForceLengthCurve);
%
% Create the ECM curve
%

lambdaECM = updModel.sarcomere.extraCellularMatrixPassiveForceFraction; 

if(lambdaECM < sqrt(eps))
    x0=-1;
    x1= 1;
    y0= 0;
    y1= 0;
    k0= 0;
    k1= 0;
    c = 0.5;
    
    pZ0 = calcQuinticBezierCornerControlPoints(x0, y0, k0, 0, ...
                                               x1, y1, k1, 0, c);
    
    %Create the curve structure
    zeroCurve.xpts    = pZ0(:,1);
    zeroCurve.ypts    = pZ0(:,2);
    
    zeroCurve.xEnd         = [x0,x1];
    zeroCurve.yEnd         = [y0,y1];
    zeroCurve.dydxEnd      = [k0, k1];
    zeroCurve.d2ydx2End    = [0, 0];
    
    zeroCurve.integral = [];
    forceLengthECMHalfCurve = zeroCurve;
    forceLengthECMHalfCurve.name = ...
        sprintf('%s.%s',updModel.musculotendon.name,'fiberForceLengthCurve');
else

    forceLengthECMHalfCurve  = ...
      createFiberForceLengthCurve2021((forceLengthCurveSettings.normLengthZero)*0.5,...
                                  (forceLengthCurveSettings.normLengthToe)*0.5,...
                                  lambdaECM,...
                                  forceLengthCurveSettings.kZero*(lambdaECM*2),...
                                  forceLengthCurveSettings.kLow*(lambdaECM*2),...
                                  forceLengthCurveSettings.kToe*(lambdaECM*2),...
                                  forceLengthCurveSettings.curviness,...
                                  flag_computeCurveIntegrals,...                              
                                  updModel.musculotendon.name,...
                                  flag_useOctave);  

end
updModel.curves.forceLengthECMHalfCurve.name = sprintf('%s.%s',...
  updModel.musculotendon.name,'forceLengthECMHalfCurve');
fprintf('    forceLengthECMHalfCurve created\n');

updModel.curves.forceLengthECMHalfInverseCurve = ...
      createInverseCurve(forceLengthECMHalfCurve); 
fprintf('    forceLengthECMHalfInverseCurve created\n');


%
% Create the titin-force length curves
%

  setTitinSlackLengthToZero = 0;

  if(abs(updModel.sarcomere.ZLineToT12NormLengthAtOptimalFiberLength)<1e-6)
    setTitinSlackLengthToZero = 1;
  end

                       

  [updModel.curves.forceLengthProximalTitinCurve, ...
      updModel.curves.forceLengthProximalTitinInverseCurve,...
   updModel.curves.forceLengthDistalTitinCurve, ...
      updModel.curves.forceLengthDistalTitinInverseCurve,...
   updModel.curves.forceLengthIgPTitinCurve, ...
      updModel.curves.forceLengthIgPTitinInverseCurve,...
   updModel.curves.forceLengthPevkTitinCurve, ...
      updModel.curves.forceLengthPevkTitinInverseCurve,...
   updModel.curves.forceLengthIgDTitinCurve, ...
      updModel.curves.forceLengthIgDTitinInverseCurve] ...
            = createTitinCurves2025( updModel.curves.fiberForceLengthCurve,...                                   
                                     forceLengthCurveSettings,...
                                     updModel.curves.forceLengthECMHalfCurve,...
                                     updModel.sarcomere,...
                                     updModel.musculotendon.name,... 
                                     updModel.curves.setTitinSlackLengthToZero,...
                                     updModel.curves.useWLCTitinModel,...
                                     updModel.curves.flag_createTwoSidedCurves,...
                                     updModel.curves.flag_computeCurveIntegrals,...
                                     updModel.curves.flag_useElasticIgD,...
                                     updModel.sarcomere.titinModelType,...  
                                     projectFolders,...                                  
                                     0);

%
% Sample the passive force-length relation
%


[ curveSampleECMHalf,...
  curveSampleTitin,...
  curveSampleTitinActive,...
  curveSampleIgp,...
  curveSamplePevk,...
  curveSampleIgd,...
  curveSampleProximalTitin,...
  curveSampleDistalTitin,...
  curveSampleTwoSegmentTitinActive] = ...
        sampleTitinCurves20250612(expData.lceN*0.5,updModel); 


%
% Evaluate the error
%
errV = zeros(size(expData.lceN));

for i=1:1:length(expData.lceN)
  fpeN = curveSampleTitin.y(i)+curveSampleECMHalf.y(i);
  errV(i) = fpeN-expData.fpeN(i);
end

if(flag_generateCurveSample==1)

  lceHN = [0:0.01:1]' .* (forceLengthCurveSettings.normLengthToe * 0.5);


  [ curveSampleECMHalf,...
    curveSampleTitin,...
    curveSampleTitinActive,...
    curveSampleIgp,...
    curveSamplePevk,...
    curveSampleIgd,...
    curveSampleProximalTitin,...
    curveSampleDistalTitin,...
    curveSampleTwoSegmentTitinActive] = ...
          sampleTitinCurves20250612(lceHN,updModel); 

  curveSample.x = zeros(size(lceHN));
  curveSample.y = zeros(size(lceHN));

  for i=1:1:length(lceHN)
    curveSample.x(i)=lceHN(i)*2;
    curveSample.y(i)=curveSampleECMHalf.y(i)+curveSampleTitin.y(i);
  end
  here=1;
end




