%%
% SPDX-FileCopyrightText: 2023 Matthew Millard <millard.matthew@gmail.com>
%
% SPDX-License-Identifier: MIT
%
% If you use this code in your work please cite the pre-print of this paper
% or the most recent peer-reviewed version of this paper:
%
%    Matthew Millard, David W. Franklin, Walter Herzog. 
%    A three filament mechanistic model of musculotendon force and impedance. 
%    bioRxiv 2023.03.27.534347; doi: https://doi.org/10.1101/2023.03.27.534347 
%
%%

function err = calcScalingError(arg, ...
                    createMusculoTendonFcn, ...
                    curvinessActiveForceLength,...
                    flag_enableNumericallyNonZeroGradients,...
                    smallNumericallyNonZeroNumber,...
                    flag_useOctave)

scaleOptimalFiberLength      = arg;
scaleMaximumIsometricTension = 1;%arg(2,1);




[musculotendonProperties, ...
 sarcomereProperties,...
 activeForceLengthData,...
 passiveForceLengthData] = ...
    createMusculoTendonFcn(scaleOptimalFiberLength,...
                           scaleMaximumIsometricTension);

assert(isempty(activeForceLengthData)==0);
assert(isempty(passiveForceLengthData)==0);

activeForceLengthCurve ...
    = createFiberActiveForceLengthCurve(...
          sarcomereProperties.normMyosinHalfLength*2,...
          sarcomereProperties.normMyosinBareHalfLength*2,...
          sarcomereProperties.normActinLength,...
          sarcomereProperties.normZLineLength,...
          sarcomereProperties.normSarcomereLengthZeroForce,...
          curvinessActiveForceLength, ...
          flag_enableNumericallyNonZeroGradients,...
          smallNumericallyNonZeroNumber,...
          '',...
          flag_useOctave); 
        
y = zeros(size(activeForceLengthData,1),1);

for i=1:1:size(activeForceLengthData,1)
  y(i,1) = calcBezierYFcnXDerivative( activeForceLengthData(i,1),...
                                      activeForceLengthCurve,0);
end

err = sum( (activeForceLengthData(:,2)-y(:,1)).^2 ,1).*100;
        
        
                          
                          