%%
% SPDX-FileCopyrightText: 2023 Matthew Millard <millard.matthew@gmail.com>
%
% SPDX-License-Identifier: MIT
%
%
%%

function defaultRatMuscle = createRatSkeletalMuscleModel(...
                                      setSarcomereProperties,...
                                      setMusculotendonProperties,...
                                      setCurveProperties,...
                                      specimenTemperature,...                   
                                      muscleName,...
                                      projectFolders,...
                                      flag_useOctave)



if( setCurveProperties.smallNumericallyNonZeroNumber <= 0 &&...
    setCurveProperties.flag_enableNumericallyNonZeroGradients  )
  disp('Warning: flag_enableNumericallyNonZeroGradients is set to 1 and');
  disp('         smallNumericallyNonZeroNumber <= 0');
  disp('Setting smallNumericallyNonZeroNumber to be sqrt(sqrt(eps))');
  setCurveProperties.smallNumericallyNonZeroNumber = sqrt(sqrt(eps));
end

if(isempty(setSarcomereProperties.normPevkToActinAttachmentPoint))
  setSarcomereProperties.normPevkToActinAttachmentPoint        = 0.5;

  disp('normPevkToActinAttachmentPoint empty using default:');  
  fprintf('\t%f\n',setSarcomereProperties.normPevkToActinAttachmentPoint);
end

if(isempty(setMusculotendonProperties.normFiberLengthAtOneNormPassiveForce))
  setMusculotendonProperties.normFiberLengthAtOneNormPassiveForce  = 1.696;

  disp('normFiberLengthAtOneNormPassiveForce empty using default');
  fprintf('\t%f\n',...
      setMusculotendonProperties.normFiberLengthAtOneNormPassiveForce);
end



[ratMusculotendonProperties, ...
 ratSarcomereProperties,...
 activeForceLengthDataNormalized,...
 passiveForceLengthDataNormalized] = ...
    createRatSkeletalMuscleParameters(  ...                       
        setMusculotendonProperties.scaleOptimalFiberLength,...
        setMusculotendonProperties.scaleMaximumIsometricTension,...
        setCurveProperties.activeForceLengthData,...
        setCurveProperties.passiveForceLengthData,...              
        setMusculotendonProperties.normFiberLengthAtZeroPassiveForce,...
        setMusculotendonProperties.normFiberLengthAtOneNormPassiveForce,...
        setMusculotendonProperties.normFiberStiffnessAtOneNormPassiveForce,...
        setSarcomereProperties.normPevkToActinAttachmentPoint,...
        setSarcomereProperties.normMaxActiveTitinToActinDamping,...
        setSarcomereProperties.normLengthTitinActinBondMinimum,...
        setSarcomereProperties.ecmForceFraction,...
        setSarcomereProperties.titinMolecularWeightInkD,...
        specimenTemperature,...
        setMusculotendonProperties.makeSkinnedFibrilModel,...
        setMusculotendonProperties.useElasticTendon,...
        muscleName,...
        projectFolders,...
        flag_useOctave);

ratSarcomereProperties.setSarcomereProperties.normCrossBridgeStiffness ...
                                    =setSarcomereProperties.normCrossBridgeStiffness;

ratSarcomereProperties.setSarcomereProperties.normCrossBridgeDamping ...
                                    =setSarcomereProperties.normCrossBridgeDamping;
%
% This fitting function will not function correctly if the model is fit
% to data
%
createMusculoTendonFcn = ...
 @( argScaleFiberLength,...
    argScaleFiso)createRatSkeletalMuscleParameters(...
                                argScaleFiberLength,...
                                argScaleFiso,...
                                setCurveProperties.activeForceLengthData,...
                                setCurveProperties.passiveForceLengthData,...
                                setMusculotendonProperties.normFiberLengthAtZeroPassiveForce,...
                                setMusculotendonProperties.normFiberLengthAtOneNormPassiveForce,...
                                setMusculotendonProperties.normFiberStiffnessAtOneNormPassiveForce,...
                                setSarcomereProperties.normPevkToActinAttachmentPoint,...
                                setSarcomereProperties.normMaxActiveTitinToActinDamping,...
                                setSarcomereProperties.normLengthTitinActinBondMinimum,...
                                setSarcomereProperties.ecmForceFraction,...
                                setSarcomereProperties.titinMolecularWeightInkD,...
                                specimenTemperature,...
                                setMusculotendonProperties.makeSkinnedFibrilModel,...
                                setMusculotendonProperties.useElasticTendon,...
                                muscleName,...
                                projectFolders,...
                                flag_useOctave); 
                                        



shiftLengthActiveForceLengthCurveDescendingCurve = 0;
flag_solveForOptimalFiberLengthOfBestFit = 1;
elasticTendonReferenceModel = [];

ratSarcomereProperties.normFiberStiffnessAtLowPassiveForce = ...
    setMusculotendonProperties.normFiberStiffnessAtLowPassiveForce;
ratSarcomereProperties.fiberForceLengthCurviness = ...
    setMusculotendonProperties.fiberForceLengthCurviness;


[ratNormMuscleCurvesUpd,...
ratMusculotendonPropertiesUpd,...
ratSarcomerePropertiesUpd,... 
activeForceLengthCurveAnnotationPoints,...
ratActiveForceLengthDataUpd,...
ratPassiveForceLengthDataUpd,...
ratPassiveForceLengthCurveSettings]= ...
   createFittedMuscleCurvesTRSS2017( ...
     ratMusculotendonProperties,...
     ratSarcomereProperties,...
     setSarcomereProperties.useWLCTitinModel,...      
     setCurveProperties.useCalibratedCurves,...
     setCurveProperties.useTwoSidedTitinCurves,...
     activeForceLengthDataNormalized,...
     passiveForceLengthDataNormalized,...
     shiftLengthActiveForceLengthCurveDescendingCurve,...
     setCurveProperties.useForceVelocityCurveWithSlopeDiscontinuity,...
     setCurveProperties.fitTitinToTRSS2017Data,...
     setCurveProperties.flag_enableNumericallyNonZeroGradients,...
     setCurveProperties.smallNumericallyNonZeroNumber,...
     flag_solveForOptimalFiberLengthOfBestFit,...
     createMusculoTendonFcn,...
     setMusculotendonProperties.useElasticTendon,...
     elasticTendonReferenceModel,...      
     flag_useOctave);

%ratSarcomerePropertiesUpd.normLengthTitinActinBondMinimum ...
%    = ratNormMuscleCurvesUpd.fiberForceLengthCurve.xEnd(1,1);

% Some muscles appear to have a minimum length for developing linear
% eccentric force profiles, others not. Here we set the default to 
% be the start of the passive-force-length curve and adjust as needed
%
%Tomalka A. Eccentric muscle contractions: from single muscle fibre to 
%whole muscle mechanics. Pflügers Archiv-European Journal of Physiology. 
%2023 Apr;475(4):421-35.

%ratSarcomerePropertiesDefault.normLengthTitinActinBondMinimum = ...
%  ratNormMuscleCurvesDefault.fiberForceLengthCurve.xEnd(1,1);

defaultRatMuscle = struct('musculotendon',...
                           ratMusculotendonPropertiesUpd,...
                           'sarcomere',...
                           ratSarcomerePropertiesUpd,...
                           'falData',...
                           ratActiveForceLengthDataUpd,...
                           'fpeData',...
                           ratPassiveForceLengthDataUpd,...
                           'curves',...
                           ratNormMuscleCurvesUpd,...
                           'fitting',...
                           []);
              


   
