%%
% SPDX-FileCopyrightText: 2023 Matthew Millard <millard.matthew@gmail.com>
%
% SPDX-License-Identifier: MIT
%
%
%%

function defaultRatSoleusFibril = createRatSoleusFibrilModel(...
                                      normCrossBridgeStiffness,...
                                      normCrossBridgeDamping,...
                                      normPevkToActinAttachmentPoint,...
                                      normMaxActiveTitinToActinDamping,...
                                      normFiberLengthAtOneNormPassiveForce,...
                                      ecmForceFraction,...
                                      titinMolecularWeightInkD,...
                                      useWLCTitinModel,...                                      
                                      useCalibratedCurves,...
                                      useTwoSidedTitinCurves,...
                                      smallNumericallyNonZeroNumber,...
                                      flag_enableNumericallyNonZeroGradients,...
                                      scaleOptimalFiberLength,...
                                      scaleMaximumIsometricTension,...
                                      projectFolders,...
                                      flag_useOctave)

fileActiveForceLength_ZHGL1995 = ...
    fullfile(projectFolders.experiments_ZHGL1995,...
    'data','ZuurbierHeslingaGrootLaarse1995.csv'     );

activeForceLengthData_ZHGL1995 =...
        loadDigitizedData( ...
        fileActiveForceLength_ZHGL1995,...
        'Length (um)','Norm. Force (f/fo)',...
        {'ZHGL1995 Exp: $$\mu$$',...
         'ZHGL1995 Exp: $$\mu+\sigma$$',...
         'ZHGL1995 Exp: $$\mu-\sigma$$',...
         'Model (GM)','Model (EDL)'},...
         'Rat fibril $$f^{L}$$');

fileActiveForceLength_SW1982 = ...
    fullfile(projectFolders.experiments_SW1982,...
    'data','StephensonWilliams1982_Fig7_fl.csv'     );

filePassiveForceLength_SW1982 = ...
    fullfile(projectFolders.experiments_SW1982,...
    'data','StephensonWilliams1982_Fig7_fpe.csv'     );


activeForceLengthData_SW1982 =...
        loadDigitizedData(fileActiveForceLength_SW1982,...
                        'Length (um)','Norm. Force (f/fo)',...
                        {'EDL (low temp)','EDL (norm. temp)',...
                         'SOL (low temp)','SOL (norm. temp)'},...
                         'Rat fibril $$f^{L}$$');

passiveForceLengthData_SW1982 = ...
    loadDigitizedData(filePassiveForceLength_SW1982,...
                        'Length (um)','Norm. Force (f/fo)',...
                        {'EDL and SOL'},...
                        'Rat fibril $$f^{PE}$$');





if( smallNumericallyNonZeroNumber <= 0 &&...
    flag_enableNumericallyNonZeroGradients  )
  disp('Warning: flag_enableNumericallyNonZeroGradients is set to 1 and');
  disp('         smallNumericallyNonZeroNumber <= 0');
  disp('Setting smallNumericallyNonZeroNumber to be sqrt(sqrt(eps))');
  smallNumericallyNonZeroNumber = sqrt(sqrt(eps));
end

if(isempty(normPevkToActinAttachmentPoint))
  normPevkToActinAttachmentPoint        = 0.5;

  disp('normPevkToActinAttachmentPoint empty using default:');  
  fprintf('\t%f\n',normPevkToActinAttachmentPoint);
end

if(isempty(normFiberLengthAtOneNormPassiveForce))
  normFiberLengthAtOneNormPassiveForce        = 1.696;

  disp('normFiberLengthAtOneNormPassiveForce empty using default');
  fprintf('\t%f\n',normFiberLengthAtOneNormPassiveForce);
end



[ratSoleusFibrilMusculotendonProperties, ...
 ratSoleusFibrilSarcomereProperties] = ...
    createRatSoleusFibrilParameters(  ...
                        scaleOptimalFiberLength,...
                        scaleMaximumIsometricTension,...
                        normFiberLengthAtOneNormPassiveForce,...
                        normPevkToActinAttachmentPoint,...
                        normMaxActiveTitinToActinDamping,...
                        ecmForceFraction,...
                        titinMolecularWeightInkD,...
                        projectFolders,...
                        flag_useOctave);

%ratSoleusFibrilSarcomereProperties.normCrossBridgeStiffness ...
%                                    =normCrossBridgeStiffness;

%ratSoleusFibrilSarcomereProperties.normCrossBridgeDamping ...
%                                    =normCrossBridgeDamping;

%createMusculoTendonFcn = ...
%  @(argScaleFiberLength,argScaleFiso)createRatSoleusFibrilParameters(...
%                                        argScaleFiberLength,...
%                                        argScaleFiso,...
%                                        normFiberLengthAtOneNormPassiveForce,...
%                                        normPevkToActinAttachmentPoint,...
%                                        normMaxActiveTitinToActinDamping,...
%                                        ecmForceFraction,...
%                                        projectFolders,...
%                                        flag_useOctave); 
                                        


%We have no data to fit to, and so these options cannot be used
%flag_solveForOptimalFiberLengthOfBestFit         = 0; 
%shiftLengthActiveForceLengthCurveDescendingCurve = 0.;

%useElasticTendon = 0;
%elasticTendonReferenceModel = [];

%[ratSoleusFibrilNormMuscleCurvesDefault,...
% ratSoleusFibrilMusculotendonPropertiesDefault,...
% ratSoleusFibrilSarcomerePropertiesDefault,... 
% activeForceLengthCurveAnnotationPoints,...
% ratSoleusFibrilActiveForceLengthDataDefault,...
% ratSoleusFibrilPassiveForceLengthDataDefault,...
% ratSoleusFibrilPassiveForceLengthCurveSettings]= ...
%    createFittedMuscleCurves( ...
%      ratSoleusFibrilMusculotendonProperties,...
%      ratSoleusFibrilSarcomereProperties,...
%      useWLCTitinModel,...      
%      useCalibratedCurves,...
%      useTwoSidedTitinCurves,...
%      ratSoleusFibrilActiveForceLengthData,...
%      ratSoleusFibrilPassiveForceLengthData,...
%      shiftLengthActiveForceLengthCurveDescendingCurve,...
%      flag_enableNumericallyNonZeroGradients,...
%      smallNumericallyNonZeroNumber,...
%      flag_solveForOptimalFiberLengthOfBestFit,...
%      createMusculoTendonFcn,...
%      useElasticTendon,...
%      elasticTendonReferenceModel,...      
%      flag_useOctave);


% Some muscles appear to have a minimum length for developing linear
% eccentric force profiles, others not. Here we set the default to 
% be the start of the passive-force-length curve and adjust as needed
%
%Tomalka A. Eccentric muscle contractions: from single muscle fibre to 
%whole muscle mechanics. Pflügers Archiv-European Journal of Physiology. 
%2023 Apr;475(4):421-35.

%ratSoleusFibrilSarcomerePropertiesDefault.normLengthTitinActinBondMinimum = ...
%  ratSoleusFibrilNormMuscleCurvesDefault.fiberForceLengthCurve.xEnd(1,1);


%defaultRatSoleusFibril = struct('musculotendon',...
%                            ratSoleusFibrilMusculotendonPropertiesDefault,...
%                            'sarcomere',...
%                            ratSoleusFibrilSarcomerePropertiesDefault,...
%                            'falData',...
%                            ratSoleusFibrilActiveForceLengthDataDefault,...
%                            'fpeData',...
%                            ratSoleusFibrilPassiveForceLengthDataDefault,...
%                            'curves',...
%                            ratSoleusFibrilNormMuscleCurvesDefault,...
%                            'fitting',...
%                            []);
              


   
