%%
% SPDX-FileCopyrightText: 2023 Matthew Millard <millard.matthew@gmail.com>
%
% SPDX-License-Identifier: MIT
%
%
%%

function defaultRatSoleusFibril = createRatSoleusModel(...
                                      normCrossBridgeStiffness,...
                                      normCrossBridgeDamping,...
                                      normPevkToActinAttachmentPoint,...
                                      normMaxActiveTitinToActinDamping,...
                                      normFiberLengthAtZeroPassiveForce,...
                                      normFiberLengthAtOneNormPassiveForce,...
                                      normFiberStiffnessAtOneNormPassiveForce,...
                                      ecmForceFraction,...
                                      titinMolecularWeightInkD,...
                                      useWLCTitinModel,...                                      
                                      useCalibratedCurves,...
                                      useTwoSidedTitinCurves,...
                                      smallNumericallyNonZeroNumber,...
                                      flag_enableNumericallyNonZeroGradients,...
                                      scaleOptimalFiberLength,...
                                      scaleMaximumIsometricTension,...
                                      specimenTemperature,...
                                      useSharpForceVelocityCurve,...
                                      useModifiedPassiveForceLengthCurve,...
                                      useElasticTendon,...
                                      makeFibrilModel,...
                                      activeForceLengthData,...
                                      passiveForceLengthData,...
                                      mapToEDLModel,...
                                      projectFolders,...
                                      flag_useOctave)



if( smallNumericallyNonZeroNumber <= 0 &&...
    flag_enableNumericallyNonZeroGradients  )
  disp('Warning: flag_enableNumericallyNonZeroGradients is set to 1 and');
  disp('         smallNumericallyNonZeroNumber <= 0');
  disp('Setting smallNumericallyNonZeroNumber to be sqrt(sqrt(eps))');
  smallNumericallyNonZeroNumber = sqrt(sqrt(eps));
end

if(isempty(normPevkToActinAttachmentPoint))
  normPevkToActinAttachmentPoint        = 0.5;

  disp('normPevkToActinAttachmentPoint empty using default:');  
  fprintf('\t%f\n',normPevkToActinAttachmentPoint);
end

if(isempty(normFiberLengthAtOneNormPassiveForce))
  normFiberLengthAtOneNormPassiveForce        = 1.696;

  disp('normFiberLengthAtOneNormPassiveForce empty using default');
  fprintf('\t%f\n',normFiberLengthAtOneNormPassiveForce);
end



[ratSoleusFibrilMusculotendonProperties, ...
 ratSoleusFibrilSarcomereProperties,...
 activeForceLengthDataNormalized,...
 passiveForceLengthDataNormalized] = ...
    createRatSoleusParameters(  ...                       
                        scaleOptimalFiberLength,...
                        scaleMaximumIsometricTension,...
                        activeForceLengthData,...
                        passiveForceLengthData,...              
                        normFiberLengthAtZeroPassiveForce,...
                        normFiberLengthAtOneNormPassiveForce,...
                        normFiberStiffnessAtOneNormPassiveForce,...
                        normPevkToActinAttachmentPoint,...
                        normMaxActiveTitinToActinDamping,...
                        ecmForceFraction,...
                        titinMolecularWeightInkD,...
                        specimenTemperature,...
                        makeFibrilModel,...
                        useElasticTendon,...
                        mapToEDLModel,...
                        projectFolders,...
                        flag_useOctave);

ratSoleusFibrilSarcomereProperties.normCrossBridgeStiffness ...
                                    =normCrossBridgeStiffness;

ratSoleusFibrilSarcomereProperties.normCrossBridgeDamping ...
                                    =normCrossBridgeDamping;
%
% This fitting function will not function correctly if the model is fit
% to data
%
createMusculoTendonFcn = ...
 @( argScaleFiberLength,...
    argScaleFiso)createRatSoleusParameters(...
                                argScaleFiberLength,...
                                argScaleFiso,...
                                activeForceLengthData,...
                                passiveForceLengthData,...
                                normFiberLengthAtZeroPassiveForce,...
                                normFiberLengthAtOneNormPassiveForce,...
                                normFiberStiffnessAtOneNormPassiveForce,...
                                normPevkToActinAttachmentPoint,...
                                normMaxActiveTitinToActinDamping,...
                                ecmForceFraction,...
                                titinMolecularWeightInkD,...
                                specimenTemperature,...
                                makeFibrilModel,...
                                useElasticTendon,...
                                mapToEDLModel,...
                                projectFolders,...
                                flag_useOctave); 
                                        
%flag_solveForOptimalFiberLengthOfBestFit         = 0; 
%shiftLengthActiveForceLengthCurveDescendingCurve = 0.;

%useElasticTendon = 0;
%elasticTendonReferenceModel = [];

ratSoleusFibrilMusculotendonProperties.useSharpForceVelocityCurve=...
                                       useSharpForceVelocityCurve;
ratSoleusFibrilMusculotendonProperties.useModifiedPassiveForceLengthCurve=...
                                       useModifiedPassiveForceLengthCurve;

shiftLengthActiveForceLengthCurveDescendingCurve = 0;
flag_solveForOptimalFiberLengthOfBestFit = 1;
elasticTendonReferenceModel = [];

[ratSoleusFibrilNormMuscleCurvesUpd,...
ratSoleusFibrilMusculotendonPropertiesUpd,...
ratSoleusFibrilSarcomerePropertiesUpd,... 
activeForceLengthCurveAnnotationPoints,...
ratSoleusFibrilActiveForceLengthDataUpd,...
ratSoleusFibrilPassiveForceLengthDataUpd,...
ratSoleusFibrilPassiveForceLengthCurveSettings]= ...
   createFittedMuscleCurves( ...
     ratSoleusFibrilMusculotendonProperties,...
     ratSoleusFibrilSarcomereProperties,...
     useWLCTitinModel,...      
     useCalibratedCurves,...
     useTwoSidedTitinCurves,...
     activeForceLengthDataNormalized,...
     passiveForceLengthDataNormalized,...
     shiftLengthActiveForceLengthCurveDescendingCurve,...
     flag_enableNumericallyNonZeroGradients,...
     smallNumericallyNonZeroNumber,...
     flag_solveForOptimalFiberLengthOfBestFit,...
     createMusculoTendonFcn,...
     useElasticTendon,...
     elasticTendonReferenceModel,...      
     flag_useOctave);

ratSoleusFibrilSarcomerePropertiesUpd.normLengthTitinActinBondMinimum ...
    = ratSoleusFibrilNormMuscleCurvesUpd.fiberForceLengthCurve.xEnd(1,1);

% Some muscles appear to have a minimum length for developing linear
% eccentric force profiles, others not. Here we set the default to 
% be the start of the passive-force-length curve and adjust as needed
%
%Tomalka A. Eccentric muscle contractions: from single muscle fibre to 
%whole muscle mechanics. Pflügers Archiv-European Journal of Physiology. 
%2023 Apr;475(4):421-35.

%ratSoleusFibrilSarcomerePropertiesDefault.normLengthTitinActinBondMinimum = ...
%  ratSoleusFibrilNormMuscleCurvesDefault.fiberForceLengthCurve.xEnd(1,1);

defaultRatSoleusFibril = struct('musculotendon',...
                           ratSoleusFibrilMusculotendonPropertiesUpd,...
                           'sarcomere',...
                           ratSoleusFibrilSarcomerePropertiesUpd,...
                           'falData',...
                           ratSoleusFibrilActiveForceLengthDataUpd,...
                           'fpeData',...
                           ratSoleusFibrilPassiveForceLengthDataUpd,...
                           'curves',...
                           ratSoleusFibrilNormMuscleCurvesUpd,...
                           'fitting',...
                           []);
              


   
