%%
% SPDX-FileCopyrightText: 2023 Matthew Millard <millard.matthew@gmail.com>
%
% SPDX-License-Identifier: MIT
%
%
%%

function [defaultRatMuscle,...
          activeForceLengthCurveAnnotationPoints]= ...
            createRatSkeletalMuscleModel(...
                                      setSarcomereProperties,...
                                      setMusculotendonProperties,...
                                      setCurveProperties,...
                                      setForceLengthCurveSettings,...
                                      specimenTemperature,...
                                      experimentName,...
                                      muscleName,...
                                      projectFolders,...
                                      flag_useOctave)



if( setCurveProperties.smallNumericallyNonZeroNumber <= 0 &&...
    setCurveProperties.flag_enableNumericallyNonZeroGradients  )
  disp('Warning: flag_enableNumericallyNonZeroGradients is set to 1 and');
  disp('         smallNumericallyNonZeroNumber <= 0');
  disp('Setting smallNumericallyNonZeroNumber to be sqrt(sqrt(eps))');
  setCurveProperties.smallNumericallyNonZeroNumber = sqrt(sqrt(eps));
end

if(isempty(setSarcomereProperties.normPevkToActinAttachmentPoint))
  setSarcomereProperties.normPevkToActinAttachmentPoint        = 0.5;

  disp('normPevkToActinAttachmentPoint empty using default:');  
  fprintf('\t%f\n',setSarcomereProperties.normPevkToActinAttachmentPoint);
end




ratSolId = 7;

[ activeForceLengthCurveAnnotationPoints, ...
  halfMyosinBareLength, ...
  halfMyosinLength,...
  zLineLength,...
  actinLength] = ...
    calcSarcomereFilamentLengthsFromActiveForceLengthKeyPoints(ratSolId);

[ratMusculotendonProperties, ...
 ratSarcomereProperties,...
 activeForceLengthDataNormalized,...
 passiveForceLengthDataNormalized] = ...
    createRatSkeletalMuscleParameters(  ...                       
        setMusculotendonProperties.scaleOptimalFiberLength,...
        setMusculotendonProperties.scaleMaximumIsometricTension,...
        setCurveProperties.activeForceLengthData,...
        setCurveProperties.passiveForceLengthData,...              
        setSarcomereProperties.normFiberLengthAtZeroPassiveForce,...
        setSarcomereProperties.normFiberLengthAtOneNormPassiveForce,...
        setSarcomereProperties.normFiberStiffnessAtOneNormPassiveForce,...
        setSarcomereProperties.normFiberForceAtPassiveToe,...
        setSarcomereProperties.normPevkToActinAttachmentPoint,...
        setSarcomereProperties.normMaxActiveTitinToActinDamping,...
        setSarcomereProperties.normLengthTitinActinBondMinimum,...
        setSarcomereProperties.ecmForceFraction,...
        setSarcomereProperties.titinMolecularWeightInkD,...
        setCurveProperties.forceVelocityMultiplierAtLowEccentricFiberVelocity,...
        setCurveProperties.forceVelocityMultiplierAtMaximumEccentricFiberVelocity,... 
        specimenTemperature,...
        setMusculotendonProperties.makeSkinnedFibrilModel,...
        setSarcomereProperties.setT12ToZLineSegmentToZero,...  
        setMusculotendonProperties.useElasticTendon,...
        experimentName,...
        muscleName,...
        projectFolders,...
        flag_useOctave);

ratSarcomereProperties.setSarcomereProperties.normCrossBridgeStiffness ...
                                    =setSarcomereProperties.normCrossBridgeStiffness;

ratSarcomereProperties.setSarcomereProperties.normCrossBridgeDamping ...
                                    =setSarcomereProperties.normCrossBridgeDamping;
%
% This fitting function will not function correctly if the model is fit
% to data
%
createMusculoTendonFcn = ...
 @( argScaleFiberLength,...
    argScaleFiso)createRatSkeletalMuscleParameters(...
        argScaleFiberLength,...
        argScaleFiso,...
        setCurveProperties.activeForceLengthData,...
        setCurveProperties.passiveForceLengthData,...
        setSarcomereProperties.normFiberLengthAtZeroPassiveForce,...
        setSarcomereProperties.normFiberLengthAtOneNormPassiveForce,...
        setSarcomereProperties.normFiberStiffnessAtOneNormPassiveForce,...
        setSarcomereProperties.normFiberForceAtPassiveToe,...
        setSarcomereProperties.normPevkToActinAttachmentPoint,...
        setSarcomereProperties.normMaxActiveTitinToActinDamping,...
        setSarcomereProperties.normLengthTitinActinBondMinimum,...
        setSarcomereProperties.ecmForceFraction,...
        setSarcomereProperties.titinMolecularWeightInkD,...
        setCurveProperties.forceVelocityMultiplierAtLowEccentricFiberVelocity,...
        setCurveProperties.forceVelocityMultiplierAtMaximumEccentricFiberVelocity,...                                 
        specimenTemperature,...
        setMusculotendonProperties.makeSkinnedFibrilModel,...
        setSarcomereProperties.setT12ToZLineSegmentToZero,...
        setMusculotendonProperties.useElasticTendon,...
        experimentName,...
        muscleName,...
        projectFolders,...
        flag_useOctave); 
                                        




flag_solveForOptimalFiberLengthOfBestFit = 1;
elasticTendonReferenceModel = [];

sarcomereFields ={'normFiberStiffnessAtLowPassiveForce',...
                  'fiberForceLengthCurviness';...
                  'normCrossBridgeStiffness',...
                  'normCrossBridgeDamping'};

for idx=1:1:length(sarcomereFields)
    if(isfield(setSarcomereProperties,sarcomereFields{idx}))
        ratSarcomereProperties.(sarcomereFields{idx}) = ...
            setSarcomereProperties.(sarcomereFields{idx});
    end
end




[ratNormMuscleCurvesUpd,...
ratMusculotendonPropertiesUpd,...
ratSarcomerePropertiesUpd,... 
activeForceLengthCurveAnnotationPoints,...
ratActiveForceLengthDataUpd,...
ratPassiveForceLengthDataUpd,...
ratPassiveForceLengthCurveSettings]= ...
   createFittedMuscleCurvesTRSS2017( ...
     ratMusculotendonProperties,...
     ratSarcomereProperties,...
     setSarcomereProperties,...
     setCurveProperties,...
     setForceLengthCurveSettings,...
     activeForceLengthDataNormalized,...
     passiveForceLengthDataNormalized,...
     flag_solveForOptimalFiberLengthOfBestFit,...
     createMusculoTendonFcn,...
     setMusculotendonProperties.useElasticTendon,...
     elasticTendonReferenceModel,...    
     projectFolders,...
     flag_useOctave);

%ratSarcomerePropertiesUpd.normLengthTitinActinBondMinimum ...
%    = ratNormMuscleCurvesUpd.fiberForceLengthCurve.xEnd(1,1);

% Some muscles appear to have a minimum length for developing linear
% eccentric force profiles, others not. Here we set the default to 
% be the start of the passive-force-length curve and adjust as needed
%
%Tomalka A. Eccentric muscle contractions: from single muscle fibre to 
%whole muscle mechanics. Pflügers Archiv-European Journal of Physiology. 
%2023 Apr;475(4):421-35.

%ratSarcomerePropertiesDefault.normLengthTitinActinBondMinimum = ...
%  ratNormMuscleCurvesDefault.fiberForceLengthCurve.xEnd(1,1);

defaultRatMuscle = struct('musculotendon',...
                           ratMusculotendonPropertiesUpd,...
                           'sarcomere',...
                           ratSarcomerePropertiesUpd,...
                           'falData',...
                           ratActiveForceLengthDataUpd,...
                           'fpeData',...
                           ratPassiveForceLengthDataUpd,...
                           'curves',...
                           ratNormMuscleCurvesUpd,...
                           'fitting',...
                           []);
              



   


