function fittedFelineSoleus = fitFelineSoleusPevkActinBondLocation( ...
                                defaultFelineSoleus,...
                                flag_useElasticTendon,...
                                felineSoleusPassiveForceLengthCurveSettings)

%The parameters updated are the 
%  :normPevkToActinAttachmentPoint (default of 0.5)
%  :normMaxActiveTitinToActinDamping (default of 20)
%
%The hand-tuned default values are quite good, but fitting is required to
%minimize the error. Since the process of both force development and 
%relaxation are nonlinear, there is not an elegant and fast way to find 
%these parameters without simulating the model directly. 

figureNumber       = 7;
subFigureNumber    = 2;
trialNumber        = 3;  

expConfigHerzogLeonard2002 =...
 getHerzogLeonard2002Configuration( figureNumber,...
                                    subFigureNumber, ...
                                    trialNumber);

dataFolder = 'experiments/HerzogLeonard2002/fitting/';



fittedFelineSoleus=defaultFelineSoleus;

if(defaultFelineSoleus.musculotendon.titinModelType==1)
    fittedFelineSoleus.curves.useTwoSidedTitinCurves=0;
end
fittedFelineSoleus.curves.useCalibratedCurves = 1;

    
[sarcomerePropertiesUpd,...
 normMuscleCurvesUpd] = ...
    updateActiveTitinParameters(defaultFelineSoleus.musculotendon, ...
                             defaultFelineSoleus.sarcomere,...
                             defaultFelineSoleus.curves,...
                             felineSoleusPassiveForceLengthCurveSettings,...
                             expConfigHerzogLeonard2002,...
                             flag_useElasticTendon,...
                             dataFolder,...
                             flag_fitActiveTitinProperties,...
                             flag_useOctave);

fittedFelineSoleus.sarcomere=sarcomerePropertiesUpd;
fittedFelineSoleus.curves=normMuscleCurvesUpd;
