function [musculotendonProperties] = getHumanSoleusMusculotendonProperties(...
                          maximumNormalizedFiberVelocity,...
                          forceVelocityMultiplierAtHalfMaximumFiberVelocity,...
                          tendonStrainAtOneNormForce,...
                          scaleOptimalFiberLength,...                                          
                          fisoScale,...
                          normPlateauOffset,...
                          useElasticTendon,...
                          flag_useOctave)                        



%Maganaris CN. Force-length characteristics of the in vivo human gastrocnemius 
%muscle. Clinical Anatomy 2003;16(3):215–23.
lceOpt   = ((37.9)/1000)*scaleOptimalFiberLength;
alphaOpt = 32.5*(pi/180); 
fiso     = 894.7;


%Arnold EM, Ward SR, Lieber RL, Delp SL. A model of the lower limb for analysis 
%of human movement. Ann Biomed Eng 2010;38(2):269–79.
ltSlk = 0.401; %Includes both the tendon and the apneurosis

%Set the elasticity of the tendon as desired
etIso = tendonStrainAtOneNormForce;
normTendonLength = 1+etIso;
if(useElasticTendon==0)
  etIso = 0;
  normTendonLength = 1;
end


minimumFiberLengthAlongTendon = sqrt(eps);

lcePerp    = lceOpt*sin(alphaOpt);
lceAT      = minimumFiberLengthAlongTendon;

alphaMax        = atan2(lcePerp, ...
                       lceAT);
minimumFiberLength = sqrt(lcePerp*lcePerp + lceAT*lceAT);

dlceMaxN=maximumNormalizedFiberVelocity;

musculotendonProperties = struct(...
        'name'                              , 'Human Soleus',  ... 
        'abbr'                              , 'hSol',     ...
        'fiso'                              , fiso,         ...  
        'optimalFiberLength'                , lceOpt,       ... 
        'pennationAngle'                    , alphaOpt,     ... 
        'pennationAngleAtMinimumFiberLength', alphaMax,...
        'tendonSlackLength'                 , ltSlk,        ...  
        'tendonStrainAtOneNormForce'        , etIso,        ...
        'normTendonDampingLinear'           , 0.0565,          ...
        'normTendonDampingConstant'         , 0.0,           ...
        'normNumericalDamping'              , 1e-4,         ...
        'minimumFiberLength'                , minimumFiberLength,    ...
        'minimumFiberLengthAlongTendon'     , minimumFiberLengthAlongTendon, ...
        'normPassiveForceLengthCurveStiffnessAtSlack', 0.001,...
        'maximumNormalizedFiberVelocity',     maximumNormalizedFiberVelocity,...
        'forceVelocityMultiplierAtHalfMaximumFiberVelocity',...
          forceVelocityMultiplierAtHalfMaximumFiberVelocity,...
        'forceVelocityMultiplierAtLowEccentricFiberVelocity',...
        1.30,... %1.15
        'forceVelocityMultiplierAtMaximumEccentricFiberVelocity',...
        1.45,... %1.30
        'appliedFiberLengthScaling', scaleOptimalFiberLength,...
        'appliedMaxIsometricForceScaling', fisoScale);





