function [lineZToPevkP, lineZToPevkD] = ...
    scaleTitinElongationFunction(optimalSarcomereLength,    ...
                numDomainsIgP, numResiduesPevk, numDomainsIgD, ...
            optimalSarcomereLengthRef, ...
                numDomainsIgPRef, numResiduesPevkRef, numDomainsIgDRef,...
            lineZToPevkPRef, lineZToPevkDRef)

 %Amount of PEVK stretch will vary with ratio of PEVK to Ig
 %   ( numResiduesPevk/(numDomainsIgP + numDomainsIgD) )
 % / ( numResiduesPevkRef/(numDomainsIgPRef+ numDomainsIgDRef) )

 %Amount of IgP and IgD stretch will vary with
 % (numDomainsIgP/numDomainsIgD) / (numDomainsIgPRef/numDomainsIgDRef)
