%%
% SPDX-FileCopyrightText: 2023 Matthew Millard <millard.matthew@gmail.com>
%
% SPDX-License-Identifier: MIT
%
%
%%

function figPub = plotRatFibrilTRSS2017(...
                    figPub,...
                    ratFibrilModelsDefault,...
                    ratFibrilModelsFitted,...
                    fitInfo,...
                    benchRecordFitted,...
                    expTRSS2017,...
                    expTRSS2017Raw,...
                    simConfig,...
                    fittingConfig,...
                    plotConfig,...
                    pubPlotOptions)


lineWidthSim = 1.0;
lineWidthExp = 0.25;
lineWidthEst = 0.75;

addLegends = 0;
addErrorText=0;

subplotIds = {'A.','B.'};
if(simConfig.fitToIndividualTrials==1)
    subplotIds = {'C.','D.'};
end


%
% Plot the force-length relation
%


expfl.lce = [];
expfl.fN   = []; 

mdlfl.lce = [];
mdlfl.fN   = [];

assert(ratFibrilModelsDefault(1).curves.useCalibratedCurves==1,...
       'Error: the calibrated curves should be used');

curveFalN = ratFibrilModelsDefault(1).curves.activeForceLengthCurve; 
lceOptMdl = ratFibrilModelsDefault(1).musculotendon.optimalFiberLength;    

for idxTrial = simConfig.trials
    lce  = expTRSS2017.activeLengtheningData(idxTrial).x(1,1);
    fN   = expTRSS2017.activeLengtheningData(idxTrial).y(1,1);

    expfl.lce  = [expfl.lce;lce];
    expfl.fN    = [expfl.fN;fN];   

    fNMdl = calcBezierYFcnXDerivative(lce./lceOptMdl,curveFalN,0);
    mdlfl.lce  = [mdlfl.lce;lce];
    mdlfl.fN    = [mdlfl.fN;fNMdl];
            
end    

%
% fal-fitting
%
subplot('Position',reshape(plotConfig.subPlotPanel(1,1,:),1,4));
subplotPosition = reshape(plotConfig.subPlotPanel(1,1,:),1,4);

    curveFitted = ratFibrilModelsFitted(1).curves.activeForceLengthCurve;    
    curveOrig = ratFibrilModelsDefault(1).curves.activeForceLengthCurve;

    sampleFlNOrig=calcBezierYFcnXCurveSampleVector(...
                    curveOrig,100,curveOrig.xEnd);
    
    sampleFlNFitted=calcBezierYFcnXCurveSampleVector(...
                    curveFitted,100,curveFitted.xEnd);

    plot(sampleFlNOrig.x,sampleFlNOrig.y,'-',...
         'Color',[1,1,1].*0.75,'DisplayName','$$f^L(\ell^M)$$');
    hold on;
    plot(sampleFlNFitted.x,sampleFlNFitted.y,'-',...
         'Color',[1,1,1].*0.75,'DisplayName','$$f^L(\ell^M) (fitted)$$');
    hold on;

    for idx=simConfig.trials        
        plot(expfl.lce(idx)./lceOptMdl,...
             expfl.fN(idx),...
             '+','Color',[0,0,0],...
             'MarkerFaceColor',plotConfig.lineColors.exp(idx,:),...
             'DisplayName',...
             expTRSS2017.activeLengtheningData(idx).seriesName);
        hold on;
    end
    xlabel('Norm. Length ($$\ell/\ell_o^M$$)');
    ylabel(expTRSS2017.activeLengtheningData(3).yName);
    title('Force-Length Relation Fitting');  
    xlim([pubPlotOptions.lceNMin,pubPlotOptions.lceNMax]);
    box off;
    hold on;   

%
% fv-fitting
%        
subplot('Position',reshape(plotConfig.subPlotPanel(1,2,:),1,4));
subplotPosition = reshape(plotConfig.subPlotPanel(1,2,:),1,4);

    plot(sampleFlNFitted.x,sampleFlNFitted.y,'-',...
         'Color',[1,1,1].*0.75,'DisplayName','$$f^L(\ell^M)$$');
    hold on;        

    curveFvN = ratFibrilModelsDefault(1).curves.fiberForceVelocityCurve;
    curveFvNFitted = ratFibrilModelsFitted(1).curves.fiberForceVelocityCurve;

    fvN = calcBezierYFcnXDerivative(0.11,curveFvN,0);
    fvNFitted = calcBezierYFcnXDerivative(0.11,curveFvNFitted,0);
    
    plot(sampleFlNFitted.x,sampleFlNFitted.y.*fvN,'-',...
         'Color',[1,1,1].*0.75,'DisplayName','$$f^L(\ell^M)f^V(v^M)$$');
    hold on;  
    plot(sampleFlNFitted.x,sampleFlNFitted.y.*fvNFitted,'-',...
         'Color',[1,1,1].*0.75,'DisplayName','$$f^L(\ell^M)f^V(v^M)$$ (fitted)');
    hold on;  

    for idx=simConfig.trials
        hdlVis='off';
        %if(idx==1)
        %    hdlVis = 'on';
        %end

        plot(expTRSS2017.activeLengtheningData(idx).x./lceOptMdl,...
             expTRSS2017.activeLengtheningData(idx).y,...
             '-','Color',plotConfig.lineColors.exp(idx,:),...
             'DisplayName','$$f^{EXP}$$ TRSS2017',...
             'HandleVisibility',hdlVis);
        hold on; 
        idxKey = expTRSS2017.activeLengtheningData(idx).keyIndices(...
                    fittingConfig.idxFvKey);
        plot(expTRSS2017.activeLengtheningData(idx).x(idxKey)./lceOptMdl,...
             expTRSS2017.activeLengtheningData(idx).y(idxKey),...
             'x','Color',[0,0,0],...
             'MarkerSize',2,...
             'HandleVisibility','off');
        hold on; 
    end

    xlabel('Norm. Length ($$\ell/\ell_o^M$$)');
    ylabel(expTRSS2017.activeLengtheningData(3).yName);
    title('Force-Velocity Curve Fitting');  
    xlim([pubPlotOptions.lceNMin,pubPlotOptions.lceNMax]);
    box off;
    hold on;           

%
% Experimental overview plot
%
subplot('Position',reshape(plotConfig.subPlotPanel(2,1,:),1,4));
subplotPosition = reshape(plotConfig.subPlotPanel(2,1,:),1,4);

%
% Experimental analysis plot
%
vN = benchRecordFitted.normFiberVelocity(end,1);
fvN = calcBezierYFcnXDerivative(vN, ...
    ratFibrilModelsFitted(1).curves.fiberForceVelocityCalibratedCurve,...
    0);


subplot('Position',reshape(plotConfig.subPlotPanel(3,1,:),1,4));
subplotPosition = reshape(plotConfig.subPlotPanel(3,1,:),1,4);
    fill([min(sampleFlNFitted.x);...
          max(sampleFlNFitted.x);...
          fliplr(sampleFlNFitted.x')'],...
          [0;...
           0;...
          fliplr((sampleFlNFitted.y.*fvN)')'],...
          [1,1,1].*0.9,'EdgeAlpha',0,...
          'HandleVisibility','off');
    hold on; 

    fill([min(sampleFlNFitted.x);...
          max(sampleFlNFitted.x);...
          fliplr(sampleFlNFitted.x')'],...
          [0;...
           0;...
          fliplr(sampleFlNFitted.y')'],...
          [1,1,1].*0.8,'EdgeAlpha',0,...
          'HandleVisibility','off');
    hold on;  

    xP=1.45;
    yP= interp1(sampleFlNFitted.x,sampleFlNFitted.y,xP);
    text(xP,yP,'$$f^{L}(\ell^M)$$',...
        'HorizontalAlignment','right',...
        'VerticalAlignment','top',...
        'rotation',-30,...
        'FontSize',8);
    hold on;

    text(xP,yP*fvN,'$$f^{L}(\ell^M)f^{V}(v^M)$$',...
        'HorizontalAlignment','right',...
        'VerticalAlignment','bottom',...
        'rotation',-35,...
        'FontSize',8);
    hold on;


for idx=simConfig.trials
    hVis='off';
    %if(idx==1)
        hVis='on';
    %end
    plot(expTRSS2017.activeLengtheningData(idx).x./lceOptMdl,...
         expTRSS2017.activeLengtheningData(idx).y,...
         '-','Color',plotConfig.lineColors.exp(idx,:),...
         'LineWidth',lineWidthExp,...
         'DisplayName',['TRSS2017: $$f^{EXP}_',num2str(idx),'$$'],...
         'HandleVisibility',hVis);
    hold on;  
    text(expTRSS2017.activeLengtheningData(idx).x(end)./lceOptMdl,...
         expTRSS2017.activeLengtheningData(idx).y(end),...
         sprintf('%s%i%s','$$f^{EXP}_{',idx,'}$$'),...
         'HorizontalAlignment','right',...
         'VerticalAlignment','baseline',...
         'FontSize',8,...
         'Color',plotConfig.lineColors.exp(idx,:));
    hold on;


end



for idx=simConfig.trials     
    subplot('Position',reshape(plotConfig.subPlotPanel(3,1,:),1,4)); 
    subplotPosition = reshape(plotConfig.subPlotPanel(3,1,:),1,4);



        idxKey=expTRSS2017.activeLengtheningData(idx).keyIndices(...
                fittingConfig.idxFvKey);
        lceNKey = expTRSS2017.activeLengtheningData(idx).x(idxKey)/lceOptMdl;
        fceNKey = expTRSS2017.activeLengtheningData(idx).y(idxKey); 

        fvCurve = ratFibrilModelsFitted(idx).curves.fiberForceVelocityCurve;
        falCurve = ratFibrilModelsFitted(idx).curves.activeForceLengthCurve;
        lceNV = benchRecordFitted.normFiberLength(:,idx);
        vceNV = benchRecordFitted.normFiberVelocity(:,idx);



        fvNV    = zeros(size(lceNV));
        falNV   = zeros(size(lceNV));
        for i=1:1:length(lceNV)
            falNV(i,1)=calcBezierYFcnXDerivative(lceNV(i,1),falCurve,0);
            fvNV(i,1)=calcBezierYFcnXDerivative(vceNV(i,1),fvCurve,0);
        end
        fxeNV = fvNV.*falNV;

        txtName = expTRSS2017.activeLengtheningData(idx).seriesName;
        i0=strfind(txtName,'Exp.');
        txtName(1,i0:4)='Sim.';


        idxValid = find(lceNV >= lceNKey);

        hdlVis='off';
        %if(idx==1)
        %    hdlVis='on';                
        %end
        
        if(addErrorText)
            text(lceNV(idxValid(1,1)),...
                 fxeNV(idxValid(1,1)),...
                 sprintf('%1.3f',fitInfo.fv.yErr(1,idx)),...
                 'HorizontalAlignment','left',...
                 'VerticalAlignment','top',...
                 'FontSize',8);
            hold on;
        end

        idxKeyF0 = expTRSS2017.activeLengtheningData(idx).keyIndices(...
                        fittingConfig.idxFlKey);
        idxKeyF2 = expTRSS2017.activeLengtheningData(idx).keyIndices(...
                         fittingConfig.idxFvKey);

        plot(expTRSS2017.activeLengtheningData(idx).x(idxKeyF0)./lceOptMdl,...
             expTRSS2017.activeLengtheningData(idx).y(idxKeyF0),...
             'o','Color',[0,0,0],...
             'MarkerSize',2,...
             'HandleVisibility','off');
        hold on;

        if(addErrorText)
            text(expTRSS2017.activeLengtheningData(idx).x(idxKeyF0)./lceOptMdl,...
                 expTRSS2017.activeLengtheningData(idx).y(idxKeyF0),...
                 sprintf('%1.3f',fitInfo.fl.yErr(1,idx)),...
                 'HorizontalAlignment','left',...
                 'VerticalAlignment','top',...
                 'FontSize',8);
            hold on;
        end

        plot(expTRSS2017.activeLengtheningData(idx).x(idxKeyF2)./lceOptMdl,...
             expTRSS2017.activeLengtheningData(idx).y(idxKeyF2),...
             'x','Color',[0,0,0],...
             'MarkerSize',2,...
             'HandleVisibility','off');
        hold on;
        
    

        xlim([pubPlotOptions.lceNMin,pubPlotOptions.lceNMax]);

        box off;


    subplot('Position',reshape(plotConfig.subPlotPanel(3,1,:),1,4));   
    subplotPosition = reshape(plotConfig.subPlotPanel(3,1,:),1,4);

        idxKey=expTRSS2017.activeLengtheningData(idx).keyIndices(...
                fittingConfig.idxFvKey);
        lceNKey = expTRSS2017.activeLengtheningData(idx).x(idxKey)/lceOptMdl;
        fceNKey = expTRSS2017.activeLengtheningData(idx).y(idxKey);           
              
        lceNVU= unique(lceNV);

        lceNExp = expTRSS2017.activeLengtheningData(idx).x ./ lceOptMdl;
        [lceNExpU,iu] = unique(lceNExp);
        fceNExp = expTRSS2017.activeLengtheningData(idx).y;
        fceNExpU = fceNExp(iu);

        titinAnalysis(idx).lceN = lceNVU;
        titinAnalysis(idx).fceN = interp1(lceNExpU,fceNExpU,lceNVU,'linear');

        

        [lceNU,iU]=unique(lceNV);
        fxeNU=fxeNV(iU);

        idxZeroTitin = find(titinAnalysis(idx).lceN <= lceNKey);  
        titinAnalysis(idx).fxeN = interp1(lceNU,fxeNU,titinAnalysis(idx).lceN);
        titinAnalysis(idx).f2N  = titinAnalysis(idx).fceN-titinAnalysis(idx).fxeN;
        titinAnalysis(idx).f2N(idxZeroTitin)=0;
        titinAnalysis(idx).f2N(titinAnalysis(idx).f2N<=0)=0;

        hVis='off';
        %if(idx==1)
        %    hVis='on';
        %end
        plot(titinAnalysis(idx).lceN, ...
             titinAnalysis(idx).f2N,...
             '-','Color',plotConfig.lineColors.calcTitinF(idx,:),...
             'LineWidth',lineWidthEst,...
             'DisplayName',['$$f^C_',num2str(idx),'$$'],...
             'HandleVisibility',hVis);
        hold on;
        text(titinAnalysis(idx).lceN(end),...
             titinAnalysis(idx).f2N(end),...
             sprintf('%s%i%s','$$f^{C}_{',idx,'}$$'),...
             'HorizontalAlignment','right',...
             'VerticalAlignment','baseline',...
             'FontSize',8,...
             'Color',plotConfig.lineColors.calcTitinF(idx,:));              
        hold on;

        if(idx==1)
          text(pubPlotOptions.lceNMin,pubPlotOptions.fceNMax,...
               sprintf('%s','TRSS2017 (Exp).: $$f_1^{EXP},f_2^{EXP},f_3^{EXP}$$'),...
               'HorizontalAlignment','left',...
               'VerticalAlignment','top',...
               'FontSize',8);
        end
        box off;
        xlim([pubPlotOptions.lceNMin,pubPlotOptions.lceNMax]);
        ylim([0,pubPlotOptions.fceNMax]);

        xlabel('Norm. Length ($$\ell/\ell_o^M$$)');
        ylabel(expTRSS2017.activeLengtheningData(3).yName);
        %title({'Experimental, simulated, and estimated','crossbridge and titin forces'});
        title({[subplotIds{1},...
               ' Fitted $$f^L(\tilde{\ell}^M),\,\&\,f^V(\tilde{\ell}^M)$$ and'],...
               'estimated titin forces'},...
               'HorizontalAlignment','center');

%         if(idx==3 && addLegends)
%             [lgdH, lgdIcons, lgdPlots, lgdTxt]=...
%                 legend('Location','southwest','FontSize',6*(9/11.7));
%             legend boxoff;
%             lgdH = adjustLegendProperties(lgdH);
%             lgdH.Position(1)=subplotPosition(1)-2*lgdH.Position(3);
%             
%         end


            

    subplot('Position',reshape(plotConfig.subPlotPanel(3,2,:),1,4));  
    subplotPosition = reshape(plotConfig.subPlotPanel(3,2,:),1,4);

        idxKValid = find(titinAnalysis(idx).f2N >...
                    pubPlotOptions.stiffnessLowerForceBound);

        xSpan = max(titinAnalysis(idx).lceN)-min(titinAnalysis(idx).lceN);
        [sp,f2NS,rho] = spaps(...
            titinAnalysis(idx).lceN(idxKValid),...
            titinAnalysis(idx).f2N(idxKValid),1e-6);

        f2NSFit = fnval(sp,titinAnalysis(idx).lceN(idxKValid));
        titinAnalysis(idx).f2NS=titinAnalysis(idx).f2N;
        titinAnalysis(idx).f2NS(idxKValid)=f2NSFit;

        titinAnalysis(idx).k2N = ...
            calcCentralDifferenceDataSeries(...
                titinAnalysis(idx).lceN,...
                titinAnalysis(idx).f2N);

        titinAnalysis(idx).k2NS = ...
            calcCentralDifferenceDataSeries(...
                titinAnalysis(idx).lceN,...
                titinAnalysis(idx).f2NS);
        lceNSpan = max(titinAnalysis(idx).lceN)...
                  -min(titinAnalysis(idx).lceN);

        hVis='off';
        %if(idx==1)
        %    hVis='on';
        %end

        plot(titinAnalysis(idx).lceN-titinAnalysis(idx).lceN(1,1), ...
             titinAnalysis(idx).f2N,...
             '-','Color',plotConfig.lineColors.calcTitinF(idx,:),...
             'LineWidth',lineWidthEst,...
             'DisplayName',...
             sprintf('%s',['$$f^{C}_{',num2str(idx),'}$$']),...
             'HandleVisibility',hVis);
        hold on;
        text(titinAnalysis(idx).lceN(end)-titinAnalysis(idx).lceN(1,1),...
             titinAnalysis(idx).f2N(end),...
             sprintf('%s%i%s','$$f^{C}_{',idx,'}$$'),...
             'HorizontalAlignment','right',...
             'VerticalAlignment','baseline',...
             'FontSize',8);
        hold on;



        box off;

        xlabel('$$\Delta$$ Norm. Length $$(\ell - \ell_i)/\ell_o^M$$');
        ylabel('Norm. Force ($$f/f_o^M$$)');
        title({[subplotIds{2},' Titin''s active force--'],...
              'length-change relation'},...
              'HorizontalAlignment','center');  
        
        xlim([0,lceNSpan]);
        ylim([0,pubPlotOptions.fceNMax]);        
%         if(idx==3)
%             [lgdH, lgdIcons, lgdPlots, lgdTxt]=...
%                 legend('Location','northwest','FontSize',6*(9/11.7));
%             legend boxoff;
%             lgdH = adjustLegendProperties(lgdH);          
%             lgdH.Position(1)=subplotPosition(1)+1.25*subplotPosition(3);
%         end

end

%
% Generate plots that compare the simulation results to the experiments
%

curveFitted = ratFibrilModelsFitted(1).curves.activeForceLengthCurve;    
sampleFlNFitted=calcBezierYFcnXCurveSampleVector(...
                curveFitted,100,curveFitted.xEnd);


vN = benchRecordFitted.normFiberVelocity(end,1);
fvN = calcBezierYFcnXDerivative(vN, ...
    ratFibrilModelsFitted(1).curves.fiberForceVelocityCalibratedCurve,...
    0);

subplot('Position',reshape(plotConfig.subPlotPanel(5,1,:),1,4)); 
subplotPosition = reshape(plotConfig.subPlotPanel(5,1,:),1,4);
    fill([min(sampleFlNFitted.x);...
          max(sampleFlNFitted.x);...
          fliplr(sampleFlNFitted.x')'],...
          [0;...
           0;...
          fliplr((sampleFlNFitted.y.*fvN)')'],...
          [1,1,1].*0.9,'EdgeAlpha',0,...
          'HandleVisibility','off');
    hold on; 

    fill([min(sampleFlNFitted.x);...
          max(sampleFlNFitted.x);...
          fliplr(sampleFlNFitted.x')'],...
          [0;...
           0;...
          fliplr(sampleFlNFitted.y')'],...
          [1,1,1].*0.8,'EdgeAlpha',0,...
          'HandleVisibility','off');
    hold on; 

    text(xP,yP,'$$f^{L}(\ell^M)$$',...
        'HorizontalAlignment','right',...
        'VerticalAlignment','top',...
        'rotation',-30,...
        'FontSize',8);
    hold on;

    text(xP,yP*fvN,'$$f^{L}(\ell^M)f^{V}(v^M)$$',...
        'HorizontalAlignment','right',...
        'VerticalAlignment','bottom',...
        'rotation',-35,...
        'FontSize',8);
    hold on;


for idx=simConfig.trials     
    hdlVis='off';
    if(idx==1)
       hdlVis = 'on';
    end

    plot(expTRSS2017.activeLengtheningData(idx).x./lceOptMdl,...
         expTRSS2017.activeLengtheningData(idx).y,...
         '-','Color',plotConfig.lineColors.exp(idx,:),...
         'LineWidth',lineWidthExp,...
         'DisplayName','TRSS2017',...
         'HandleVisibility',hdlVis);
    hold on; 

    text(expTRSS2017.activeLengtheningData(idx).x(end)./lceOptMdl,...
         expTRSS2017.activeLengtheningData(idx).y(end),...
         sprintf('%s%i%s','$$f^{EXP}_{',idx,'}$$'),...
         'HorizontalAlignment','right',...
         'VerticalAlignment','bottom',...
         'FontSize',8,...
         'Color',plotConfig.lineColors.exp(idx,:));
    hold on;

    ffit='';
    if(~isempty(fitInfo.QToF.x))
        ffit = 'QToF';        
    end
    if(~isempty(fitInfo.QToK.x))
        ffit = 'QToK';        
    end    
    if(~isempty(fitInfo.f1HNPreload.x))
        ffit = 'f1HNPreload';        
    end
    if(~isempty(fitInfo.l1HNOffset.x))
        ffit = 'l1HNOffset';        
    end    

    xErr = fitInfo.(ffit).x(end,idx)./lceOptMdl;
    yErr = (fitInfo.(ffit).y(end,idx) + fitInfo.(ffit).yFit(end,idx)).*0.5;

    rmseTrial = sqrt(mean(fitInfo.(ffit).yErr(:,idx).^2));

    hVis='off';
    %if(idx==1)
    %  hVis='on';
    %end
    plot(titinAnalysis(idx).lceN, ...
         titinAnalysis(idx).f2N,...
         '-','Color',plotConfig.lineColors.calcTitinF(idx,:),...
         'LineWidth',lineWidthEst,...
         'DisplayName','Titin (Est)',...         
         'HandleVisibility',hVis);   

    text(titinAnalysis(idx).lceN(end),...
         titinAnalysis(idx).f2N(end),...
         sprintf('%s%i%s','$$f^{C}_{',idx,'}$$'),...
         'HorizontalAlignment','right',...
         'VerticalAlignment','bottom',...
         'FontSize',8,...
         'Color',plotConfig.lineColors.calcTitinF(idx,:));
    hold on;    
    
   plot( benchRecordFitted.normFiberLength(:,idx), ...
         benchRecordFitted.normFiberForce(:,idx),...
         '-','Color',plotConfig.lineColors.simF(idx,:),...
         'LineWidth',lineWidthSim,...         
         'DisplayName',['$$f^{M}_',num2str(idx),'(\tilde{\ell}^M)$$ (Sim)'],...
         'HandleVisibility',hVis);

   hold on;

   text(benchRecordFitted.normFiberLength(end,idx),...
        benchRecordFitted.normFiberForce(end,idx),...
         sprintf('%s%i%s','$$f^{M}_{',idx,'}$$'),...
         'HorizontalAlignment','left',...
         'VerticalAlignment','bottom',...
         'FontSize',8,...
         'Color',plotConfig.lineColors.simF(idx,:));
    hold on;   

   plot( benchRecordFitted.normFiberLength(:,idx), ...
         benchRecordFitted.normDistalTitinForce(:,idx),...
         '-','Color',plotConfig.lineColors.simTitinF(idx,:),...
         'LineWidth',lineWidthSim,...         
         'DisplayName',['$$f^{2}_',num2str(idx),'(\tilde{\ell}^M)$$ (Sim)'],...
         'HandleVisibility',hVis);
   hold on;

   text(benchRecordFitted.normFiberLength(end,idx),...
        benchRecordFitted.normDistalTitinForce(end,idx),...
         sprintf('%s%i%s','$$f^{2}_{',idx,'}$$'),...
         'HorizontalAlignment','left',...
         'VerticalAlignment','bottom',...
         'FontSize',8,...
         'Color',plotConfig.lineColors.simTitinF(idx,:));
    hold on;     

   if(idx==1 && simConfig.fitToIndividualTrials==1)
       %%
       % Annotate the largest error between the fiber force and the data
       %%
        npts=100;
        x0 = benchRecordFitted.normFiberLength(1,idx);
        x1 = benchRecordFitted.normFiberLength(end,idx);
        xV = [0:(1/(npts-1)):1]' .*(x1-x0) + x0;
        [c,ia,ic] = unique(expTRSS2017.activeLengtheningData(idx).x);
        yV = interp1(expTRSS2017.activeLengtheningData(idx).x(ia)./lceOptMdl,...
                     expTRSS2017.activeLengtheningData(idx).y(ia),...
                     xV);
        [c,ia,ic] = unique(benchRecordFitted.normFiberLength(:,idx));        
        yVFit = interp1(benchRecordFitted.normFiberLength(ia,idx),...
                       benchRecordFitted.normFiberForce(ia,idx),...
                       xV);
        [maxErrV,idxMaxErr] = max(abs(yV-yVFit));
        text(xV(idxMaxErr,1),yV(idxMaxErr,1)+0.1,...
             sprintf('%s%1.2f%s','$$\epsilon_{MAX}^{M}=',maxErrV,'$$'),...
             'HorizontalAlignment','right',...
             'FontSize',8);        
        hold on;
        plot([1,1].*xV(idxMaxErr,1),...
             [yVFit(idxMaxErr,1),yV(idxMaxErr,1)],...
             '-k',...
             'HandleVisibility','off');
        hold on;
        plot([1,1].*xV(idxMaxErr,1),...
             [yV(idxMaxErr,1),yVFit(idxMaxErr,1)],...
             '.k',...
             'HandleVisibility','off');
        hold on;

       %%
       % Annotate the largest error between the titin force and the data
       %%
        npts=100;
        x0 = benchRecordFitted.normFiberLength(1,idx);
        x1 = benchRecordFitted.normFiberLength(end,idx);
        xV = [0:(1/(npts-1)):1]' .*(x1-x0) + x0;
        [c,ia,ic] = unique(titinAnalysis(idx).lceN);
        yV = interp1(titinAnalysis(idx).lceN(ia),...
                     titinAnalysis(idx).f2N(ia),...
                     xV);
        [c,ia,ic] = unique(benchRecordFitted.normFiberLength(:,idx));        
        yVFit = interp1(benchRecordFitted.normFiberLength(ia,idx),...
                       benchRecordFitted.normDistalTitinForce(ia,idx),...
                       xV);
        [maxErrV,idxMaxErr] = max(abs(yV-yVFit));
        text(xV(idxMaxErr,1),yV(idxMaxErr,1)+0.1,...
             sprintf('%s%1.2f%s','$$\epsilon_{MAX}^{C}=',maxErrV,'$$'),...
             'HorizontalAlignment','right',...
             'FontSize',8);        
        hold on;
        plot([1,1].*xV(idxMaxErr,1),...
             [yVFit(idxMaxErr,1),yV(idxMaxErr,1)],...
             '-k',...
             'HandleVisibility','off');
        hold on;
        plot([1,1].*xV(idxMaxErr,1),...
             [yV(idxMaxErr,1),yVFit(idxMaxErr,1)],...
             '.k',...
             'HandleVisibility','off');

        
        
   end

end


box off;
xlim([pubPlotOptions.lceNMin,pubPlotOptions.lceNMax]);
ylim([0,pubPlotOptions.fceNMax]); 
xlabel('Norm. Length ($$\ell/\ell_o^M$$)');
ylabel(expTRSS2017.activeLengtheningData(3).yName);

% [lgdH, lgdIcons, lgdPlots, lgdTxt]=...
%     legend('Location','northwest','FontSize',6*(9/11.7));
% legend boxoff;
% lgdH = adjustLegendProperties(lgdH);
% lgdH.Position(1)=subplotPosition(1)-2*lgdH.Position(3);

% [lgdH, lgdIcons, lgdPlots, lgdTxt,xDataOrig,xDataUpd] = ...
% scaleLegendLines(0.5,lgdH, lgdIcons, lgdPlots, lgdTxt);

title({[subplotIds{1},...
        ' Fitted $$f^L(\tilde{\ell}^M),\,\&\,f^V(\tilde{\ell}^M)$$ and'],...
       'estimated titin forces $$f^{C}(\tilde{\ell}^{M})$$'},...
       'HorizontalAlignment','center');


subplot('Position',reshape(plotConfig.subPlotPanel(5,2,:),1,4));     
subplotPosition = reshape(plotConfig.subPlotPanel(5,2,:),1,4);

    for idx=simConfig.trials
        hVis='off';
        %if(idx==1)
        %   hVis='on';
        %end

        plot(titinAnalysis(idx).lceN-titinAnalysis(idx).lceN(1,1), ...
             titinAnalysis(idx).f2N,...
             '-','Color',plotConfig.lineColors.calcTitinF(idx,:),...
             'LineWidth',lineWidthEst,...             
             'DisplayName',...
             sprintf('%s%s',['$$f^{C}_',num2str(idx),'(\tilde{\ell}^M)'],'$$ (Est)'),...
             'HandleVisibility',hVis);
        hold on;

       text(titinAnalysis(idx).lceN(end)-titinAnalysis(idx).lceN(1,1),...
            titinAnalysis(idx).f2N(end),...
             sprintf('%s%i%s','$$f^{C}_{',idx,'}$$'),...
             'HorizontalAlignment','right',...
             'VerticalAlignment','bottom',...
             'FontSize',8,...
             'Color',plotConfig.lineColors.calcTitinF(idx,:));
        hold on;         

    end

    for idx=simConfig.trials

        hVis='off';
        %if(idx==1)
        %    hVis='on';
        %end
       

       plot( benchRecordFitted.normFiberLength(:,idx)...
              -benchRecordFitted.normFiberLength(1,idx), ...
             benchRecordFitted.normDistalTitinForce(:,idx),...
             '-','Color',plotConfig.lineColors.simTitinF(idx,:),...
             'LineWidth',lineWidthSim,...
             'DisplayName',sprintf('%s%s',['$$f^{2}_',num2str(idx),'(\tilde{\ell}^M)'],'$$ (Sim)' ),...
             'HandleVisibility',hVis);

       hold on;   

       text(benchRecordFitted.normFiberLength(end,idx)...
              -benchRecordFitted.normFiberLength(1,idx), ...
            benchRecordFitted.normDistalTitinForce(end,idx),...
             sprintf('%s%i%s','$$f^{2}_{',idx,'}$$'),...
             'HorizontalAlignment','left',...
             'VerticalAlignment','bottom',...
             'FontSize',8,...
             'Color',plotConfig.lineColors.simTitinF(idx,:));
        hold on;        

       lceNSpan = benchRecordFitted.normFiberLength(end,idx)...
                 -benchRecordFitted.normFiberLength(1,idx);
%        text(lceNSpan,...
%             benchRecordFitted.normDistalTitinForce(end,idx),...
%              sprintf('%1.1f%s',benchRecordFitted.normDistalTitinForce(end,idx),'$$f_o^M$$'),...
%              'HorizontalAlignment','left',...
%              'VerticalAlignment','top',...
%              'FontSize',8);
%        hold on;

       %%
       % Annotate the largest error between the titin force and the data
       %%
      if(idx==1 && simConfig.fitToIndividualTrials==1)
        npts=100;
        x0 = 0;
        x1 = benchRecordFitted.normFiberLength(end,idx) ...
            -benchRecordFitted.normFiberLength(1,idx);
        xV = [0:(1/(npts-1)):1]' .*(x1-x0) + x0;
        [c,ia,ic] = unique(titinAnalysis(idx).lceN);
        yV = interp1(titinAnalysis(idx).lceN(ia)-titinAnalysis(idx).lceN(ia(1)),...
                     titinAnalysis(idx).f2N(ia),...
                     xV);
        [c,ia,ic] = unique(benchRecordFitted.normFiberLength(:,idx));        
        yVFit = interp1(benchRecordFitted.normFiberLength(ia,idx) ...
                       -benchRecordFitted.normFiberLength(ia(1),idx),...
                       benchRecordFitted.normDistalTitinForce(ia,idx),...
                       xV);
        [maxErrV,idxMaxErr] = max(abs(yV-yVFit));
        text(xV(idxMaxErr,1)+0.075,yVFit(idxMaxErr,1),...
             sprintf('%s%1.2f%s','$$\epsilon_{MAX}^{C}=',maxErrV,'$$'),...
             'HorizontalAlignment','left',...
             'VerticalAlignment','baseline',...
             'FontSize',8);        
        hold on;
        plot([(xV(idxMaxErr,1)+0.025),(xV(idxMaxErr,1)+0.075)],...
             [yVFit(idxMaxErr,1),yVFit(idxMaxErr,1)],...
             '-k',...
             'HandleVisibility','off');
        hold on;
        
        plot([1,1].*xV(idxMaxErr,1),...
             [yVFit(idxMaxErr,1),yV(idxMaxErr,1)],...
             '-k',...
             'HandleVisibility','off');
        hold on;
        plot([1,1].*xV(idxMaxErr,1),...
             [yV(idxMaxErr,1),yVFit(idxMaxErr,1)],...
             '.k',...
             'HandleVisibility','off');
      end

    end    

box off;
xlim([0,lceNSpan]);
ylim([0,pubPlotOptions.fceNMax]);

xlabel('$$\Delta$$ Norm. Length $$(\ell - \ell_i)/\ell_o^M$$');
ylabel('Norm. Force ($$f/f_o^M$$)');
title({[subplotIds{2},' Titin''s active force--'],'length-change relation'},...
      'HorizontalAlignment','center');  

% [lgdH, lgdIcons, lgdPlots, lgdTxt]=...
%     legend('Location','northwest','FontSize',6*(9/11.7));
% legend boxoff;
% lgdH = adjustLegendProperties(lgdH);
% lgdH.Position(1)=subplotPosition(1)+1.25*subplotPosition(3);





