%%
% SPDX-FileCopyrightText: 2023 Matthew Millard <millard.matthew@gmail.com>
%
% SPDX-License-Identifier: MIT
%
%
%%

function figPub = plotRatFibrilTRSS2017(...
                    figPub,...
                    ratFibrilModelsDefault,...
                    ratFibrilModelsFitted,...
                    fitInfo,...
                    benchRecordFitted,...
                    expTRSS2017Raw,...
                    simConfig,...
                    fittingConfig,...
                    plotConfig,...
                    pubPlotOptions)


lineWidthSim = 1.0;
lineWidthTimeSeries=1;
lineWidthExp = 0.25;
lineWidthEst = 0.75;


addLegends = 0;
addErrorText=0;

subplotIds = {'A.','B.'};
if(simConfig.fitToIndividualTrials==1)
    subplotIds = {'C.','D.'};
end

flag_legendType = 1; %0: Explicit
                     %1: List

%
% Plot the force-length relation
%


expfl.lceN = [];
expfl.fN   = []; 

mdlfl.lceN = [];
mdlfl.fN   = [];

assert(ratFibrilModelsDefault(1).curves.useCalibratedCurves==1,...
       'Error: the calibrated curves should be used');

curveFalN = ratFibrilModelsDefault(1).curves.activeForceLengthCurve; 
lceOptMdl = ratFibrilModelsDefault(1).musculotendon.optimalFiberLength;    

for idxTrial = simConfig.trials
    seriesName = expTRSS2017Raw.trials{idxTrial};
    lceN  = expTRSS2017Raw.(seriesName).lN(1,1); 
      %expTRSS2017.activeLengtheningData(idxTrial).x(1,1);
    fN   =  expTRSS2017Raw.(seriesName).fNavg(1,1);
      %expTRSS2017.activeLengtheningData(idxTrial).y(1,1);

    expfl.lceN  = [expfl.lceN;lceN];
    expfl.fN    = [expfl.fN;fN];   

    fNMdl = calcBezierYFcnXDerivative(lceN,curveFalN,0);
    mdlfl.lceN  = [mdlfl.lceN;lceN];
    mdlfl.fN    = [mdlfl.fN;fNMdl];
            
end    

%
% fal-fitting
%
subplot('Position',reshape(plotConfig.subPlotPanel(1,1,:),1,4));
subplotPosition = reshape(plotConfig.subPlotPanel(1,1,:),1,4);

    curveFitted = ratFibrilModelsFitted(1).curves.activeForceLengthCurve;    
    curveOrig = ratFibrilModelsDefault(1).curves.activeForceLengthCurve;

    sampleFlNOrig=calcBezierYFcnXCurveSampleVector(...
                    curveOrig,100,curveOrig.xEnd);
    
    sampleFlNFitted=calcBezierYFcnXCurveSampleVector(...
                    curveFitted,100,curveFitted.xEnd);

    plot(sampleFlNOrig.x,sampleFlNOrig.y,'-',...
         'Color',[1,1,1].*0.75,'DisplayName','$$f^L(\ell^M)$$');
    hold on;
    plot(sampleFlNFitted.x,sampleFlNFitted.y,'-',...
         'Color',[1,1,1].*0.75,'DisplayName','$$f^L(\ell^M) (fitted)$$');
    hold on;

    for idx=simConfig.trials        
        plot(expfl.lceN(idx),...
             expfl.fN(idx),...
             '+','Color',[0,0,0],...
             'MarkerFaceColor',plotConfig.lineColors.exp(idx,:));
        hold on;
    end
    xlabel('Norm. Length ($$\ell/\ell_o^M$$)');
    ylabel('Norm. Force ($$f /f_o^M$$)');
    title('Force-Length Relation Fitting');  
    xlim([pubPlotOptions.lceNMin,pubPlotOptions.lceNMax]);
    box off;
    hold on;   

%
% fv-fitting
%        
subplot('Position',reshape(plotConfig.subPlotPanel(1,2,:),1,4));
subplotPosition = reshape(plotConfig.subPlotPanel(1,2,:),1,4);

    plot(sampleFlNFitted.x,sampleFlNFitted.y,'-',...
         'Color',[1,1,1].*0.75,'DisplayName','$$f^L(\ell^M)$$');
    hold on;        

    curveFvN        = ratFibrilModelsDefault(1).curves.fiberForceVelocityCurve;
    curveFvNFitted  = ratFibrilModelsFitted(1).curves.fiberForceVelocityCurve;

    fvN = calcBezierYFcnXDerivative(0.11,curveFvN,0);
    fvNFitted = calcBezierYFcnXDerivative(0.11,curveFvNFitted,0);
    
    plot(sampleFlNFitted.x,...
         sampleFlNFitted.y.*fvN,'-',...
         'Color',[1,1,1].*0.75,'DisplayName','$$f^L(\ell^M)f^V(v^M)$$');
    hold on;  
    plot(sampleFlNFitted.x,...
         sampleFlNFitted.y.*fvNFitted,'-',...
         'Color',[1,1,1].*0.75,'DisplayName','$$f^L(\ell^M)f^V(v^M)$$ (fitted)');
    hold on;  

    for idx=simConfig.trials
        hdlVis='off';
        %if(idx==1)
        %    hdlVis = 'on';
        %end
        %lceN  = expTRSS2017Raw.(idxFieldsTRSS2017{idxTrial}).lN(1,1); 
        %expTRSS2017.activeLengtheningData(idxTrial).x(1,1);
        %fN   =  expTRSS2017Raw.(idxFieldsTRSS2017{idxTrial}).fNavg(1,1);
        seriesName = expTRSS2017Raw.trials{idx};
        stdAreaX = [expTRSS2017Raw.(seriesName).lN; ...
                   fliplr(expTRSS2017Raw.(seriesName).lN')'];
        stdAreaY = [(expTRSS2017Raw.(seriesName).fNavg...
                      -expTRSS2017Raw.(seriesName).fNstd); ...
                   fliplr((expTRSS2017Raw.(seriesName).fNavg...
                      +expTRSS2017Raw.(seriesName).fNstd)')'];

        stdAreaColor = plotConfig.lineColors.exp(idx,:).*0.5 + ([1,1,1].*0.75).*0.5;
        fill(stdAreaX,stdAreaY,stdAreaColor,...
             'EdgeColor','none',...
             'FaceAlpha',0.5); 
        hold on;

        plot(expTRSS2017Raw.(seriesName).lN,...
             expTRSS2017Raw.(seriesName).fNavg,...
              '-','Color',plotConfig.lineColors.exp(idx,:),...
             'DisplayName','$$f^{EXP}$$ TRSS2017',...
             'HandleVisibility',hdlVis);             
        hold on;

%         plot(expTRSS2017.activeLengtheningData(idx).x./lceOptMdl,...
%              expTRSS2017.activeLengtheningData(idx).y,...
%              '-','Color',plotConfig.lineColors.exp(idx,:),...
%              'DisplayName','$$f^{EXP}$$ TRSS2017',...
%              'HandleVisibility',hdlVis);
%         hold on; 
        seriesName = expTRSS2017Raw.trials{idx};    
        idxKeyF = expTRSS2017Raw.keyIndices.(seriesName)(...
                         fittingConfig.idxFvKey);        
        lceNKey = expTRSS2017Raw.(seriesName).lN(idxKeyF);
        fceNKey = expTRSS2017Raw.(seriesName).fNavg(idxKeyF); 

        plot(lceNKey,fceNKey,...
             'x','Color',[0,0,0],...
             'MarkerSize',3,...
             'HandleVisibility','off');
        hold on;         
%         idxKey = expTRSS2017.activeLengtheningData(idx).keyIndices(...
%                     fittingConfig.idxFvKey);
%         plot(expTRSS2017.activeLengtheningData(idx).x(idxKey)./lceOptMdl,...
%              expTRSS2017.activeLengtheningData(idx).y(idxKey),...
%              'x','Color',[0,0,0],...
%              'MarkerSize',3,...
%              'HandleVisibility','off');
%         hold on; 
    end

    xlabel('Norm. Length ($$\ell/\ell_o^M$$)');
    ylabel('Norm. Force ($$f/f_o^M$$)');
    title('Force-Velocity Curve Fitting');  
    xlim([pubPlotOptions.lceNMin,pubPlotOptions.lceNMax]);
    box off;
    hold on;           

%
% Experimental overview plots
%
subplot('Position',reshape(plotConfig.subPlotPanel(2,1,:),1,4));
subplotPosition = reshape(plotConfig.subPlotPanel(2,1,:),1,4);

  seriesName = expTRSS2017Raw.trialsLong{1};



  yyaxis left;

  boxTime = [0,1,1,0,0].*(0.45/(2.25*0.11)) + 5;
  boxLength=[0,0,1,1,0].*(3.0);

  plot(boxTime,boxLength,'-',...
    'Color',plotConfig.lineColors.annotationBox);
  hold on;

  longSeriesFields = fields(expTRSS2017Raw.(seriesName));

  colorF1 = plotConfig.lineColors.timeSeriesF;
  colorF2 = colorF1.*0.1 + ([1,1,1].*0.75).*0.9;

  colorL1 = plotConfig.lineColors.timeSeriesL;
  colorL2 = colorL1.*0.1 + ([1,1,1].*0.75).*0.9;


  flag_plotAllTrials=0;
  iMax=1;
  if(flag_plotAllTrials==1)
    iMax=24;    
  end

  for i=1:1:iMax    
    fNname = num2str(i);
    if(length(fNname)<2)
      fNname=['0',fNname];
    end
    fNname = ['fN',fNname];

    n = (i-1)/(24-1);

    lineColorF = colorF1.*(n) + colorF2.*(1-n);

    if(flag_plotAllTrials==0)
      lineColorF = colorF1;
    end

    plot(expTRSS2017Raw.(seriesName).time,...
         expTRSS2017Raw.(seriesName).(fNname),...
         '-','Color',lineColorF,...
         'LineWidth',lineWidthExp);
    hold on;

    if(flag_plotAllTrials==0)
      idxKeyF0 = 5006;
      idxKeyF2 = 5137;
      
      plot(expTRSS2017Raw.(seriesName).time(idxKeyF0),...
           expTRSS2017Raw.(seriesName).fNavg(idxKeyF0),...
           'o','Color',[0,0,0],...
           'MarkerSize',3,...
           'HandleVisibility','off');
      hold on;
    
      plot(expTRSS2017Raw.(seriesName).time(idxKeyF2),...
           expTRSS2017Raw.(seriesName).fN01(idxKeyF2),...
           'x','Color',[0,0,0],...
           'MarkerSize',3,...
           'HandleVisibility','off');
      hold on;     
    
      text(expTRSS2017Raw.(seriesName).time(idxKeyF0),...
           expTRSS2017Raw.(seriesName).fNavg(idxKeyF0),...
           sprintf('%s%i%s','$$\tilde{\ell}_{',idx,',i}^{A}$$'),...
           'HorizontalAlignment','left',...
           'VerticalAlignment','top',...
           'FontSize',8);
      hold on;
      
      text(expTRSS2017Raw.(seriesName).time(idxKeyF2),...
           expTRSS2017Raw.(seriesName).fNavg(idxKeyF2),...
           sprintf('%s%i%s','$$\tilde{\ell}_{',idx,',i}^{B}$$'),...
           'HorizontalAlignment','left',...
           'VerticalAlignment','top',...
           'FontSize',8);
      hold on;       
    end

  end

  if(flag_plotAllTrials==1)
    stdAreaX = [expTRSS2017Raw.(seriesName).time; ...
               fliplr(expTRSS2017Raw.(seriesName).time')'];
    stdAreaY = [(expTRSS2017Raw.(seriesName).fNavg...
                  -expTRSS2017Raw.(seriesName).fNstd); ...
               fliplr((expTRSS2017Raw.(seriesName).fNavg...
                  +expTRSS2017Raw.(seriesName).fNstd)')'];
  
    stdAreaColor = plotConfig.lineColors.exp(idx,:).*0.5 + ([1,1,1].*0.75).*0.5;
    fill(stdAreaX,stdAreaY,stdAreaColor,...
         'EdgeColor','none',...
         'FaceAlpha',0.5); 
    hold on;
  
    hVis='off';
  
    idx=3;
    plot(expTRSS2017Raw.(seriesName).time,...
         expTRSS2017Raw.(seriesName).fNavg,...
         '-','Color',plotConfig.lineColors.exp(idx,:),...
         'LineWidth',lineWidthExp,...
         'DisplayName',['TRSS2017: $$f^{EXP}_',num2str(idx),'$$'],...
         'HandleVisibility',hVis);
    hold on;  
  
    plot(expTRSS2017Raw.(seriesName).time,...
         expTRSS2017Raw.(seriesName).fNavg,...
         '-','Color',plotConfig.lineColors.exp(idx,:),...
         'LineWidth',lineWidthExp,...
         'DisplayName',['TRSS2017: $$f^{EXP}_',num2str(idx),'$$'],...
         'HandleVisibility',hVis);
    hold on;  
  
  
    text(expTRSS2017Raw.(seriesName).time(end),...
         (expTRSS2017Raw.(seriesName).fNavg(end)...
          +expTRSS2017Raw.(seriesName).fNstd(end)),...
         sprintf('%s%i%s','$$f^{EXP}_{',idx,'}$$'),...
         'HorizontalAlignment','left',...
         'VerticalAlignment','baseline',...
         'FontSize',8,...
         'Color',plotConfig.lineColors.exp(idx,:));
    hold on;
  
    idxKeyF0 = expTRSS2017Raw.keyIndices.(seriesName)(...
                    fittingConfig.idxFlKey);
    idxKeyF2 = expTRSS2017Raw.keyIndices.(seriesName)(...
                     fittingConfig.idxFvKey);
  
    plot(expTRSS2017Raw.(seriesName).time(idxKeyF0),...
         expTRSS2017Raw.(seriesName).fNavg(idxKeyF0),...
         'o','Color',[0,0,0],...
         'MarkerSize',3,...
         'HandleVisibility','off');
    hold on;
  
    plot(expTRSS2017Raw.(seriesName).time(idxKeyF2),...
         expTRSS2017Raw.(seriesName).fNavg(idxKeyF2),...
         'x','Color',[0,0,0],...
         'MarkerSize',3,...
         'HandleVisibility','off');
    hold on;    
  
    text(expTRSS2017Raw.(seriesName).time(idxKeyF0),...
         expTRSS2017Raw.(seriesName).fNavg(idxKeyF0),...
         sprintf('%s%i%s','$$\tilde{\ell}_',idx,'^A$$'),...
         'HorizontalAlignment','left',...
         'VerticalAlignment','top',...
         'FontSize',8);
    hold on;
    
    text(expTRSS2017Raw.(seriesName).time(idxKeyF2),...
         expTRSS2017Raw.(seriesName).fNavg(idxKeyF2),...
         sprintf('%s%i%s','$$\tilde{\ell}_',idx,'^B$$'),...
         'HorizontalAlignment','left',...
         'VerticalAlignment','top',...
         'FontSize',8);
    hold on;    
  end

  


  axis tight;
  ylim([0,pubPlotOptions.fceNMax]);

  xticks([0,5,round(5+0.45/(2.25*0.11),2)]);
  yticks([0,1,1.37,2.77]);

  xlabel('Time (s)');  
  ylabel('Norm. Force ($$f / f_o^M $$)');
  yyaxis right;

  plot(expTRSS2017Raw.(seriesName).time,...
       expTRSS2017Raw.(seriesName).lN,...
       '-','Color',plotConfig.lineColors.timeSeriesL,...
       'LineWidth',lineWidthExp);
  axis tight;
  ylim([min(expTRSS2017Raw.(seriesName).lN),...
        max(expTRSS2017Raw.(seriesName).lN)*2]);
  yticks([1,1.45]);

  ylabel('Norm. Length ($$\ell / \ell_o^M$$)');
  
  ax = gca;
  ax.YAxis(1).Color = plotConfig.lineColors.timeSeriesF;
  ax.YAxis(2).Color = plotConfig.lineColors.timeSeriesL;  

  box off;
  title('A. Example trial $$i$$');

subplot('Position',reshape(plotConfig.subPlotPanel(2,2,:),1,4));
subplotPosition = reshape(plotConfig.subPlotPanel(2,2,:),1,4);

vN = benchRecordFitted.normFiberVelocity(end,1);
fvN = calcBezierYFcnXDerivative(vN, ...
    ratFibrilModelsFitted(1).curves.fiberForceVelocityCalibratedCurve,...
    0);

fill([min(sampleFlNFitted.x);...
      max(sampleFlNFitted.x);...
      fliplr(sampleFlNFitted.x')'],...
      [0;...
       0;...
      fliplr((sampleFlNFitted.y.*fvN)')'],...
      [1,1,1].*0.9,'EdgeAlpha',0,...
      'HandleVisibility','off');
hold on; 

fill([min(sampleFlNFitted.x);...
      max(sampleFlNFitted.x);...
      fliplr(sampleFlNFitted.x')'],...
      [0;...
       0;...
      fliplr(sampleFlNFitted.y')'],...
      [1,1,1].*0.8,'EdgeAlpha',0,...
      'HandleVisibility','off');
hold on;  

xP=1.45;
yP= interp1(sampleFlNFitted.x,sampleFlNFitted.y,xP);
text(xP,yP,'$$f^{L}(\ell^M)$$',...
    'HorizontalAlignment','right',...
    'VerticalAlignment','top',...
    'rotation',-30,...
    'FontSize',8);
hold on;

text(xP,yP*fvN,'$$f^{L}(\ell^M)f^{V}(v^M)$$',...
    'HorizontalAlignment','right',...
    'VerticalAlignment','bottom',...
    'rotation',-35,...
    'FontSize',8);
hold on;



subplot('Position',reshape(plotConfig.subPlotPanel(2,2,:),1,4));
subplotPosition = reshape(plotConfig.subPlotPanel(2,2,:),1,4);


for idx=simConfig.trials
    
    seriesName = expTRSS2017Raw.trials{idx};
    stdAreaX = [expTRSS2017Raw.(seriesName).lN; ...
               fliplr(expTRSS2017Raw.(seriesName).lN')'];
    stdAreaY = [(expTRSS2017Raw.(seriesName).fNavg...
                  -expTRSS2017Raw.(seriesName).fNstd); ...
               fliplr((expTRSS2017Raw.(seriesName).fNavg...
                  +expTRSS2017Raw.(seriesName).fNstd)')'];

    stdAreaColor = plotConfig.lineColors.exp(idx,:).*0.5 + ([1,1,1].*0.75).*0.5;
    fill(stdAreaX,stdAreaY,stdAreaColor,...
         'EdgeColor','none',...
         'FaceAlpha',0.5); 
    hold on;

    hVis='off';
    %if(idx==1)
    %    hVis='on';
    %end
    plot(expTRSS2017Raw.(seriesName).lN,...
         expTRSS2017Raw.(seriesName).fNavg,...
         '-','Color',plotConfig.lineColors.exp(idx,:),...
         'LineWidth',lineWidthExp,...
         'DisplayName',['TRSS2017: $$f^{EXP}_',num2str(idx),'$$'],...
         'HandleVisibility',hVis);
    hold on;  


    text(expTRSS2017Raw.(seriesName).lN(end),...
         (expTRSS2017Raw.(seriesName).fNavg(end)),...
         sprintf('%s%i%s','$$f^{EXP}_{',idx,'}$$'),...
         'HorizontalAlignment','left',...
         'VerticalAlignment','baseline',...
         'FontSize',8,...
         'Color',plotConfig.lineColors.exp(idx,:));
    hold on;

    text(expTRSS2017Raw.(seriesName).lN(end),...
         (expTRSS2017Raw.(seriesName).fNavg(end)...
          +expTRSS2017Raw.(seriesName).fNstd(end)),...
         sprintf('%s%i%s','$$\sigma^{EXP}_{',idx,'}$$'),...
         'HorizontalAlignment','right',...
         'VerticalAlignment','baseline',...
         'FontSize',8,...
         'Color',plotConfig.lineColors.exp(idx,:));
    hold on;    

    idxKeyF0 = expTRSS2017Raw.keyIndices.(seriesName)(...
                    fittingConfig.idxFlKey);
    idxKeyF2 = expTRSS2017Raw.keyIndices.(seriesName)(...
                     fittingConfig.idxFvKey);

    plot(expTRSS2017Raw.(seriesName).lN(idxKeyF0),...
         expTRSS2017Raw.(seriesName).fNavg(idxKeyF0),...
         'o','Color',[0,0,0],...
         'MarkerSize',3,...
         'HandleVisibility','off');
    hold on;

    plot(expTRSS2017Raw.(seriesName).lN(idxKeyF2),...
         expTRSS2017Raw.(seriesName).fNavg(idxKeyF2),...
         'x','Color',[0,0,0],...
         'MarkerSize',3,...
         'HandleVisibility','off');
    hold on;    

    text(expTRSS2017Raw.(seriesName).lN(idxKeyF0),...
         expTRSS2017Raw.(seriesName).fNavg(idxKeyF0),...
         sprintf('%s%i%s','$$\tilde{\ell}_',idx,'^A$$'),...
         'HorizontalAlignment','left',...
         'VerticalAlignment','top',...
         'FontSize',8);
    hold on;
    
    text(expTRSS2017Raw.(seriesName).lN(idxKeyF2),...
         expTRSS2017Raw.(seriesName).fNavg(idxKeyF2),...
         sprintf('%s%i%s','$$\tilde{\ell}_',idx,'^B$$'),...
         'HorizontalAlignment','left',...
         'VerticalAlignment','top',...
         'FontSize',8);
    hold on;    


end



for idx=simConfig.trials     
  subplot('Position',reshape(plotConfig.subPlotPanel(2,2,:),1,4)); 
  subplotPosition = reshape(plotConfig.subPlotPanel(2,2,:),1,4);


      seriesName = expTRSS2017Raw.trials{idx};    
      idxKeyF = expTRSS2017Raw.keyIndices.(seriesName)(...
                       fittingConfig.idxFvKey);        
      lceNKey = expTRSS2017Raw.(seriesName).lN(idxKeyF);
      fceNKey = expTRSS2017Raw.(seriesName).fNavg(idxKeyF);    

      %idxKey=expTRSS2017.activeLengtheningData(idx).keyIndices(...
      %        fittingConfig.idxFvKey);
      %lceNKey = expTRSS2017.activeLengtheningData(idx).x(idxKey)/lceOptMdl;
      %fceNKey = expTRSS2017.activeLengtheningData(idx).y(idxKey); 

      fvCurve = ratFibrilModelsFitted(idx).curves.fiberForceVelocityCurve;
      falCurve = ratFibrilModelsFitted(idx).curves.activeForceLengthCurve;
      
      lceNV = expTRSS2017Raw.(seriesName).lN;
      %vceNVavg = (expTRSS2017Raw.(seriesName).lN(end) ...
      %        -expTRSS2017Raw.(seriesName).lN(1)) ...
      %        /(expTRSS2017Raw.(seriesName).time(end) ...
      %        -expTRSS2017Raw.(seriesName).time(1)); %
      %vceNV = ones(size(lceNV)).*vceNVavg;
      lpfFreqHz=simConfig.numericalDiffLowPassFilterFrequencyHz;
      [b,a]=butter(2,lpfFreqHz/(0.5*expTRSS2017Raw.sampleFrequencyHz),'low');
      vceNVnum = calcCentralDifferenceDataSeries(...
                  expTRSS2017Raw.(seriesName).time,...
                  filtfilt(b,a,expTRSS2017Raw.(seriesName).lN));
      vceNVavg = mean(vceNVnum);
      vceNV = ones(size(lceNV)).*vceNVavg;
      %lceNV = benchRecordFitted.normFiberLength(:,idx);
      %vceNV = benchRecordFitted.normFiberVelocity(:,idx);



      fvNV    = zeros(size(lceNV));
      falNV   = zeros(size(lceNV));
      for i=1:1:length(lceNV)
          falNV(i,1)=calcBezierYFcnXDerivative(lceNV(i,1),falCurve,0);
          fvNV(i,1)=calcBezierYFcnXDerivative(vceNV(i,1),fvCurve,0);
      end
      fxeNV = fvNV.*falNV;

      txtName = seriesName;
      %i0=strfind(txtName,'Exp.');
      %txtName(1,i0:4)='Sim.';


      idxValid = find(lceNV >= lceNKey);

      hdlVis='off';
      %if(idx==1)
      %    hdlVis='on';                
      %end
      
      if(addErrorText)
          text(lceNV(idxValid(1,1)),...
               fxeNV(idxValid(1,1)),...
               sprintf('%1.3f',fitInfo.fv.yErr(1,idx)),...
               'HorizontalAlignment','left',...
               'VerticalAlignment','top',...
               'FontSize',8);
          hold on;
      end

      xlim([pubPlotOptions.lceNMin,pubPlotOptions.lceNMax]);
      ylim([0,pubPlotOptions.fceNMax]);
      
      box off;


  subplot('Position',reshape(plotConfig.subPlotPanel(2,2,:),1,4));   
  subplotPosition = reshape(plotConfig.subPlotPanel(2,2,:),1,4);

      seriesName = expTRSS2017Raw.trials{idx};
  
      plot(expTRSS2017Raw.(seriesName).lN(idxKeyF0),...
           expTRSS2017Raw.(seriesName).fNavg(idxKeyF0),...
           'o','Color',[0,0,0],...
           'MarkerSize',3,...
           'HandleVisibility','off');
      hold on;

      hVis='off';

      if(idx==1)
        switch flag_legendType
          case 0
            dx = (pubPlotOptions.lceNMax-pubPlotOptions.lceNMin)*0.01;
            text(pubPlotOptions.lceNMin+dx,pubPlotOptions.fceNMax,...
                 sprintf('%s',...
                   ['\begin{tabular}{l l} ',...
                   '\multicolumn{2}{c}{TRSS2017 (Exp)} \\',...
                   'avg. force & std force\\',...
                   ' $$f_1^{EXP}$$ & $$\sigma_1^{EXP}$$ \\',...
                   ' $$f_2^{EXP}$$ & $$\sigma_1^{EXP}$$ \\',...
                   '$$f_3^{EXP}$$ & $$\sigma_1^{EXP}$$',...
                   ' \end{tabular}']),...
                 'HorizontalAlignment','left',...
                 'VerticalAlignment','top',...
                 'FontSize',8);
            hold on;
          case 1
            dx = (pubPlotOptions.lceNMax-pubPlotOptions.lceNMin)*0.01;
            text(pubPlotOptions.lceNMin+dx,pubPlotOptions.fceNMax,...
                 sprintf('%s\n%s',...
                   'TRSS2017',...
                   ['\begin{tabular}{l l l l}',...
                    'Avg. fiber force & $$f_1^{EXP}$$ & $$f_2^{EXP}$$ & $$f_3^{EXP}$$\\',...
                    'Fiber force std. & $$\sigma_1^{EXP}$$ & $$\sigma_2^{EXP}$$ & $$\sigma_3^{EXP}$$\\',...
                    '\end{tabular}']),...
                 'HorizontalAlignment','left',...
                 'VerticalAlignment','top',...
                 'FontSize',8);
            hold on;               
        end
      end
end

box off;


xlabel('Norm. Length ($$\ell/\ell_o^M$$)');
ylabel('Norm. Force ($$f / f_o^M$$)');
%title({'Experimental, simulated, and estimated','crossbridge and titin forces'});
title('B. Data in force-length space','HorizontalAlignment','center');

% title({[subplotIds{1},...
%        ' Fitted $$f^L(\tilde{\ell}^M),\,\&\,f^V(\tilde{\ell}^M)$$ and'],...
%        'estimated titin forces'},...
%        'HorizontalAlignment','center');


%
% Experimental analysis plot
%
vN = benchRecordFitted.normFiberVelocity(end,1);
fvN = calcBezierYFcnXDerivative(vN, ...
    ratFibrilModelsFitted(1).curves.fiberForceVelocityCalibratedCurve,...
    0);


subplot('Position',reshape(plotConfig.subPlotPanel(3,1,:),1,4));
subplotPosition = reshape(plotConfig.subPlotPanel(3,1,:),1,4);
    fill([min(sampleFlNFitted.x);...
          max(sampleFlNFitted.x);...
          fliplr(sampleFlNFitted.x')'],...
          [0;...
           0;...
          fliplr((sampleFlNFitted.y.*fvN)')'],...
          [1,1,1].*0.9,'EdgeAlpha',0,...
          'HandleVisibility','off');
    hold on; 

    fill([min(sampleFlNFitted.x);...
          max(sampleFlNFitted.x);...
          fliplr(sampleFlNFitted.x')'],...
          [0;...
           0;...
          fliplr(sampleFlNFitted.y')'],...
          [1,1,1].*0.8,'EdgeAlpha',0,...
          'HandleVisibility','off');
    hold on;  

    xP=1.45;
    yP= interp1(sampleFlNFitted.x,sampleFlNFitted.y,xP);
    text(xP,yP,'$$f^{L}(\ell^M)$$',...
        'HorizontalAlignment','right',...
        'VerticalAlignment','top',...
        'rotation',-30,...
        'FontSize',8);
    hold on;

    text(xP,yP*fvN,'$$f^{L}(\ell^M)f^{V}(v^M)$$',...
        'HorizontalAlignment','right',...
        'VerticalAlignment','bottom',...
        'rotation',-35,...
        'FontSize',8);
    hold on;

%
%Eval error between hand indexed key points and
%
% for idx=simConfig.trials
%         idxKey = expTRSS2017.activeLengtheningData(idx).keyIndices(...
%                     fittingConfig.idxFvKey);  
% end

for idx=simConfig.trials
    
    seriesName = expTRSS2017Raw.trials{idx};
    stdAreaX = [expTRSS2017Raw.(seriesName).lN; ...
               fliplr(expTRSS2017Raw.(seriesName).lN')'];
    stdAreaY = [(expTRSS2017Raw.(seriesName).fNavg...
                  -expTRSS2017Raw.(seriesName).fNstd); ...
               fliplr((expTRSS2017Raw.(seriesName).fNavg...
                  +expTRSS2017Raw.(seriesName).fNstd)')'];

    stdAreaColor = plotConfig.lineColors.exp(idx,:).*0.5 + ([1,1,1].*0.75).*0.5;
    fill(stdAreaX,stdAreaY,stdAreaColor,...
         'EdgeColor','none',...
         'FaceAlpha',0.5); 
    hold on;

    hVis='off';
    %if(idx==1)
    %    hVis='on';
    %end
    plot(expTRSS2017Raw.(seriesName).lN,...
         expTRSS2017Raw.(seriesName).fNavg,...
         '-','Color',plotConfig.lineColors.exp(idx,:),...
         'LineWidth',lineWidthExp,...
         'DisplayName',['TRSS2017: $$f^{EXP}_',num2str(idx),'$$'],...
         'HandleVisibility',hVis);
    hold on;  


    text(expTRSS2017Raw.(seriesName).lN(end),...
         (expTRSS2017Raw.(seriesName).fNavg(end)...
          +expTRSS2017Raw.(seriesName).fNstd(end)),...
         sprintf('%s%i%s','$$f^{EXP}_{',idx,'}$$'),...
         'HorizontalAlignment','left',...
         'VerticalAlignment','baseline',...
         'FontSize',8,...
         'Color',plotConfig.lineColors.exp(idx,:));
    hold on;

    idxKeyF0 = expTRSS2017Raw.keyIndices.(seriesName)(...
                    fittingConfig.idxFlKey);
    idxKeyF2 = expTRSS2017Raw.keyIndices.(seriesName)(...
                     fittingConfig.idxFvKey);

    plot(expTRSS2017Raw.(seriesName).lN(idxKeyF0),...
         expTRSS2017Raw.(seriesName).fNavg(idxKeyF0),...
         'o','Color',[0,0,0],...
         'MarkerSize',3,...
         'HandleVisibility','off');
    hold on;

    plot(expTRSS2017Raw.(seriesName).lN(idxKeyF2),...
         expTRSS2017Raw.(seriesName).fNavg(idxKeyF2),...
         'x','Color',[0,0,0],...
         'MarkerSize',3,...
         'HandleVisibility','off');
    hold on;    

    text(expTRSS2017Raw.(seriesName).lN(idxKeyF0),...
         expTRSS2017Raw.(seriesName).fNavg(idxKeyF0),...
         sprintf('%s%i%s','$$\tilde{\ell}_',idx,'^A$$'),...
         'HorizontalAlignment','left',...
         'VerticalAlignment','top',...
         'FontSize',8);
    hold on;
    
    text(expTRSS2017Raw.(seriesName).lN(idxKeyF2),...
         expTRSS2017Raw.(seriesName).fNavg(idxKeyF2),...
         sprintf('%s%i%s','$$\tilde{\ell}_',idx,'^B$$'),...
         'HorizontalAlignment','left',...
         'VerticalAlignment','top',...
         'FontSize',8);
    hold on;    


end



for idx=simConfig.trials     
    subplot('Position',reshape(plotConfig.subPlotPanel(3,1,:),1,4)); 
    subplotPosition = reshape(plotConfig.subPlotPanel(3,1,:),1,4);


        seriesName = expTRSS2017Raw.trials{idx};    
        idxKeyF = expTRSS2017Raw.keyIndices.(seriesName)(...
                         fittingConfig.idxFvKey);        
        lceNKey = expTRSS2017Raw.(seriesName).lN(idxKeyF);
        fceNKey = expTRSS2017Raw.(seriesName).fNavg(idxKeyF);    

        %idxKey=expTRSS2017.activeLengtheningData(idx).keyIndices(...
        %        fittingConfig.idxFvKey);
        %lceNKey = expTRSS2017.activeLengtheningData(idx).x(idxKey)/lceOptMdl;
        %fceNKey = expTRSS2017.activeLengtheningData(idx).y(idxKey); 

        fvCurve = ratFibrilModelsFitted(idx).curves.fiberForceVelocityCurve;
        falCurve = ratFibrilModelsFitted(idx).curves.activeForceLengthCurve;
        
        lceNV = expTRSS2017Raw.(seriesName).lN;
        %vceNVavg = (expTRSS2017Raw.(seriesName).lN(end) ...
        %        -expTRSS2017Raw.(seriesName).lN(1)) ...
        %        /(expTRSS2017Raw.(seriesName).time(end) ...
        %        -expTRSS2017Raw.(seriesName).time(1)); %
        %vceNV = ones(size(lceNV)).*vceNVavg;
        lpfFreqHz=simConfig.numericalDiffLowPassFilterFrequencyHz;
        [b,a]=butter(2,lpfFreqHz/(0.5*expTRSS2017Raw.sampleFrequencyHz),'low');
        vceNVnum = calcCentralDifferenceDataSeries(...
                    expTRSS2017Raw.(seriesName).time,...
                    filtfilt(b,a,expTRSS2017Raw.(seriesName).lN));
        vceNVavg = mean(vceNVnum);
        vceNV = ones(size(lceNV)).*vceNVavg;
        %lceNV = benchRecordFitted.normFiberLength(:,idx);
        %vceNV = benchRecordFitted.normFiberVelocity(:,idx);



        fvNV    = zeros(size(lceNV));
        falNV   = zeros(size(lceNV));
        for i=1:1:length(lceNV)
            falNV(i,1)=calcBezierYFcnXDerivative(lceNV(i,1),falCurve,0);
            fvNV(i,1)=calcBezierYFcnXDerivative(vceNV(i,1),fvCurve,0);
        end
        fxeNV = fvNV.*falNV;

        txtName = seriesName;
        %i0=strfind(txtName,'Exp.');
        %txtName(1,i0:4)='Sim.';


        idxValid = find(lceNV >= lceNKey);

        hdlVis='off';
        %if(idx==1)
        %    hdlVis='on';                
        %end
        
        if(addErrorText)
            text(lceNV(idxValid(1,1)),...
                 fxeNV(idxValid(1,1)),...
                 sprintf('%1.3f',fitInfo.fv.yErr(1,idx)),...
                 'HorizontalAlignment','left',...
                 'VerticalAlignment','top',...
                 'FontSize',8);
            hold on;
        end

        xlim([pubPlotOptions.lceNMin,pubPlotOptions.lceNMax]);

        box off;


    subplot('Position',reshape(plotConfig.subPlotPanel(3,1,:),1,4));   
    subplotPosition = reshape(plotConfig.subPlotPanel(3,1,:),1,4);

        seriesName = expTRSS2017Raw.trials{idx};
    
        plot(expTRSS2017Raw.(seriesName).lN(idxKeyF0),...
             expTRSS2017Raw.(seriesName).fNavg(idxKeyF0),...
             'o','Color',[0,0,0],...
             'MarkerSize',3,...
             'HandleVisibility','off');
        hold on;

        idxKeyF = expTRSS2017Raw.keyIndices.(seriesName)(...
                         fittingConfig.idxFvKey);        
        lceNKey = expTRSS2017Raw.(seriesName).lN(idxKeyF);
        fceNKey = expTRSS2017Raw.(seriesName).fNavg(idxKeyF);

        %idxKey=expTRSS2017.activeLengtheningData(idx).keyIndices(...
        %        fittingConfig.idxFvKey);
        %lceNKey = expTRSS2017.activeLengtheningData(idx).x(idxKey)/lceOptMdl;
        %fceNKey = expTRSS2017.activeLengtheningData(idx).y(idxKey);           
              
        lceNExp = expTRSS2017Raw.(seriesName).lN;
        [lceNExpU,iu] = unique(lceNExp);
        fceNExp = expTRSS2017Raw.(seriesName).fNavg;
        fceNExpU = fceNExp(iu);

        %lceNExp = expTRSS2017.activeLengtheningData(idx).x ./ lceOptMdl;
        %[lceNExpU,iu] = unique(lceNExp);
        %fceNExp = expTRSS2017.activeLengtheningData(idx).y;
        %fceNExpU = fceNExp(iu);

        [lceNVU,iU]=unique(lceNV); 
        titinAnalysis(idx).lceN = lceNVU;
        titinAnalysis(idx).fceN = interp1(lceNExpU,fceNExpU,lceNVU,'linear');

        fxeNU=fxeNV(iU);

        idxZeroTitin = find(titinAnalysis(idx).lceN <= lceNKey);  
        titinAnalysis(idx).fxeN = interp1(lceNVU,fxeNU,titinAnalysis(idx).lceN);
        titinAnalysis(idx).f2N  = titinAnalysis(idx).fceN-titinAnalysis(idx).fxeN;
        titinAnalysis(idx).f2N(idxZeroTitin)=0;
        titinAnalysis(idx).f2N(titinAnalysis(idx).f2N<=0)=0;

        hVis='off';
        %if(idx==1)
        %    hVis='on';
        %end
        plot(titinAnalysis(idx).lceN, ...
             titinAnalysis(idx).f2N,...
             '-','Color',plotConfig.lineColors.calcTitinF(idx,:),...
             'LineWidth',lineWidthEst,...
             'DisplayName',['$$f^C_',num2str(idx),'$$'],...
             'HandleVisibility',hVis);
        hold on;
        text(titinAnalysis(idx).lceN(end),...
             titinAnalysis(idx).f2N(end),...
             sprintf('%s%i%s','$$f^{C}_{',idx,'}$$'),...
             'HorizontalAlignment','right',...
             'VerticalAlignment','baseline',...
             'FontSize',8,...
             'Color',plotConfig.lineColors.calcTitinF(idx,:));              
        hold on;

        if(idx==1)
          switch flag_legendType
            case 0
              dx = (pubPlotOptions.lceNMax-pubPlotOptions.lceNMin)*0.01;
              text(pubPlotOptions.lceNMin+dx,pubPlotOptions.fceNMax,...
                   sprintf('%s',...
                     ['\begin{tabular}{l l} ',...
                     '\multicolumn{2}{c}{TRSS2017 (Exp)} \\',...
                     'fiber force & titin force\\',...
                     ' $$f_1^{EXP}$$ & $$f_1^{C}$$ \\',...
                     ' $$f_2^{EXP}$$ & $$f_2^{C}$$ \\',...
                     '$$f_3^{EXP}$$ & $$f_3^{C}$$',...
                     ' \end{tabular}']),...
                   'HorizontalAlignment','left',...
                   'VerticalAlignment','top',...
                   'FontSize',8);
              hold on;
            case 1
              dx = (pubPlotOptions.lceNMax-pubPlotOptions.lceNMin)*0.01;
              text(pubPlotOptions.lceNMin+dx,pubPlotOptions.fceNMax,...
                   sprintf('%s\n%s',...
                     'TRSS2017',...
                     ['\begin{tabular}{l l l l}',...
                      'fiber & $$f_1^{EXP}$$ & $$f_2^{EXP}$$ & $$f_3^{EXP}$$\\',...
                      'titin & $$f_1^{C}$$ & $$f_2^{C}$$ & $$f_3^{C}$$\\',...
                      '\end{tabular}']),...
                   'HorizontalAlignment','left',...
                   'VerticalAlignment','top',...
                   'FontSize',8);
              hold on;               
          end
        end
        box off;
        xlim([pubPlotOptions.lceNMin,pubPlotOptions.lceNMax]);
        ylim([0,pubPlotOptions.fceNMax]);

        xlabel('Norm. Length ($$\ell/\ell_o^M$$)');
        ylabel('Norm. Force ($$f / f_o^M$$)');
        %title({'Experimental, simulated, and estimated','crossbridge and titin forces'});
        title({[subplotIds{1},...
               ' Fitted $$f^L(\tilde{\ell}^M),\,\&\,f^V(\tilde{\ell}^M)$$ and'],...
               'estimated titin forces'},...
               'HorizontalAlignment','center');




            

    subplot('Position',reshape(plotConfig.subPlotPanel(3,2,:),1,4));  
    subplotPosition = reshape(plotConfig.subPlotPanel(3,2,:),1,4);

        idxKValid = find(titinAnalysis(idx).f2N >...
                    pubPlotOptions.stiffnessLowerForceBound);

        xSpan = max(titinAnalysis(idx).lceN)-min(titinAnalysis(idx).lceN);
        [sp,f2NS,rho] = spaps(...
            titinAnalysis(idx).lceN(idxKValid),...
            titinAnalysis(idx).f2N(idxKValid),1e-6);

        f2NSFit = fnval(sp,titinAnalysis(idx).lceN(idxKValid));
        titinAnalysis(idx).f2NS=titinAnalysis(idx).f2N;
        titinAnalysis(idx).f2NS(idxKValid)=f2NSFit;

        titinAnalysis(idx).k2N = ...
            calcCentralDifferenceDataSeries(...
                titinAnalysis(idx).lceN,...
                titinAnalysis(idx).f2N);

        titinAnalysis(idx).k2NS = ...
            calcCentralDifferenceDataSeries(...
                titinAnalysis(idx).lceN,...
                titinAnalysis(idx).f2NS);
        lceNSpan = max(titinAnalysis(idx).lceN)...
                  -min(titinAnalysis(idx).lceN);

        hVis='off';
        %if(idx==1)
        %    hVis='on';
        %end

        plot(titinAnalysis(idx).lceN-titinAnalysis(idx).lceN(1,1), ...
             titinAnalysis(idx).f2N,...
             '-','Color',plotConfig.lineColors.calcTitinF(idx,:),...
             'LineWidth',lineWidthEst,...
             'DisplayName',...
             sprintf('%s',['$$f^{C}_{',num2str(idx),'}$$']),...
             'HandleVisibility',hVis);
        hold on;
        text(titinAnalysis(idx).lceN(end)-titinAnalysis(idx).lceN(1,1),...
             titinAnalysis(idx).f2N(end),...
             sprintf('%s%i%s','$$f^{C}_{',idx,'}$$'),...
             'HorizontalAlignment','right',...
             'VerticalAlignment','baseline',...
             'FontSize',8);
        hold on;

        if(idx==1)
          switch flag_legendType
            case 0
              dx = (lceNSpan)*0.01;
              dy = pubPlotOptions.fceNMax*0.1;
              text(dx,pubPlotOptions.fceNMax,...
                   sprintf('%s',...
                     ['\begin{tabular}{l} ',...
                     'TRSS2017 (Exp) \\',...
                     'titin force\\',...
                     '$$f_1^{C}$$ \\',...
                     '$$f_2^{C}$$ \\',...
                     '$$f_3^{C}$$',...
                     ' \end{tabular}']),...
                   'HorizontalAlignment','left',...
                   'VerticalAlignment','top',...
                   'FontSize',8);
              hold on;
            case 1
              dx = (lceNSpan)*0.01;
              dy = pubPlotOptions.fceNMax*0.1;              
              text(dx,pubPlotOptions.fceNMax,...
                   sprintf('%s\n%s',...
                     'TRSS2017',...
                     ['\begin{tabular}{l l l l}',...
                      'titin & $$f_1^{C}$$ & $$f_2^{C}$$ & $$f_3^{C}$$\\',...
                      '\end{tabular}']),...
                   'HorizontalAlignment','left',...
                   'VerticalAlignment','top',...
                   'FontSize',8);
              hold on; 

          end
        end

        box off;

        xlabel('$$\Delta$$ Norm. Length $$(\ell - \ell_i)/\ell_o^M$$');
        ylabel('Norm. Force ($$f/f_o^M$$)');
        title({[subplotIds{2},' Titin''s active force--'],...
              'length-change relation'},...
              'HorizontalAlignment','center');  
        
        xlim([0,lceNSpan]);
        ylim([0,pubPlotOptions.fceNMax]);        
%         if(idx==3)
%             [lgdH, lgdIcons, lgdPlots, lgdTxt]=...
%                 legend('Location','northwest','FontSize',6*(9/11.7));
%             legend boxoff;
%             lgdH = adjustLegendProperties(lgdH);          
%             lgdH.Position(1)=subplotPosition(1)+1.25*subplotPosition(3);
%         end

end

%
% Generate plots that compare the simulation results to the experiments
%

curveFitted = ratFibrilModelsFitted(1).curves.activeForceLengthCurve;    
sampleFlNFitted=calcBezierYFcnXCurveSampleVector(...
                curveFitted,100,curveFitted.xEnd);


vN = benchRecordFitted.normFiberVelocity(end,1);
fvN = calcBezierYFcnXDerivative(vN, ...
    ratFibrilModelsFitted(1).curves.fiberForceVelocityCalibratedCurve,...
    0);

subplot('Position',reshape(plotConfig.subPlotPanel(5,1,:),1,4)); 
subplotPosition = reshape(plotConfig.subPlotPanel(5,1,:),1,4);
    fill([min(sampleFlNFitted.x);...
          max(sampleFlNFitted.x);...
          fliplr(sampleFlNFitted.x')'],...
          [0;...
           0;...
          fliplr((sampleFlNFitted.y.*fvN)')'],...
          [1,1,1].*0.9,'EdgeAlpha',0,...
          'HandleVisibility','off');
    hold on; 

    fill([min(sampleFlNFitted.x);...
          max(sampleFlNFitted.x);...
          fliplr(sampleFlNFitted.x')'],...
          [0;...
           0;...
          fliplr(sampleFlNFitted.y')'],...
          [1,1,1].*0.8,'EdgeAlpha',0,...
          'HandleVisibility','off');
    hold on; 

    text(xP,yP,'$$f^{L}(\ell^M)$$',...
        'HorizontalAlignment','right',...
        'VerticalAlignment','top',...
        'rotation',-30,...
        'FontSize',8);
    hold on;

    text(xP,yP*fvN,'$$f^{L}(\ell^M)f^{V}(v^M)$$',...
        'HorizontalAlignment','right',...
        'VerticalAlignment','bottom',...
        'rotation',-35,...
        'FontSize',8);
    hold on;


for idx=simConfig.trials     
    hdlVis='off';
    if(idx==1)
       hdlVis = 'on';
    end

    seriesName = expTRSS2017Raw.trials{idx};
    stdAreaX = [expTRSS2017Raw.(seriesName).lN; ...
               fliplr(expTRSS2017Raw.(seriesName).lN')'];
    stdAreaY = [(expTRSS2017Raw.(seriesName).fNavg...
                  -expTRSS2017Raw.(seriesName).fNstd); ...
               fliplr((expTRSS2017Raw.(seriesName).fNavg...
                  +expTRSS2017Raw.(seriesName).fNstd)')'];

    stdAreaColor = plotConfig.lineColors.exp(idx,:).*0.5 + ([1,1,1].*0.75).*0.5;
    fill(stdAreaX,stdAreaY,stdAreaColor,...
         'EdgeColor','none',...
         'FaceAlpha',0.5); 
    hold on;

    plot(expTRSS2017Raw.(seriesName).lN,...
         expTRSS2017Raw.(seriesName).fNavg,...
         '-','Color',plotConfig.lineColors.exp(idx,:),...
         'LineWidth',lineWidthExp,...
         'DisplayName','TRSS2017',...
         'HandleVisibility',hdlVis);
    hold on;     
    text(expTRSS2017Raw.(seriesName).lN(end),...
         expTRSS2017Raw.(seriesName).fNavg(end)...
          +expTRSS2017Raw.(seriesName).fNstd(end),...
         sprintf('%s%i%s','$$f^{EXP}_{',idx,'}$$'),...
         'HorizontalAlignment','right',...
         'VerticalAlignment','bottom',...
         'FontSize',8,...
         'Color',plotConfig.lineColors.exp(idx,:));
    hold on;

%     plot(expTRSS2017.activeLengtheningData(idx).x./lceOptMdl,...
%          expTRSS2017.activeLengtheningData(idx).y,...
%          '-','Color',plotConfig.lineColors.exp(idx,:),...
%          'LineWidth',lineWidthExp,...
%          'DisplayName','TRSS2017',...
%          'HandleVisibility',hdlVis);
%     hold on; 

%     text(expTRSS2017.activeLengtheningData(idx).x(end)./lceOptMdl,...
%          expTRSS2017.activeLengtheningData(idx).y(end),...
%          sprintf('%s%i%s','$$f^{EXP}_{',idx,'}$$'),...
%          'HorizontalAlignment','right',...
%          'VerticalAlignment','bottom',...
%          'FontSize',8,...
%          'Color',plotConfig.lineColors.exp(idx,:));
%     hold on;

    ffit='';
    if(~isempty(fitInfo.QToF.x))
        ffit = 'QToF';        
    end
    if(~isempty(fitInfo.QToK.x))
        ffit = 'QToK';        
    end    
    if(~isempty(fitInfo.f1HNPreload.x))
        ffit = 'f1HNPreload';        
    end
    if(~isempty(fitInfo.l1HNOffset.x))
        ffit = 'l1HNOffset';        
    end    

    xErr = fitInfo.(ffit).x(end,idx)./lceOptMdl;
    yErr = (fitInfo.(ffit).y(end,idx) + fitInfo.(ffit).yFit(end,idx)).*0.5;

    rmseTrial = sqrt(mean(fitInfo.(ffit).yErr(:,idx).^2));

    hVis='off';
    %if(idx==1)
    %  hVis='on';
    %end
    plot(titinAnalysis(idx).lceN, ...
         titinAnalysis(idx).f2N,...
         '-','Color',plotConfig.lineColors.calcTitinF(idx,:),...
         'LineWidth',lineWidthEst,...
         'DisplayName','Titin (Est)',...         
         'HandleVisibility',hVis);   

    text(titinAnalysis(idx).lceN(end),...
         titinAnalysis(idx).f2N(end),...
         sprintf('%s%i%s','$$f^{C}_{',idx,'}$$'),...
         'HorizontalAlignment','right',...
         'VerticalAlignment','bottom',...
         'FontSize',8,...
         'Color',plotConfig.lineColors.calcTitinF(idx,:));
    hold on;    


   plot( benchRecordFitted.normFiberLength(:,idx), ...
         benchRecordFitted.normFiberForce(:,idx),...
         '-','Color',[1,1,1],...
         'LineWidth',lineWidthSim*2.5);
   hold on;    
   plot( benchRecordFitted.normFiberLength(:,idx), ...
         benchRecordFitted.normFiberForce(:,idx),...
         '-','Color',plotConfig.lineColors.simF(idx,:),...
         'LineWidth',lineWidthSim,...         
         'DisplayName',['$$f^{M}_',num2str(idx),'(\tilde{\ell}^M)$$ (Sim)'],...
         'HandleVisibility',hVis);
   hold on;

   text(benchRecordFitted.normFiberLength(end,idx),...
        benchRecordFitted.normFiberForce(end,idx),...
         sprintf('%s%i%s','$$f^{M}_{',idx,'}$$'),...
         'HorizontalAlignment','left',...
         'VerticalAlignment','bottom',...
         'FontSize',8,...
         'Color',plotConfig.lineColors.simF(idx,:));
    hold on;   

   plot( benchRecordFitted.normFiberLength(:,idx), ...
         benchRecordFitted.normDistalTitinForce(:,idx),...
         '-','Color',[1,1,1],...
         'LineWidth',lineWidthSim*2.5);
   hold on;    
   plot( benchRecordFitted.normFiberLength(:,idx), ...
         benchRecordFitted.normDistalTitinForce(:,idx),...
         '-','Color',plotConfig.lineColors.simTitinF(idx,:),...
         'LineWidth',lineWidthSim,...         
         'DisplayName',['$$f^{2}_',num2str(idx),'(\tilde{\ell}^M)$$ (Sim)'],...
         'HandleVisibility',hVis);
   hold on;

   text(benchRecordFitted.normFiberLength(end,idx),...
        benchRecordFitted.normDistalTitinForce(end,idx),...
         sprintf('%s%i%s','$$f^{2}_{',idx,'}$$'),...
         'HorizontalAlignment','left',...
         'VerticalAlignment','bottom',...
         'FontSize',8,...
         'Color',plotConfig.lineColors.simTitinF(idx,:));
    hold on;     

   if(idx==1 && simConfig.fitToIndividualTrials==1)
       %%
       % Annotate the largest error between the fiber force and the data
       %%
        npts=100;
        x0 = benchRecordFitted.normFiberLength(1,idx);
        x1 = benchRecordFitted.normFiberLength(end,idx);
        xV = [0:(1/(npts-1)):1]' .*(x1-x0) + x0;

        [c,ia,ic] = unique(expTRSS2017Raw.(seriesName).lN);
        yV = interp1(expTRSS2017Raw.(seriesName).lN(ia),...
                     expTRSS2017Raw.(seriesName).fNavg(ia),...
                     xV);


%         [c,ia,ic] = unique(expTRSS2017.activeLengtheningData(idx).x);
%         yV = interp1(expTRSS2017.activeLengtheningData(idx).x(ia)./lceOptMdl,...
%                      expTRSS2017.activeLengtheningData(idx).y(ia),...
%                      xV);
        [c,ia,ic] = unique(benchRecordFitted.normFiberLength(:,idx));        
        yVFit = interp1(benchRecordFitted.normFiberLength(ia,idx),...
                       benchRecordFitted.normFiberForce(ia,idx),...
                       xV);
        [maxErrV,idxMaxErr] = max(abs(yV-yVFit));
        text(xV(idxMaxErr,1),yV(idxMaxErr,1)+0.1,...
             sprintf('%s%1.2f%s','$$\epsilon_{MAX}^{M}=',maxErrV,'$$'),...
             'HorizontalAlignment','right',...
             'FontSize',8);        
        hold on;
        plot([1,1].*xV(idxMaxErr,1),...
             [yVFit(idxMaxErr,1),yV(idxMaxErr,1)],...
             '-k',...
             'HandleVisibility','off');
        hold on;
        plot([1,1].*xV(idxMaxErr,1),...
             [yV(idxMaxErr,1),yVFit(idxMaxErr,1)],...
             '.k',...
             'HandleVisibility','off');
        hold on;

       %%
       % Annotate the largest error between the titin force and the data
       %%
        npts=100;
        x0 = benchRecordFitted.normFiberLength(1,idx);
        x1 = benchRecordFitted.normFiberLength(end,idx);
        xV = [0:(1/(npts-1)):1]' .*(x1-x0) + x0;
        [c,ia,ic] = unique(titinAnalysis(idx).lceN);
        yV = interp1(titinAnalysis(idx).lceN(ia),...
                     titinAnalysis(idx).f2N(ia),...
                     xV);
        [c,ia,ic] = unique(benchRecordFitted.normFiberLength(:,idx));        
        yVFit = interp1(benchRecordFitted.normFiberLength(ia,idx),...
                       benchRecordFitted.normDistalTitinForce(ia,idx),...
                       xV);
        [maxErrV,idxMaxErr] = max(abs(yV-yVFit));
        text(xV(idxMaxErr,1),yV(idxMaxErr,1)+0.1,...
             sprintf('%s%1.2f%s','$$\epsilon_{MAX}^{C}=',maxErrV,'$$'),...
             'HorizontalAlignment','right',...
             'FontSize',8);        
        hold on;
        plot([1,1].*xV(idxMaxErr,1),...
             [yVFit(idxMaxErr,1),yV(idxMaxErr,1)],...
             '-k',...
             'HandleVisibility','off');
        hold on;
        plot([1,1].*xV(idxMaxErr,1),...
             [yV(idxMaxErr,1),yVFit(idxMaxErr,1)],...
             '.k',...
             'HandleVisibility','off');

        
        
   end

end


dx = (pubPlotOptions.lceNMax-pubPlotOptions.lceNMin)*0.01;
dy = pubPlotOptions.fceNMax*0.1;

  switch flag_legendType
     case 0
       text(pubPlotOptions.lceNMin+0.5*dx,pubPlotOptions.fceNMax,...
             sprintf('%s',...
               ['\begin{tabular}{l l} ',...
               '\multicolumn{2}{c}{TRSS2017 (Exp)} \\',...
               'fiber & titin\\',...
               ' $$f_1^{EXP}$$ & $$f_1^{C}$$ \\',...
               ' $$f_2^{EXP}$$ & $$f_2^{C}$$ \\',...
               '$$f_3^{EXP}$$ & $$f_3^{C}$$',...
               ' \end{tabular}']),...
             'HorizontalAlignment','left',...
             'VerticalAlignment','top',...
             'FontSize',8);
       hold on;
       text(pubPlotOptions.lceNMin+dx*4.5,pubPlotOptions.fceNMax,...
             sprintf('%s',...
               ['\begin{tabular}{l l} ',...
               '\multicolumn{2}{c}{Simulation} \\',...
               'fiber & titin\\',...
               ' $$f_1^{M}$$ & $$f_1^{2}$$ \\',...
               ' $$f_2^{M}$$ & $$f_2^{2}$$ \\',...
               '$$f_3^{M}$$ & $$f_3^{2}$$',...
               ' \end{tabular}']),...
             'HorizontalAlignment','left',...
             'VerticalAlignment','top',...
             'FontSize',8);       
    case 1
        text(pubPlotOptions.lceNMin+dx,pubPlotOptions.fceNMax,...
             sprintf('%s\n%s',...
               'TRSS2017',...
               ['\begin{tabular}{l l l l}',...
                'fiber & $$f_1^{EXP}$$ & $$f_2^{EXP}$$ & $$f_3^{EXP}$$\\',...
                'titin & $$f_1^{C}$$ & $$f_2^{C}$$ & $$f_3^{C}$$\\',...
                '\end{tabular}']),...
             'HorizontalAlignment','left',...
             'VerticalAlignment','top',...
             'FontSize',8);
        hold on;   
        text(pubPlotOptions.lceNMin+dx,pubPlotOptions.fceNMax-1.5*dy,...
             sprintf('%s\n%s',...
               'Simulation',...
               ['\begin{tabular}{l l l l}',...
                'fiber & $$f_1^{M}$$ & $$f_2^{M}$$ & $$f_3^{M}$$\\',...
                'titin & $$f_1^{2}$$ & $$f_2^{2}$$ & $$f_3^{2}$$\\',...
                '\end{tabular}']),...
             'HorizontalAlignment','left',...
             'VerticalAlignment','top',...
             'FontSize',8);  
        hold on;
  end



box off;
xlim([pubPlotOptions.lceNMin,pubPlotOptions.lceNMax]);
ylim([0,pubPlotOptions.fceNMax]); 
xlabel('Norm. Length ($$\ell/\ell_o^M$$)');
ylabel('Norm. Length ($$f/f_o^M$$)');

% [lgdH, lgdIcons, lgdPlots, lgdTxt]=...
%     legend('Location','northwest','FontSize',6*(9/11.7));
% legend boxoff;
% lgdH = adjustLegendProperties(lgdH);
% lgdH.Position(1)=subplotPosition(1)-2*lgdH.Position(3);

% [lgdH, lgdIcons, lgdPlots, lgdTxt,xDataOrig,xDataUpd] = ...
% scaleLegendLines(0.5,lgdH, lgdIcons, lgdPlots, lgdTxt);

title({[subplotIds{1},...
        ' Fitted $$f^L(\tilde{\ell}^M),\,\&\,f^V(\tilde{\ell}^M)$$ and'],...
       'estimated titin forces $$f^{C}(\tilde{\ell}^{M})$$'},...
       'HorizontalAlignment','center');


subplot('Position',reshape(plotConfig.subPlotPanel(5,2,:),1,4));     
subplotPosition = reshape(plotConfig.subPlotPanel(5,2,:),1,4);

    for idx=simConfig.trials
        hVis='off';
        %if(idx==1)
        %   hVis='on';
        %end

        plot(titinAnalysis(idx).lceN-titinAnalysis(idx).lceN(1,1), ...
             titinAnalysis(idx).f2N,...
             '-','Color',plotConfig.lineColors.calcTitinF(idx,:),...
             'LineWidth',lineWidthEst,...             
             'DisplayName',...
             sprintf('%s%s',['$$f^{C}_',num2str(idx),'(\tilde{\ell}^M)'],'$$ (Est)'),...
             'HandleVisibility',hVis);
        hold on;

       text(titinAnalysis(idx).lceN(end)-titinAnalysis(idx).lceN(1,1),...
            titinAnalysis(idx).f2N(end),...
             sprintf('%s%i%s','$$f^{C}_{',idx,'}$$'),...
             'HorizontalAlignment','right',...
             'VerticalAlignment','bottom',...
             'FontSize',8,...
             'Color',plotConfig.lineColors.calcTitinF(idx,:));
        hold on;         

    end

    for idx=simConfig.trials

        hVis='off';
        %if(idx==1)
        %    hVis='on';
        %end
       
       plot( benchRecordFitted.normFiberLength(:,idx)...
              -benchRecordFitted.normFiberLength(1,idx), ...
             benchRecordFitted.normDistalTitinForce(:,idx),...
             '-','Color',[1,1,1],...
             'LineWidth',lineWidthSim*2.5);

       hold on;  
       plot( benchRecordFitted.normFiberLength(:,idx)...
              -benchRecordFitted.normFiberLength(1,idx), ...
             benchRecordFitted.normDistalTitinForce(:,idx),...
             '-','Color',plotConfig.lineColors.simTitinF(idx,:),...
             'LineWidth',lineWidthSim,...
             'DisplayName',sprintf('%s%s',['$$f^{2}_',num2str(idx),'(\tilde{\ell}^M)'],'$$ (Sim)' ),...
             'HandleVisibility',hVis);

       hold on;   

       text(benchRecordFitted.normFiberLength(end,idx)...
              -benchRecordFitted.normFiberLength(1,idx), ...
            benchRecordFitted.normDistalTitinForce(end,idx),...
             sprintf('%s%i%s','$$f^{2}_{',idx,'}$$'),...
             'HorizontalAlignment','left',...
             'VerticalAlignment','bottom',...
             'FontSize',8,...
             'Color',plotConfig.lineColors.simTitinF(idx,:));
        hold on;        

       lceNSpan = benchRecordFitted.normFiberLength(end,idx)...
                 -benchRecordFitted.normFiberLength(1,idx);
%        text(lceNSpan,...
%             benchRecordFitted.normDistalTitinForce(end,idx),...
%              sprintf('%1.1f%s',benchRecordFitted.normDistalTitinForce(end,idx),'$$f_o^M$$'),...
%              'HorizontalAlignment','left',...
%              'VerticalAlignment','top',...
%              'FontSize',8);
%        hold on;

       %%
       % Annotate the largest error between the titin force and the data
       %%
      if(idx==1 && simConfig.fitToIndividualTrials==1)
        npts=100;
        x0 = 0;
        x1 = benchRecordFitted.normFiberLength(end,idx) ...
            -benchRecordFitted.normFiberLength(1,idx);
        xV = [0:(1/(npts-1)):1]' .*(x1-x0) + x0;
        [c,ia,ic] = unique(titinAnalysis(idx).lceN);
        yV = interp1(titinAnalysis(idx).lceN(ia)-titinAnalysis(idx).lceN(ia(1)),...
                     titinAnalysis(idx).f2N(ia),...
                     xV);
        [c,ia,ic] = unique(benchRecordFitted.normFiberLength(:,idx));        
        yVFit = interp1(benchRecordFitted.normFiberLength(ia,idx) ...
                       -benchRecordFitted.normFiberLength(ia(1),idx),...
                       benchRecordFitted.normDistalTitinForce(ia,idx),...
                       xV);
        [maxErrV,idxMaxErr] = max(abs(yV-yVFit));
        text(xV(idxMaxErr,1)+0.075,yVFit(idxMaxErr,1),...
             sprintf('%s%1.2f%s','$$\epsilon_{MAX}^{C}=',maxErrV,'$$'),...
             'HorizontalAlignment','left',...
             'VerticalAlignment','baseline',...
             'FontSize',8);        
        hold on;
        plot([(xV(idxMaxErr,1)+0.025),(xV(idxMaxErr,1)+0.075)],...
             [yVFit(idxMaxErr,1),yVFit(idxMaxErr,1)],...
             '-k',...
             'HandleVisibility','off');
        hold on;
        
        plot([1,1].*xV(idxMaxErr,1),...
             [yVFit(idxMaxErr,1),yV(idxMaxErr,1)],...
             '-k',...
             'HandleVisibility','off');
        hold on;
        plot([1,1].*xV(idxMaxErr,1),...
             [yV(idxMaxErr,1),yVFit(idxMaxErr,1)],...
             '.k',...
             'HandleVisibility','off');
      end

    end    

dx = (lceNSpan)*0.01;
dy = pubPlotOptions.fceNMax*0.1;

switch flag_legendType
  case 0
    text(0.5*dx,pubPlotOptions.fceNMax,...
         sprintf('%s',...
           ['\begin{tabular}{l} ',...
           'TRSS2017 (Exp) \\',...
           'titin\\',...
           '$$f_1^{C}$$ \\',...
           '$$f_2^{C}$$ \\',...
           '$$f_3^{C}$$',...
           ' \end{tabular}']),...
         'HorizontalAlignment','left',...
         'VerticalAlignment','top',...
         'FontSize',8);
    hold on;
    text(dx*4.5,pubPlotOptions.fceNMax,...
         sprintf('%s',...
           ['\begin{tabular}{l} ',...
           'Simulation \\',...
           'titin\\',...
           '$$f_1^{2}$$ \\',...
           '$$f_2^{2}$$ \\',...
           '$$f_3^{2}$$',...
           ' \end{tabular}']),...
         'HorizontalAlignment','left',...
         'VerticalAlignment','top',...
         'FontSize',8);
     hold on;
  case 1
      dx = (lceNSpan)*0.1;     
      text(dx,pubPlotOptions.fceNMax,...
           sprintf('%s\n%s',...
             'TRSS2017',...
             ['\begin{tabular}{l l l l}',...
              'titin & $$f_1^{C}$$ & $$f_2^{C}$$ & $$f_3^{C}$$\\',...
              '\end{tabular}']),...
           'HorizontalAlignment','left',...
           'VerticalAlignment','top',...
           'FontSize',8);
      hold on;   
      text(dx,pubPlotOptions.fceNMax-dy,...
           sprintf('%s\n%s',...
             'Simulation',...
             ['\begin{tabular}{l l l l}',...
              'titin & $$f_1^{2}$$ & $$f_2^{2}$$ & $$f_3^{2}$$\\',...
              '\end{tabular}']),...
           'HorizontalAlignment','left',...
           'VerticalAlignment','top',...
           'FontSize',8);  
      hold on;      
end

box off;
xlim([0,lceNSpan]);
ylim([0,pubPlotOptions.fceNMax]);

xlabel('$$\Delta$$ Norm. Length $$(\ell - \ell_i)/\ell_o^M$$');
ylabel('Norm. Force ($$f/f_o^M$$)');
title({[subplotIds{2},' Titin''s active force--'],'length-change relation'},...
      'HorizontalAlignment','center');  

% [lgdH, lgdIcons, lgdPlots, lgdTxt]=...
%     legend('Location','northwest','FontSize',6*(9/11.7));
% legend boxoff;
% lgdH = adjustLegendProperties(lgdH);
% lgdH.Position(1)=subplotPosition(1)+1.25*subplotPosition(3);





