%%
% SPDX-FileCopyrightText: 2023 Matthew Millard <millard.matthew@gmail.com>
%
% SPDX-License-Identifier: MIT
%
% If you use this code in your work please cite the pre-print of this paper
% or the most recent peer-reviewed version of this paper:
%
%    Matthew Millard, David W. Franklin, Walter Herzog. 
%    A three filament mechanistic model of musculotendon force and impedance. 
%    bioRxiv 2023.03.27.534347; doi: https://doi.org/10.1101/2023.03.27.534347 
%
%%

function [success] = plotRatMuscleTitinFittingCurvesTRSS2017_Pub( ...
                      muscleModel,...
                      muscleModel_manual,...
                      humanSoleusMuscle,...                      
                      activeForceLengthCurveAnnotationPoints,...
                      fittingData,...
                      activeForceLengthData,...
                      passiveForceLengthData,...   
                      normFiberLengthAtOneNormPassiveForce,...
                      trialId,...
                      previousFilePathAndName,...
                      filePathAndName,...
                      projectFolders)

%%
% 
%%
   assert(humanSoleusMuscle.sarcomere.titinModelType ...
          == muscleModel.sarcomere.titinModelType,...
          ['Error: the muscleModel and humanSoleusModel need to have' ...
          'the same titinModelType']);

scaleLength = muscleModel.musculotendon.optimalFiberLength;   
scaleVelocity = muscleModel.musculotendon.maximumNormalizedFiberVelocity;
%%
% Series colors
%%
csVib = getPaulTolColourSchemes('vibrant');

n=0.75;

lineColors.orig(1,:)=[0,0,0];
lineColors.orig(2,:)=[44,133,229]./255;
lineColors.orig(3,:)=[63,181,175]./255;

for i=1:1:3
    n0 = 0.25*(i-1);
    n1 = n0;%n0+0.25;
    lineColors.exp(i,:)         = [0,0,0].*(1-n1)+[1,1,1].*n1;  
    lineColors.simXE(i,:)       = csVib.grey;
    lineColors.calcTitinF(i,:)  = lineColors.exp(i,:);%csVib.blue.*(1-n0)+[1,1,1].*n0;
    lineColors.calcTitinK(i,:)  = lineColors.exp(i,:);%lineColors.calcTitinF(i,:);
    lineColors.simF(i,:)        = csVib.blue.*(1-n0)+[1,1,1].*n0;%csVib.red.*(1-n0)+[1,1,1].*n0;
    lineColors.simTitinF(i,:)   = csVib.red.*(1-n0)+[1,1,1].*n0;%csVib.magenta.*(1-n0)+[1,1,1].*n0;
    lineColors.simTitinPassive(i,:)   = csVib.magenta.*(1-n0)+[1,1,1].*n0;%csVib.magenta.*(1-n0)+[1,1,1].*n0;
    lineColors.simTitinActive(i,:)     = csVib.red.*(1-n0)+[1,1,1].*n0;%csVib.magenta.*(1-n0)+[1,1,1].*n0;
    
    lineColors.simTitinK(i,:)   = lineColors.simTitinF(i,:);
end



%   if(trialId==0)
%     n=0;
%   else
%     n = 1-((trialId-1)/2);
%   end

  colorTitinActive  = [0,0,0];%csVib.red.*0.75;
  colorTitinPassive = [0,0,0];%csVib.blue.*0.75;
  colorTitinLight   = colorTitinActive.*0.1 + [1,1,1].*0.9;  

  colorIgp             = csVib.red;%[1,0,0].*n + ([1,0,0].*0.25).*(1-n);
  colorPEVK            = csVib.blue;%[0.5,0,0].*n + ([0.5,0,0].*0.25).*(1-n);
  colorIgd             = csVib.magenta; %[0.25,0,0].*n + ([0.25,0,0].*0.25).*(1-n);
  colorDistal          = colorTitinActive;
  colorProximal        = colorDistal.*0.5;


%%
%Plot configuration
%%
  flag_fibrilModel = 0;
  if(muscleModel.sarcomere.extraCellularMatrixPassiveForceFraction==0)
    flag_fibrilModel=1;
  end


  fig_pubTitinCurves=figure;

  numberOfHorizontalPlotColumns = 2;
  numberOfVerticalPlotRows      = 2;

  pageWidth         = 21;
  pageHeight        = 29.7;
  plotWidth         = 5;
  plotHeight        = 5;
  
  if(~isempty(muscleModel_manual))
    plotWidth         = 6.5;
    plotHeight        = 6.5;    
  end
  plotHorizMarginCm = 2;
  plotVertMarginCm  = 2.;

  flag_usingOctave  = 0;



  plotConfigGeneric;  
    
  lineColorTendon = [0,0,0];
  lineWidthTendon = 1;
  
  labelRotationOffset = -10;
  
  plotProps(4) = struct('xlim',[],'ylim',[],'domain',[],...
                     'xticks',[],'xticklabels',{''},...
                     'yticks',[],'yticklabels',{''},...
                     'lineColor',[],'lineWidth',[],...
                     'xlabel','', 'ylabel','','title','');


  %%
  % Data
  %%
  fileTrombitas1998Figure5 = fullfile(projectFolders.experiments_TGFG1998,...
      'Trombitas1998_Figure5.csv');

  dataTrombitas1998Figure5 = loadDigitizedData(fileTrombitas1998Figure5,...
                        'Sarcomere Length','PEVK Width (um)',...
                        {'a','b'},'Trombitas 1998 Figure 5');  
                      
  fileTrombitas1998Figure6 = fullfile(projectFolders.experiments_TGFG1998, ...
      'Trombitas1998_Figure6.csv');
  dataTrombitas1998Figure6 = loadDigitizedData(fileTrombitas1998Figure6,...
                        'Sarcomere Length','PEVK Width (um)',...
                        {'a'},'Trombitas 1998 Figure 6');  

  
  %%
  % PE: ECM + titin force-length
  %%
  idxTrombitasFigure5_A = 1;
  idx   =idxTrombitasFigure5_A;
  
  lopt = muscleModel.sarcomere.optimalSarcomereLength;
  loptHuman=humanSoleusMuscle.sarcomere.optimalSarcomereLength;%um
  %from createFiberActiveForceLength.m
  plotProps(idx).xlim = [2.0,4.75];  
  plotProps(idx).ylim = [0,1.5];
  
  plotProps(idx).domain      = plotProps(idx).xlim + [-0.01,0.01];
  plotProps(idx).xticks      = [2.25:0.5:4.75];
  plotProps(idx).xticklabels = cell(1,length(plotProps(idx).xticks),1);
  for z=1:1:length(plotProps(idx).xticks)
    plotProps(idx).xticklabels{z} = num2str(round(plotProps(idx).xticks(1,z),3));
  end
  plotProps(idx).yticks      = [0:0.2:1.2];
  plotProps(idx).yticklabels = cell(1,length(plotProps(idx).yticks));
  for z=1:1:length(plotProps(idx).yticks)
    plotProps(idx).yticklabels{z} = num2str(round(plotProps(idx).yticks(1,z),3));
  end
  
  plotProps(idx).lineColor   = [0,0,0];
  plotProps(idx).lineWidth   = 0.5;
  plotProps(idx).xlabel = 'Sarcomere Length ($$\mu m$$)';
  plotProps(idx).ylabel = 'epitope to Z-line ($$\mu m$$)';
  plotProps(idx).title  = {'A. Human titin seg. elongation','vs. Trombitas et al. 1998 Fig. 5'};  
    
  %%
  % PE: ECM + titin force-length
  %%
  idxTrombitasFigure5_B = 2;
  idx   =idxTrombitasFigure5_B;
  
  lopt = muscleModel.sarcomere.optimalSarcomereLength;
  loptHuman=humanSoleusMuscle.sarcomere.optimalSarcomereLength;%um
  %from createFiberActiveForceLength.m
  plotProps(idx).xlim = [2.00,4.75];  
  plotProps(idx).ylim = [0,1.5];
  
  plotProps(idx).domain      = plotProps(idx).xlim + [-0.01,0.01];
  plotProps(idx).xticks      = [2.25:0.5:4.75];
  plotProps(idx).xticklabels = cell(1,length(plotProps(idx).xticks),1);
  for z=1:1:length(plotProps(idx).xticks)
    plotProps(idx).xticklabels{z} = num2str(round(plotProps(idx).xticks(1,z),3));
  end
  plotProps(idx).yticks      = [0:0.2:1.2];
  plotProps(idx).yticklabels = cell(1,length(plotProps(idx).yticks));
  for z=1:1:length(plotProps(idx).yticks)
    plotProps(idx).yticklabels{z} = num2str(round(plotProps(idx).yticks(1,z),3));
  end
  
  plotProps(idx).lineColor   = [0,0,0];
  plotProps(idx).lineWidth   = 0.5;
  plotProps(idx).xlabel = 'Sarcomere Length ($$\mu m$$)';
  plotProps(idx).ylabel = 'epitope to Z-line ($$\mu m$$)';
  plotProps(idx).title  = {'B. Rat \& human titin seg. elongation','vs. Trombitas et al. 1998 Fig. 5'};  
  
    
   
  %%
  % PE: ECM + titin force-length
  %%
  idxPeEcmTitinLength = 3;
  idx         =idxPeEcmTitinLength;
  

  %from createFiberActiveForceLength.m
  plotProps(idx).xlim = ...
    (muscleModel.curves.fiberForceLengthCurve.xEnd +[-0.02,0.02]);
  
  plotProps(idx).ylim = [0,1.0]+[-0.01,0.01];
  plotProps(idx).domain      = plotProps(idx).xlim + [-0.01,0.01];
  plotProps(idx).xticks      = ...
      [round(muscleModel.curves.fiberForceLengthCurve.xEnd(1,1),2),...                                
        1,...
        round(muscleModel.curves.fiberForceLengthCurve.xEnd(1,2),2)];

  plotProps(idx).xticklabels = ...
                              {num2str(plotProps(idx).xticks(1,1)),...
                                num2str(plotProps(idx).xticks(1,2)),...
                                num2str(plotProps(idx).xticks(1,3))};
                              
  plotProps(idx).yticks      = [0,1];
  plotProps(idx).yticklabels = {'0','$$f^M_o$$'};
  plotProps(idx).lineColor   = [0,0,0];
  plotProps(idx).lineWidth   = 0.5;
  %if(abs(scaleVelocity-1)<1e-3)  
      plotProps(idx).xlabel = 'Normalized Length ($$\ell/\ell^{M}_{o}$$)';
  %else
  %    plotProps(idx).xlabel = 'Length ($$\mu$$m)';
  %end
  plotProps(idx).ylabel = 'Normalized Force ($$f/f^{M}_{o}$$)';
  plotProps(idx).title  = {'C. Rat EDL passive force-length','relation (full sarcomere)'};  
  

  

  %from createFiberActiveForceLength.m
  
  lambdaECM = muscleModel.sarcomere.extraCellularMatrixPassiveForceFraction;  

%Structurally distinct segments of titin
  
  ligpZero  = muscleModel.curves.forceLengthIgPTitinCurve.xEnd(1,1);
  lpevkZero = muscleModel.curves.forceLengthPevkTitinCurve.xEnd(1,1);
  
  
  ligpOpt  = muscleModel.sarcomere.IGPNormLengthAtOptimalFiberLength;
  lpevkOpt = muscleModel.sarcomere.PEVKNormLengthAtOptimalFiberLength;  
  ligdOpt  = muscleModel.sarcomere.IGDFreeNormLengthAtOptimalFiberLength;

  ligpFiso  = calcBezierYFcnXDerivative((1-lambdaECM),...
              muscleModel.curves.('forceLengthIgPTitinInverseCurve'),...
              0);
            
  lpevkFiso = calcBezierYFcnXDerivative((1-lambdaECM),...
              muscleModel.curves.('forceLengthPevkTitinInverseCurve'),...
              0);
  
  normLengthZToT12 = ...
    muscleModel.sarcomere.ZLineToT12NormLengthAtOptimalFiberLength;   
  
  normLengthIgdFixed = ...
    muscleModel.sarcomere.IGDFixedNormLengthAtOptimalFiberLength;    
  
  ltitinOpt = normLengthZToT12+normLengthIgdFixed + ligpOpt+lpevkOpt;
  ltitinFiso = normLengthZToT12+normLengthIgdFixed + ligpFiso+lpevkFiso;
    
%Segments of titin from the Z-line to the PEVK-actin attachment point and
%from the PEVK-actin attachment point to myosin:

normLengthProximalTitinAtOptimalFiberLengthHuman=0;
normLengthDistalTitinAtOptimalFiberLengthHuman=0;

normLengthProximalTitinAtOptimalFiberLengthAnimal=0;
normLengthDistalTitinAtOptimalFiberLengthAnimal=0;

assert(humanSoleusMuscle.sarcomere.titinModelType ...
      == muscleModel.sarcomere.titinModelType,...
      ['Error: the muscleModel and humanSoleusModel need to have' ...
      'the same titinModelType']);


if(muscleModel.sarcomere.titinModelType==0)

    %Input model
    n = muscleModel.sarcomere.normPevkToActinAttachmentPoint;
                          
    normLengthProximalTitinAtOptimalFiberLengthAnimal = ...
          muscleModel.sarcomere.IGPNormLengthAtOptimalFiberLength...
    + (n)*muscleModel.sarcomere.PEVKNormLengthAtOptimalFiberLength;

    normLengthDistalTitinAtOptimalFiberLengthAnimal = ...
        + (1-n)*muscleModel.sarcomere.PEVKNormLengthAtOptimalFiberLength ...
        + muscleModel.sarcomere.IGDFreeNormLengthAtOptimalFiberLength;
 
    %Human
    n = humanSoleusMuscle.sarcomere.normPevkToActinAttachmentPoint;
                          
    normLengthProximalTitinAtOptimalFiberLengthHuman = ...
          humanSoleusMuscle.sarcomere.IGPNormLengthAtOptimalFiberLength...
    + (n)*humanSoleusMuscle.sarcomere.PEVKNormLengthAtOptimalFiberLength;

    normLengthDistalTitinAtOptimalFiberLengthHuman = ...
        + (1-n)*humanSoleusMuscle.sarcomere.PEVKNormLengthAtOptimalFiberLength ...
        + humanSoleusMuscle.sarcomere.IGDFreeNormLengthAtOptimalFiberLength;

end
if(muscleModel.sarcomere.titinModelType==1)
    %Input Model                        
    normLengthProximalTitinAtOptimalFiberLengthAnimal = ...
          muscleModel.sarcomere.IGPNormLengthAtOptimalFiberLength...
        + muscleModel.sarcomere.IGDFreeNormLengthAtOptimalFiberLength;

    normLengthDistalTitinAtOptimalFiberLengthAnimal = ...
        + muscleModel.sarcomere.PEVKNormLengthAtOptimalFiberLength;
    
    %Human
    normLengthProximalTitinAtOptimalFiberLengthHuman = ...
          humanSoleusMuscle.sarcomere.IGPNormLengthAtOptimalFiberLength...
        + humanSoleusMuscle.sarcomere.IGDFreeNormLengthAtOptimalFiberLength;

    normLengthDistalTitinAtOptimalFiberLengthHuman = ...
        + humanSoleusMuscle.sarcomere.PEVKNormLengthAtOptimalFiberLength;

end

  lPZero = muscleModel.curves.forceLengthProximalTitinCurve.xEnd(1,1);
  lDZero = muscleModel.curves.forceLengthDistalTitinCurve.xEnd(1,1);
  
  
  lPOpt = normLengthProximalTitinAtOptimalFiberLengthAnimal;

  lDOpt = normLengthDistalTitinAtOptimalFiberLengthAnimal;

  lPFiso = calcBezierYFcnXDerivative((1-lambdaECM),...
              muscleModel.curves.('forceLengthProximalTitinInverseCurve'),...
              0);
            
  lDFiso = calcBezierYFcnXDerivative((1-lambdaECM),...
              muscleModel.curves.('forceLengthDistalTitinInverseCurve'),...
              0);

  fpeDomain = muscleModel.curves.('fiberForceLengthCurve').xEnd ...
             +[-0.01,0.01]+[0,1];
  curveSampleFPE = calcBezierYFcnXCurveSampleVector(...
                muscleModel.curves.('fiberForceLengthCurve'), ...
                200,fpeDomain);
%%
% Titin segment
%%

  %Now go and evaluate the ECM and the titin elements at all of the equivalent
  %lengths
  z0 = zeros(size(curveSampleFPE.x));
  
  
[ curveSampleECMHalf,...
  curveSampleTitin,...
  curveSampleTitinActive,...
  curveSampleIgp,...
  curveSamplePevk,...
  curveSampleIgd,...
  curveSampleProximalTitin,...
  curveSampleDistalTitin,...
  curveSampleTwoSegmentTitinActive] = ...
        sampleTitinCurves20250612(curveSampleFPE.x.*0.5,...
                                  muscleModel); 

  lengthZ2Igp  = muscleModel.sarcomere.ZLineToT12NormLengthAtOptimalFiberLength ...
                                         .*ones(size(curveSampleFPE.x));
  lengthZ2Pevk = lengthZ2Igp + curveSampleIgp.x;
  lengthZ2Igd  = lengthZ2Pevk + curveSamplePevk.x;     
  lengthZ2Myosin= lengthZ2Igd + curveSampleIgd.x;  
  lengthCE     = curveSampleFPE.x.*0.5;                  
                  
[ curveSampleECMHalfHuman,...
  curveSampleTitinHuman,...
  curveSampleTitinActiveHuman,...
  curveSampleIgpHuman,...
  curveSamplePevkHuman,...
  curveSampleIgdHuman,...
  curveSampleProximalTitinHuman,...
  curveSampleDistalTitinHuman,...  
  curveSampleTwoSegmentTitinActiveHuman] = ...
  sampleTitinCurves20250612(curveSampleFPE.x.*0.5,...
                    humanSoleusMuscle);   
                  
  lengthZ2IgpHuman  = ...
      humanSoleusMuscle.sarcomere.ZLineToT12NormLengthAtOptimalFiberLength...
      .*ones(size(curveSampleFPE.x));
  lengthZ2PevkHuman     = lengthZ2IgpHuman + curveSampleIgpHuman.x;
  lengthZ2IgdHuman      = lengthZ2PevkHuman + curveSamplePevkHuman.x;  
  lengthZ2MyosinHuman   = lengthZ2IgdHuman + curveSampleIgdHuman.x;
  lengthCEHuman     = curveSampleFPE.x.*0.5;    


%%
% Plot configuration
%%

  xposXTickIgpPevkFL = [lPOpt,lPFiso,lDFiso,lDOpt].*2;
  textXTickIgpPevkFL = {'$$\ell^{1}_{o}$$','$$\ell^{2}_{o}$$',...
                   '$$\ell^{1}_{1-\lambda}$$','$$\ell^{2}_{1-\lambda}$$',...
                   '$$\ell^{T12}+\ell^{1}(f)+\ell^{2}(f)$$'}; 

%  xposXTickIgpPevkFL = [ligpOpt,ligpFiso,lpevkFiso,ltitinOpt].*2;
%  textXTickIgpPevkFL = {'$$\ell^{Igp}_{o}$$','$$\ell^{PEVK}_{o}$$',...
%                   '$$\ell^{Igp}_{1-\lambda}$$','$$\ell^{PEVK}_{1-\lambda}$$',...
%                   '$$\ell^{T12}+\ell^{Igp}(f)+\ell^{PEVK}(f)+\ell^{Igd}$$'};  

  %%
  % PE: IgP, PEVK, Titin
  %%
  idxIgpPevkForceLength = 4;
  idx         =idxIgpPevkForceLength;

  plotProps(idx).xlim   = ([0,0.29] + [-0.01,0.01]);  
  plotProps(idx).ylim   = [0,1] + [-0.01,0.01];
  plotProps(idx).domain = plotProps(idx).xlim + [-0.01,0.01];
                 
                 
  plotProps(idx).xticks      = [1,1].*nan;
  plotProps(idx).xticklabels = {''};
                              
  
                              
  plotProps(idx).yticks      = [0,(1-lambdaECM)];
  plotProps(idx).yticklabels = {'0',['$$',num2str(round(1-lambdaECM,2)),'f^M_o$$']};
  plotProps(idx).lineColor   = [0,0,0];
  plotProps(idx).lineWidth   = 0.5;
%  if(abs(scaleLength-1)<1e-3)
    plotProps(idx).xlabel = 'Normalized Length ($$\ell/\ell^{M}_{o}$$)';
%   else
%     plotProps(idx).xlabel = 'Length ($$\mu$$m)';      
%   end
  plotProps(idx).ylabel = 'Normalized Force ($$f/f^{M}_{o}$$)';
  plotProps(idx).title  = {'D. Rat EDL titin force-length','relation (half-sarcomere)'};  
    
  



  
  figure(fig_pubTitinCurves);
  
  %%
  % Igp + PEVK force-length
  %%    
  figure(fig_pubTitinCurves);  
  subplotTrombitasFigure5 = reshape(subPlotPanel(1,1,:),1,4);
  subplot('Position',subplotTrombitasFigure5);  
  idx=idxTrombitasFigure5_A; 


  normMyosinHalfLengthHuman = ...
    humanSoleusMuscle.sarcomere.normMyosinHalfLength;
  
  zLineToT12NormLengthAtOptimalFiberLengthHuman = ...
    humanSoleusMuscle.sarcomere.ZLineToT12NormLengthAtOptimalFiberLength;

  fillMyosinHumanX = [ (lengthCEHuman.*2).*loptHuman;...
                       ((fliplr(lengthCEHuman')').*2).*loptHuman;...
                       (lengthCEHuman(1).*2).*loptHuman];
%   filly = [(lengthZ2MyosinHuman).*loptHuman; ...
%            ((fliplr(lengthCEHuman')')).*loptHuman;...
%            (lengthZ2MyosinHuman(1)).*loptHuman];

  lengthCEHumanLessMyosin = lengthCEHuman-normMyosinHalfLengthHuman;

  fillMyosinHumanY = [(lengthCEHumanLessMyosin).*loptHuman; ...
                     ((fliplr(lengthCEHuman')')).*loptHuman;...
                     (lengthCEHumanLessMyosin(1)).*loptHuman];  

  fill(fillMyosinHumanX,fillMyosinHumanY,[0,0,0],...
       'EdgeColor','none','FaceAlpha',0.25,...
       'DisplayName','Myosin (human)');
  hold on;

  fillT12HumanX = [(lengthCEHuman.*2).*loptHuman;...
           ((fliplr(lengthCEHuman')').*2).*loptHuman;...
           (lengthCEHuman(1).*2).*loptHuman];

  fillT12HumanY = [ones(size(lengthCEHuman)).*0; ...
              ones(size(lengthCEHuman)).*(loptHuman*zLineToT12NormLengthAtOptimalFiberLengthHuman);...
              0];
  
  fill(fillT12HumanX,fillT12HumanY,[1,1,1].*0.5,...
       'EdgeColor','none','FaceAlpha',0.25,...
       'DisplayName','Z-line--T12');
  hold on;

  hVis ='off';


  plot([1,1].*loptHuman,[0,1.0],'-k','HandleVisibility','off');
  hold on;
  text(loptHuman,1.0,'$$\ell^M_o$$ (human)',...
            'HorizontalAlignment','left',...
            'VerticalAlignment','bottom',...
            'FontSize',6);
  hold on;

  plot( dataTrombitas1998Figure5(2).x,...
        dataTrombitas1998Figure5(2).y,...
        'o','MarkerSize',3, ...
        'MarkerFaceColor',[1,1,1].*0.9,...
        'Color',[1,1,1].*0.75,...
        'DisplayName','Exp: Z-line (ZL) to N-end 9D10',...
        'HandleVisibility',hVis);
  hold on;

  plot( dataTrombitas1998Figure5(1).x,...
        dataTrombitas1998Figure5(1).y,...
        'o','MarkerSize',3, ...
        'MarkerFaceColor',[1,1,1].*0.5,...
        'Color',[1,1,1].*0.5,...
        'DisplayName','Exp: ZL to C-end 9D10',...
        'HandleVisibility',hVis);
  hold on;

  rawColor = [0,0,0];
  
  plot(muscleModel.sarcomere.extra.lineHumanZToPevkP_raw.x,...
       muscleModel.sarcomere.extra.lineHumanZToPevkP_raw.y,...
       '-',...
       'Color',[1,1,1],...
       'LineWidth',plotProps(idx).lineWidth*3,...
       'HandleVisibility','off');
  hold on;

  plot(muscleModel.sarcomere.extra.lineHumanZToPevkP_raw.x,...
       muscleModel.sarcomere.extra.lineHumanZToPevkP_raw.y,...
       '-',...
       'Color',rawColor,...
       'LineWidth',plotProps(idx).lineWidth*2,...
       'DisplayName','Human N-end (LSQ)');
  hold on;

  plot(muscleModel.sarcomere.extra.lineHumanZToPevkD_raw.x,...
       muscleModel.sarcomere.extra.lineHumanZToPevkD_raw.y,...
       '-',...
       'Color',[1,1,1],...
       'LineWidth',plotProps(idx).lineWidth*3,...
       'HandleVisibility','off');
  hold on;

  plot(muscleModel.sarcomere.extra.lineHumanZToPevkD_raw.x,...
       muscleModel.sarcomere.extra.lineHumanZToPevkD_raw.y,...
       '--',...
       'Color',rawColor,...
       'LineWidth',plotProps(idx).lineWidth*2,...
       'DisplayName','Human C-end (LSQ)');
  hold on;


  adjColor = csVib.red;

  plot( (lengthCEHuman.*2).*loptHuman,...
        (lengthZ2PevkHuman).*loptHuman,...
        '-','Color',[1,1,1],...
        'LineWidth',plotProps(idx).lineWidth*3,...
        'HandleVisibility','off');      
  hold on;

  plot( (lengthCEHuman.*2).*loptHuman,...
        (lengthZ2PevkHuman).*loptHuman,...
        '-','Color',adjColor,...
        'LineWidth',plotProps(idx).lineWidth*2,...
        'DisplayName','Human N-end (Adj.)');      
  hold on;
          
  plot( (lengthCEHuman.*2).*loptHuman,...
        (lengthZ2IgdHuman).*loptHuman,...
        '-','Color',[1,1,1],...
        'LineWidth',plotProps(idx).lineWidth*3,...
        'HandleVisibility','off');

  hold on;

  plot( (lengthCEHuman.*2).*loptHuman,...
        (lengthZ2IgdHuman).*loptHuman,...
        '--','Color',adjColor,...
        'LineWidth',plotProps(idx).lineWidth*2,...
        'DisplayName','Human C-end (Adj.)');

  hold on;

  legend('Position',(subplotTrombitasFigure5 + [0,-0.5,0,0]));
  legend boxoff;

  box off

  xticks(plotProps(idx).xticks);
  xticklabels(plotProps(idx).xticklabels);

  yticks(plotProps(idx).yticks);
  yticklabels(plotProps(idx).yticklabels);

  xlim(plotProps(idx).xlim);
  ylim(plotProps(idx).ylim);

  xlabel(plotProps(idx).xlabel);
  ylabel(plotProps(idx).ylabel);
  title(plotProps(idx).title);   
          
  %%
  % Igp + PEVK force-length
  %%    
  figure(fig_pubTitinCurves);  
  subplotTrombitasFigure5 = reshape(subPlotPanel(1,2,:),1,4);
  subplot('Position',subplotTrombitasFigure5);  
  idx=idxTrombitasFigure5_B; 

  normMyosinHalfLength = ...
    muscleModel.sarcomere.normMyosinHalfLength;
  
  zLineToT12NormLengthAtOptimalFiberLength = ...
    muscleModel.sarcomere.ZLineToT12NormLengthAtOptimalFiberLength;

  lengthCELessMyosin = lengthCE-normMyosinHalfLength;

  fillMyosinX = [(lengthCE.*2).*lopt;...
           ((fliplr(lengthCE')').*2).*lopt;...
           (lengthCE(1).*2).*lopt];
  fillMyosinY = [(lengthCELessMyosin).*lopt; ...
           ((fliplr(lengthCE')')).*lopt;...
           (lengthCELessMyosin(1)).*lopt];

  fill(fillMyosinX,fillMyosinY,[csVib.blue],...
       'EdgeColor','none','FaceAlpha',0.25,...
       'DisplayName','Myosin (rat)');
  hold on;

  fillT12X = [(lengthCE.*2).*lopt;...
             ((fliplr(lengthCE')').*2).*lopt;...
             (lengthCE(1).*2).*lopt];
  fillT12Y = [ones(size(lengthCE)).*0; ...
              ones(size(lengthCE)).*(lopt*zLineToT12NormLengthAtOptimalFiberLength);...
              0];
  
  fill(fillT12X,fillT12Y,[csVib.blue].*0.5,...
       'EdgeColor','none','FaceAlpha',0.25,...
       'DisplayName','Z-line--T12');
  hold on;



  fillMyosinHumanX = [(lengthCEHuman.*2).*loptHuman;...
           ((fliplr(lengthCEHuman')').*2).*loptHuman;...
           (lengthCEHuman(1).*2).*loptHuman];
  fillMyosinHumanY = [(lengthCEHumanLessMyosin).*loptHuman; ...
           ((fliplr(lengthCEHuman')')).*loptHuman;...
           (lengthCEHumanLessMyosin(1)).*loptHuman];

  fill(fillMyosinHumanX,fillMyosinHumanY,[0,0,0],...
      'EdgeColor','none','FaceAlpha',0.25,...
       'DisplayName','Myosin (human)');
  hold on;

  fill(fillT12HumanX,fillT12HumanY,[1,1,1].*0.5,...
       'EdgeColor','none','FaceAlpha',0.25,...
       'DisplayName','Z-line--T12');
  hold on;


  hVis ='off';


  plot([1,1].*loptHuman,[0,1.0],'-k','HandleVisibility','off');
  hold on;
  text(loptHuman,1.0,'$$\ell^M_o$$ (human)',...
            'HorizontalAlignment','left',...
            'VerticalAlignment','bottom',...
            'FontSize',6);
  hold on;

  plot([1,1].*lopt,[0,1.2],'-','Color',[0,0,0],'HandleVisibility','off');
  hold on;
  text(lopt,1.2,'$$\ell^M_o$$ (rat)',...
            'HorizontalAlignment','left',...
            'VerticalAlignment','bottom',...
            'FontSize',6,...
            'Color',[0,0,0]);
  hold on;
  


  plot( dataTrombitas1998Figure5(2).x,...
        dataTrombitas1998Figure5(2).y,...
        'o','MarkerSize',3, ...
        'MarkerFaceColor',[1,1,1].*0.9,...
        'Color',[1,1,1].*0.75,...
        'DisplayName','Exp: Z-line (ZL) to N-end 9D10',...
        'HandleVisibility',hVis);
  hold on;

  plot( dataTrombitas1998Figure5(1).x,...
        dataTrombitas1998Figure5(1).y,...
        'o','MarkerSize',3, ...
        'MarkerFaceColor',[1,1,1].*0.5,...
        'Color',[1,1,1].*0.5,...
        'DisplayName','Exp: ZL to C-end 9D10',...
        'HandleVisibility',hVis);
  hold on;

 

  plot( (lengthCEHuman.*2).*loptHuman,...
          (lengthZ2PevkHuman).*loptHuman,...
          '-','Color',[1,1,1],...
          'LineWidth',plotProps(idx).lineWidth*3,...
          'HandleVisibility','off');      
  hold on;
  
  plot( (lengthCEHuman.*2).*loptHuman,...
          (lengthZ2PevkHuman).*loptHuman,...
          '-','Color',adjColor,...
          'LineWidth',plotProps(idx).lineWidth*2,...
          'DisplayName','Human N-end (Adj.)');      
  hold on;
            
  plot( (lengthCEHuman.*2).*loptHuman,...
          (lengthZ2IgdHuman).*loptHuman,...
          '-','Color',[1,1,1],...
          'LineWidth',plotProps(idx).lineWidth*3,...
          'HandleVisibility','off');
  
  hold on;
  
  plot( (lengthCEHuman.*2).*loptHuman,...
          (lengthZ2IgdHuman).*loptHuman,...
          '--','Color',adjColor,...
          'LineWidth',plotProps(idx).lineWidth*2,...
          'DisplayName','Human C-end (Adj.)');
  
  hold on;

  ratColor = csVib.blue;

  plot( (lengthCE.*2).*lopt,...
        (lengthZ2Pevk).*lopt,...
        '-','Color',[1,1,1],...
        'LineWidth',plotProps(idx).lineWidth*3,...
        'HandleVisibility','off');     
  hold on;


  plot( (lengthCE.*2).*lopt,...
        (lengthZ2Pevk).*lopt,...
        '-','Color',ratColor,...
        'LineWidth',plotProps(idx).lineWidth*2,...
        'DisplayName','Rat N-end (model)');     
  hold on;

  plot( (lengthCE.*2).*lopt,...
        (lengthZ2Igd).*lopt,...
        '-','Color',[1,1,1],...
        'LineWidth',plotProps(idx).lineWidth*3,...
        'HandleVisibility','off');
      
  hold on;        
  plot( (lengthCE.*2).*lopt,...
        (lengthZ2Igd).*lopt,...
        '--','Color',ratColor,...
        'LineWidth',plotProps(idx).lineWidth*2,...
        'DisplayName','Rat C-end (model)');
      
  hold on;

  legend('Position',(subplotTrombitasFigure5 + [0,-0.5,0,0]));
  legend boxoff;
 
  box off

  xticks(plotProps(idx).xticks);
  xticklabels(plotProps(idx).xticklabels);

  yticks(plotProps(idx).yticks);
  yticklabels(plotProps(idx).yticklabels);

  xlim(plotProps(idx).xlim);
  ylim(plotProps(idx).ylim);

  xlabel(plotProps(idx).xlabel);
  ylabel(plotProps(idx).ylabel);
  title(plotProps(idx).title);   
          


  %%
  % Passive curve decomposition: total, ecm, titin
  %%    
  figure(fig_pubTitinCurves);  
  subplotPeEcmTitin = reshape(subPlotPanel(2,1,:),1,4);
  subplot('Position',subplotPeEcmTitin);  
  idx=idxPeEcmTitinLength;
  

%   fill([curveSampleECMHalf.x;fliplr(curveSampleECMHalf.x')'].*(2*scaleLength), ...
%        [zeros(size(curveSampleECMHalf.y)); fliplr(curveSampleECMHalf.y')'],...
%         [0.9,0.9,1],'EdgeColor','none','HandleVisibility','off');
%   hold on;  

%   plot( curveSampleECMHalf.x.*(2*scaleLength), ...
%         curveSampleECMHalf.y,...
%         '-','Color',[0,0,1],...
%         'LineWidth',plotProps(idx).lineWidth*2,...
%         'HandleVisibility','off');
%   hold on;    
 
  

  
%   fill([curveSampleTitin.x;fliplr(curveSampleTitin.x')'].*(2*scaleLength), ...
%          [curveSampleECMHalf.y; fliplr(curveSampleTitin.y'+curveSampleECMHalf.y')'],...
%           colorTitinLight,'EdgeColor','none');
%   hold on;  

  curveSamplePassiveTitin.x = curveSampleTitin.x.*(2);
  curveSamplePassiveTitin.y = curveSampleTitin.y+curveSampleECMHalf.y;

  dydxTitin = calcCentralDifferenceDataSeries(...
                curveSamplePassiveTitin.x,...
                curveSamplePassiveTitin.y);
  dydxTitinActive = calcCentralDifferenceDataSeries(...
                      curveSampleTwoSegmentTitinActive.x,...
                      curveSampleTwoSegmentTitinActive.y);
  
%       plot( curveSampleFPE.x, ...
%             curveSampleFPE.y,...
%             '--','Color',[0,0,0],...
%             'LineWidth',plotProps(idx).lineWidth);
%       hold on;   

    for i=1:1:length(passiveForceLengthData)
      displayMod='';
      labelShort = passiveForceLengthData(i).label;
      idxLabel = strfind(labelShort,' ');
      labelShort = labelShort(1:idxLabel(1));
      plotColor = passiveForceLengthData(i).color;
      if(contains(passiveForceLengthData(i).label,'TRSS2017'))
        displayMod=' (fit)';
        plotColor=[0,0,0];
      end

        plot(passiveForceLengthData(i).x./scaleLength,...
             passiveForceLengthData(i).y,...
             passiveForceLengthData(i).mark,...
             'Color',plotColor,...
             'MarkerFaceColor',plotColor,...
             'MarkerSize',2,...
             'LineWidth',plotProps(idx).lineWidth,...
             'DisplayName',[labelShort,displayMod]);
        hold on;

        if(contains(passiveForceLengthData(i).label,'SW1982'))
          displayMod=' (fit)';
          plotColor = [0,0,0];
          idxFit = find(passiveForceLengthData(i).y > 0.3);

          plot(passiveForceLengthData(i).x(idxFit)./scaleLength,...
               passiveForceLengthData(i).y(idxFit),...
               passiveForceLengthData(i).mark,...
               'Color',plotColor,...
               'MarkerFaceColor',plotColor,...
               'MarkerSize',2,...
               'LineWidth',plotProps(idx).lineWidth,...
               'DisplayName',[labelShort,displayMod]);
          hold on;          

        end
        

    end

  plot( curveSampleTitin.x.*(2), ...
        curveSampleTitin.y+curveSampleECMHalf.y,...
        '-','Color',[1,1,1],...
        'LineWidth',plotProps(idx).lineWidth*3,...
        'DisplayName','Titin model (passive)',...
        'HandleVisibility','off');
  hold on;     

  plot( curveSampleTitin.x.*(2), ...
        curveSampleTitin.y+curveSampleECMHalf.y,...
        '-','Color',colorTitinPassive,...
        'LineWidth',plotProps(idx).lineWidth*2,...
        'DisplayName','Titin model (passive)');
  hold on;  

  %%
  %
  % Add the manually adjusted f^{Ti} curve
  %
  %%
  if(~isempty(muscleModel_manual))
      curveSampleFPE_manual = calcBezierYFcnXCurveSampleVector(...
                    muscleModel_manual.curves.('fiberForceLengthCurve'), ...
                    200,fpeDomain);    
      [ curveSampleECMHalf_manual,...
        curveSampleTitin_manual,...
        curveSampleTitinActive_manual,...
        curveSampleIgp_manual,...
        curveSamplePevk_manual,...
        curveSampleIgd_manual,...
        curveSampleProximalTitin_manual,...
        curveSampleDistalTitin_manual,...
        curveSampleTwoSegmentTitinActive_manual] = ...
              sampleTitinCurves20250612(curveSampleFPE_manual.x.*0.5,...
                                        muscleModel_manual); 

      plot( curveSampleTitin_manual.x.*(2), ...
            curveSampleTitin_manual.y+curveSampleECMHalf_manual.y,...
            '-','Color',[1,1,1],...
            'LineWidth',plotProps(idx).lineWidth*3,...
            'DisplayName','Titin model manual (passive)',...
            'HandleVisibility','off');
      hold on;     
    
      plot( curveSampleTitin_manual.x.*(2), ...
            curveSampleTitin_manual.y+curveSampleECMHalf_manual.y,...
            '-','Color',csVib.teal,...
            'LineWidth',plotProps(idx).lineWidth*2,...
            'DisplayName','Titin model manual (passive)');
      hold on;  

%       yTxt=0.9;
%       xTxt = interp1(curveSampleTitin_manual.y+curveSampleECMHalf_manual.y,...
%                      curveSampleTitin_manual.x.*(2),...
%                      yTxt);

      hti = text(0.5, 0.75,...
         sprintf('%s=%1.2f%s\n%s=%1.2f%s',...
          '$$\mathbf{k}^{*}',...
          muscleModel_manual.curves.forceLengthCurveSettings.kToe,...
          'f^M_o/\ell^M_o$$',...
          '$$\Delta \ell^{*}',...
          (muscleModel_manual.curves.forceLengthCurveSettings.normLengthToe...
          -muscleModel.curves.forceLengthCurveSettings.normLengthToe),...
          '\ell^M_o$$'),...
         'FontSize',6,...
         'HorizontalAlignment','right',...
         'VerticalAlignment','top',...
         'Color',csVib.teal);
      hold on;      
  end  

  flag_plotActiveTitin=0;
  
  if(flag_plotActiveTitin==1)
    plot( curveSampleTwoSegmentTitinActive.x.*(2),...
          curveSampleTwoSegmentTitinActive.y+curveSampleECMHalf.y,...
          '-','Color',colorTitinActive,...
          'LineWidth',plotProps(idx).lineWidth,...
          'DisplayName','Titin (active)');
    hold on;   
    
    yTxt = 1;
    yErr = Inf;
    z=length(curveSampleTwoSegmentTitinActive.y);
    while z > 2 && ...
        ((curveSampleTwoSegmentTitinActive.y(z,1)-yTxt)*(curveSampleTwoSegmentTitinActive.y(z-1,1)-yTxt) > 0)
      z=z-1;
    end  
    xTxt = curveSampleTwoSegmentTitinActive.x(z,1);
    yTxt = curveSampleTwoSegmentTitinActive.y(z,1);
  
    hti = text(xTxt*2-0.05, yTxt,...
       sprintf('%s=%1.2f%s',...
        '$$\mathbf{k}^{*}',...
        dydxTitinActive(end),...
        'f^M_o/\ell^M_o$$'),...
       'FontSize',6,...
       'HorizontalAlignment','right',...
       'VerticalAlignment','top',...
       'Color',colorTitinActive);
    hold on;


%     yTxt = 1;
%     xTxt = interp1(curveSampleTwoSegmentTitinActive.y+curveSampleECMHalf.y,...
%                                 curveSampleTwoSegmentTitinActive.x*(2), yTxt);
%     hTa =  text(xTxt+0.1,yTxt,'Titin (active)',...
%          'FontSize',6,...
%          'HorizontalAlignment','right',...
%          'VerticalAlignment','bottom');
%     hold on
%     angle = atan(curveSampleTwoSegmentTitinActive.dydx(end)...
%                  +curveSampleECMHalf.dydx(end))*(180/pi);             
%     set(hTa,'Rotation',angle+labelRotationOffset*0.7);
  end


  

  lambdaECM = muscleModel.sarcomere.extraCellularMatrixPassiveForceFraction;
  
  if(lambdaECM < 1 && lambdaECM > 0)
    text(normFiberLengthAtOneNormPassiveForce,...
         0,...
         ['$$\lambda^{ECM}=',sprintf('%1.2f',lambdaECM),'$$'],...
         'FontSize',8,...
         'HorizontalAlignment','right',...
         'VerticalAlignment','bottom');
    hold on;
  end
      
%       plot(passiveForceLengthData(:,1),...
%            passiveForceLengthData(:,2),...
%            '.','Color',[0,0,1],'MarkerSize',5,...
%            'LineWidth',plotProps(idx).lineWidth);
%       hold on;  

  
  
  

  if(flag_fibrilModel==0)
      yTxt = lambdaECM;
      yErr = Inf;
      z=length(curveSampleECMHalf.y);
      while z > 2 && ...
          ((curveSampleECMHalf.y(z,1)-yTxt)*(curveSampleECMHalf.y(z-1,1)-yTxt) > 0)
        z=z-1;
      end      
      xTxt = curveSampleECMHalf.x(z,1);
      yTxt = curveSampleECMHalf.y(z,1);
      angle = atan(curveSampleECMHalf.dydx(z,1))*(180/pi);
      
      hecm= text(xTxt*2, yTxt,...
           'ECM          ',...
           'FontSize',8,...
           'HorizontalAlignment','right',...
           'VerticalAlignment','top');
      hold on;
      set(hecm,'Rotation',angle+labelRotationOffset*2.5);
      hold on;
  end

  yTxt = 0.5;
  yErr = Inf;
  z=length(curveSampleTitin.y);
  while z > 2 && ...
      ((curveSampleTitin.y(z,1)-yTxt)*(curveSampleTitin.y(z-1,1)-yTxt) > 0)
    z=z-1;
  end  
  xTxt = curveSampleTitin.x(z,1);
  yTxt = curveSampleTitin.y(z,1);

  hti = text(xTxt*2, yTxt,...
     '$$\mathbf{f}^{Ti}(\ell^M)$$',...
     'FontSize',6,...
     'HorizontalAlignment','right',...
     'VerticalAlignment','bottom',...
     'Color',colorTitinPassive);
  hold on;

  yTxt = 1;
  yErr = Inf;
  z=length(curveSampleTitin.y);
  while z > 2 && ...
      ((curveSampleTitin.y(z,1)-yTxt)*(curveSampleTitin.y(z-1,1)-yTxt) > 0)
    z=z-1;
  end  
  xTxt = curveSampleTitin.x(z,1);
  yTxt = curveSampleTitin.y(z,1);

  hti = text(xTxt*2-0.05, yTxt,...
     sprintf('%s=%1.2f%s',...
      '$$\mathbf{k}^{Ti}',...
      dydxTitin(end),...
      'f^M_o/\ell^M_o$$'),...
     'FontSize',6,...
     'HorizontalAlignment','right',...
     'VerticalAlignment','top',...
     'Color',colorTitinPassive);
  hold on;

      
    
  box off

  legend('Position',(subplotPeEcmTitin + [0,-0.5,0,0]));
  legend boxoff;  
  
  
  xticks(plotProps(idx).xticks);
  xticklabels(plotProps(idx).xticklabels);

  yticks(plotProps(idx).yticks);
  yticklabels(plotProps(idx).yticklabels);

  xlim(plotProps(idx).xlim);
  ylim(plotProps(idx).ylim);

  box off;

  xlabel(plotProps(idx).xlabel);
  ylabel(plotProps(idx).ylabel);
  title(plotProps(idx).title);      
  

  %%
  % Igp + PEVK force-length
  %%    
  figure(fig_pubTitinCurves);  
  subplotIgpPevk = reshape(subPlotPanel(2,2,:),1,4);
  subplot('Position',subplotIgpPevk);  
  idx=idxIgpPevkForceLength;


%   curveSampleECMHalf,...
%   curveSampleTitin,...
%   curveSampleTitinActive,...
%   curveSampleIgp,...
%   curveSamplePevk,...
%   curveSampleIgd,...
%   curveSampleProximalTitin,...
%   curveSampleDistalTitin,...
%   curveSampleTwoSegmentTitinActive  
%   colorIgD   = [0,0,1];
%   colorPEVK  = [1,0,0];
%   colorIgp   = [1,0,1];

  plot(curveSampleIgp.x,...
       curveSampleIgp.y,...
       '-','Color',colorIgp,...
       'LineWidth',plotProps(idx).lineWidth*2,...
       'DisplayName','$$\mathbf{f}^{IgP}$$');
  hold on;

  xTitinSegTicks = [0];

  yLabel= 1;
  xLabel = interp1(curveSampleIgp.y,curveSampleIgp.x,yLabel);
  xTitinSegTicks = [xLabel;xTitinSegTicks];

%   text(xLabel,...
%        yLabel,...
%        sprintf('%s=%1.2f%s',...
%       '$$\mathbf{k}^{IgP}',...
%       muscleModel.curves.forceLengthIgPTitinCurve.dydxEnd(2),'$$'),...
%        'FontSize',6,...
%        'Color',colorIgp,...
%        'VerticalAlignment','top',...
%        'HorizontalAlignment','right');
%   hold on;

  text(xLabel,...
       yLabel,...
       sprintf('%1.2f%s',...
         muscleModel.curves.forceLengthIgPTitinCurve.dydxEnd(2),'$$f^M_o/\ell^M_o$$'),...
       'FontSize',6,...
       'Color',colorIgp,...
       'VerticalAlignment','top',...
       'HorizontalAlignment','right');
  hold on;  

  yLabel=0.5;
  xLabel = interp1(curveSampleIgp.y,curveSampleIgp.x,yLabel);
  
  text(xLabel,...
       yLabel,...
       '$$\mathbf{f}^{IgP}$$',...
       'FontSize',6,...
       'Color',colorIgp,...
       'VerticalAlignment','top',...
       'HorizontalAlignment','right');
  hold on;



  plot(curveSamplePevk.x,...
       curveSamplePevk.y,...
       '-','Color',colorPEVK,...
       'LineWidth',plotProps(idx).lineWidth*2,...
       'DisplayName','$$\mathbf{f}^{PEVK}$$');
  hold on;

  yLabel = 1;
  xLabel = interp1(curveSamplePevk.y,curveSamplePevk.x,yLabel);
  xTitinSegTicks = [xLabel;xTitinSegTicks];  

%   text(xLabel,...
%        yLabel,...
%        sprintf('%s=%1.2f%s',...
%       '$$\mathbf{k}^{PEVK}',...
%       muscleModel.curves.forceLengthPevkTitinCurve.dydxEnd(2),'$$'),...
%        'FontSize',6,...
%        'Color',colorPEVK,...
%        'VerticalAlignment','top',...
%        'HorizontalAlignment','left');
%   hold on;
  text(xLabel,...
       yLabel,...
       sprintf('%1.2f%s',...
      muscleModel.curves.forceLengthPevkTitinCurve.dydxEnd(2),'$$f^M_o/\ell^M_o$$'),...
       'FontSize',6,...
       'Color',colorPEVK,...
       'VerticalAlignment','top',...
       'HorizontalAlignment','right');
  hold on;  

  yLabel = 0.5;
  xLabel = interp1(curveSamplePevk.y,curveSamplePevk.x,yLabel);


  text(xLabel,...
       yLabel,...  
       '$$\mathbf{f}^{PEVK}$$',...
       'FontSize',6,...
       'Color',colorPEVK,...
       'VerticalAlignment','top',...
       'HorizontalAlignment','right'); 
  hold on;


  plot(curveSampleIgd.x,...
       curveSampleIgd.y,...
       '-','Color',colorIgd,...
       'LineWidth',plotProps(idx).lineWidth*2,...
       'DisplayName','$$\mathbf{f}^{IgD}$$');
  hold on;
 
  yLabel = 1;
  xLabel = interp1(curveSampleIgd.y,curveSampleIgd.x,yLabel);  
  xTitinSegTicks = [xLabel;xTitinSegTicks];

  text(xLabel,...
       yLabel,...
       sprintf('%1.2f%s',...
       muscleModel.curves.forceLengthIgDTitinCurve.dydxEnd(2),'$$f^M_o/\ell^M_o$$'),...
       'FontSize',6,...
       'Color',colorIgd,...
       'VerticalAlignment','top',...
       'HorizontalAlignment','right');
  hold on;   

  yLabel = 0.5;
  xLabel = interp1(curveSampleIgd.y,curveSampleIgd.x,yLabel);  

  text(xLabel,...
       yLabel,...
       '$$\mathbf{f}^{IgD}$$',...
       'FontSize',6,...
       'Color',colorIgd,...
       'VerticalAlignment','top',...
       'HorizontalAlignment','right'); 
  hold on;



  %%
  % Two segmented titin model
  %%

  flag_add2SegModel=0;

  if(flag_add2SegModel==1)
    yLabel = 0.5;
    xLabel = interp1(curveSampleProximalTitin.y,...
                     curveSampleProximalTitin.x,yLabel);  
  
    xTitinSegTicks = [xLabel;xTitinSegTicks];
  
    text(xLabel,...
         yLabel,...  
         '$$\mathbf{f}^{1}$$',...
         'FontSize',6,...
         'Color',colorProximal,...
         'VerticalAlignment','top',...
         'HorizontalAlignment','right'); 
    hold on;
  
  
    plot(curveSampleProximalTitin.x,...
         curveSampleProximalTitin.y,...
         '-','Color',colorProximal,...
         'LineWidth',plotProps(idx).lineWidth,...
         'DisplayName','$$\mathbf{f}^{1}$$');
    hold on;
   
    yLabel = 1;
    xLabel = interp1(curveSampleProximalTitin.y,...
                     curveSampleProximalTitin.x,yLabel);  
    xTitinSegTicks = [xLabel;xTitinSegTicks];
  
    text(xLabel,...
         yLabel,...
         sprintf('%1.2f%s',...
         muscleModel.curves.forceLengthProximalTitinCurve.dydxEnd(2),'$$f^M_o/\ell^M_o$$'),...
         'FontSize',6,...
         'Color',colorIgd,...
         'VerticalAlignment','top',...
         'HorizontalAlignment','right');
    hold on;  
  
  %
  % Distal segment
  %
  
    yLabel = 0.5;
    xLabel = interp1(curveSampleDistalTitin.y,...
                     curveSampleDistalTitin.x,yLabel);  
  
    xTitinSegTicks = [xLabel;xTitinSegTicks];
  
    text(xLabel,...
         yLabel,...  
         '$$\mathbf{f}^{2}$$',...
         'FontSize',6,...
         'Color',colorProximal,...
         'VerticalAlignment','top',...
         'HorizontalAlignment','right'); 
    hold on;
  
  
    plot(curveSampleDistalTitin.x,...
         curveSampleDistalTitin.y,...
         '-','Color',colorProximal,...
         'LineWidth',plotProps(idx).lineWidth,...
         'DisplayName','$$\mathbf{f}^{2}$$');
    hold on;
   
    yLabel = 1;
    xLabel = interp1(curveSampleDistalTitin.y,...
                     curveSampleDistalTitin.x,yLabel);  
    xTitinSegTicks = [xLabel;xTitinSegTicks];
  
    text(xLabel,...
         yLabel,...
         sprintf('%1.2f%s',...
         muscleModel.curves.forceLengthDistalTitinCurve.dydxEnd(2),'$$f^M_o/\ell^M_o$$'),...
         'FontSize',6,...
         'Color',colorIgd,...
         'VerticalAlignment','top',...
         'HorizontalAlignment','right');
    hold on;  
  end


  box off




  legend('Position',(subplotIgpPevk + [0,-0.5,0,0]));
  legend boxoff;  
  

  xticks( unique(sort(round(xTitinSegTicks,2))) ) ;  

  yticks([0,1]);
  yticklabels({'0','$$f^M_o$$'});

  xlim(plotProps(idx).xlim);
  ylim(plotProps(idx).ylim);

  box off;

  xlabel(plotProps(idx).xlabel);
  ylabel(plotProps(idx).ylabel);
  title(plotProps(idx).title);   



  
  
  here=1;
  pause(0.1);
  figure(fig_pubTitinCurves);  
  pause(0.1);  
  configPlotExporter;
  print('-dpdf', [filePathAndName,'_Pub.pdf']); 
  saveas(fig_pubTitinCurves,filePathAndName,'fig');
  pause(0.1);  
  success=1;